linz/basemaps

- .github/CODEOWNERS
Adding codeowners so pull requests will get automatic reviewers
> build: add codeowners for default pr review

- README.md
Fixes #1 
Simplify readme to things that have been decided.
> Add readme information

- .github/CODEOWNERS
Joe has switched accounts so updated codeowners
> build: joe has switched accounts update codeowners

- .github/workflows/push.yml
- .travis.yml
- Dockerfile
- README.md
- lerna.json
- package.json
- yarn.lock
Adds github actions as a build system
> ci: adding github actions

- yarn.lock
Eslint was triggering a security alert, upgrading eslint
https://www.npmjs.com/advisories/1118
> fix: eslint security alert

- .github/workflows/master.yml
- .github/workflows/push.yml
AWS CDK needs access to access keys to do a cdk diff & deploy
Verify that CICD build process now works on master.
> ci: cdk needs a aws credentials file to exist

- .github/workflows/master.yml
- .github/workflows/push.yml
- packages/_infra/package.json
- packages/_infra/src/index.ts
- packages/_infra/src/serve/index.ts
- packages/_infra/src/serve/lambda.xyz.ts
- packages/lambda-api-tracker/src/index.ts
- packages/lambda-xyz/README.md
- packages/lambda-xyz/jest.config.js
- packages/lambda-xyz/package.json
- packages/lambda-xyz/src/index.ts
- packages/lambda-xyz/src/path.ts
- packages/lambda-xyz/tsconfig.json
- packages/lambda-xyz/webpack.config.js
- packages/shared/src/__test__/lambda.test.ts
- packages/shared/src/lambda.ts
- tsconfig.json
- webpack.config.js
- yarn.lock
> feat: lambda xyz tile server

- .github/workflows/push.yml
- .gitignore
- packages/_infra/src/edge/index.ts
- packages/_infra/src/edge/lambda.edge.api.key.ts
- packages/_infra/src/index.ts
- packages/_infra/src/serve/lambda.xyz.ts
- packages/lambda-xyz/bundle.sh
- packages/lambda-xyz/src/index.ts
- packages/shared/package.json
- packages/shared/src/__test__/bounds.test.ts
- packages/shared/src/__test__/bounds.tile.test.ts
- packages/shared/src/bounds.ts
- packages/shared/src/lambda.ts
- packages/shared/src/projection.ts
- packages/tiler/package.json
- packages/tiler/src/index.ts
- packages/tiler/src/raster.ts
- packages/tiler/src/tiler.ts
- packages/tiler/tsconfig.json
- tsconfig.json
- webpack.config.js
- yarn.lock
Fixes: #12 
Adds a XYZ tiling lambda, this lambda loads COG files from a source S3 bucket and composes them into WebMercator tiles
> Feat/tiler fixes #12

- packages/lambda-xyz/src/index.ts
Adding a second dataset to see if layering works.
Gisborne should now be visible.
> feat: tile multiple datasets

- packages/lambda-xyz/src/index.ts
- packages/shared/src/__test__/bounds.tile.test.ts
- packages/shared/src/__test__/lambda.test.ts
- packages/shared/src/__test__/metrics.test.ts
- packages/shared/src/index.ts
- packages/shared/src/lambda.ts
- packages/shared/src/metrics.ts
- packages/shared/src/session.ts
- packages/tiler/src/raster.ts
- packages/tiler/src/tiler.ts
Improving metric generation so that we can start creating visualizations based off run time of the tiler.
...
> feat: adding improved metrics

- yarn.lock
Upgrades
- `aws-cdk` 1.12.0
- `lerna` 3.16.5
- `@typescript-eslint` 2.3.3
> build: yarn upgrade

- packages/lambda-xyz/package.json
- packages/tiler/package.json
- yarn.lock
Upgrade to cogeotiff 0.4.1, this introduces a number of performance increases when loading in large numbers of geotiffs.
In theory everything should just "work"
> feat: upgrade to cogeotiff 0.4.1

- package.json
- yarn.lock
Adds a command to remove all built files and build cache
`yarn run clean`
> build: add yarn clean to remove built files

- packages/lambda-api-tracker/src/index.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/index.ts
- packages/shared/src/lambda.ts
Include a easy to search name for each lambda
Include useful client metrics in response logging
...
> feat: increase metric tracking

- packages/shared/src/lambda.ts
Include version information
...
> feat: include version information in logs

- .github/workflows/push.yml
- lefthook.yml
- package.json
- packages/_infra/package.json
- yarn.lock
Upgrade deps, fix security audit alert
...
> Build/aws cdk 1.16

- packages/lambda-xyz/package.json
- packages/tiler/package.json
- yarn.lock
Dependabot does not bump multiple packages at the same time
> build: cogeotiff 0.6.0

- packages/lambda-xyz/src/tiff.ts
> feat: gebco bathymetry

- packages/cog/src/builder.ts
- packages/cog/src/cli/cli.ts
- packages/cog/src/cover.ts
- packages/cog/src/gdal.docker.ts
- packages/cog/src/gdal.ts
Fixes: #  
Only apply -addalpha and 3857 reprojection if we really need to.
> fix: not everything needs -addalpha

- packages/lambda-xyz/src/cli/index.ts
- packages/lambda-xyz/static/index.html
Adds a index.html for the local debug server, uses openlayers to visualize any directory of COGs
> feat: serve a webmap when running a local debug server.

- packages/cog/Dockerfile
- packages/cog/README.md
- packages/cog/package.json
- packages/cog/src/builder.ts
- packages/cog/src/cli/actions/action.cog.ts
- packages/cog/src/cli/actions/action.job.ts
- packages/cog/src/cli/index.ts
- packages/cog/src/cog.ts
- packages/cog/src/cog.vrt.ts
- packages/cog/src/file/file.config.ts
- packages/cog/src/file/file.s3.ts
- packages/cog/src/file/file.ts
- packages/cog/src/gdal.docker.ts
- packages/lambda-api-tracker/src/__test__/validate.test.ts
- packages/lambda-xyz/package.json
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/shared/src/__test__/log.spy.ts
- packages/shared/src/aws/credentials.ts
- packages/shared/src/aws/index.ts
- packages/shared/src/aws/object.cache.ts
- packages/shared/src/log.ts
- packages/tiler/package.json
- packages/tiler/src/__test__/tile.benchmark.test.ts
- packages/tiler/src/__test__/tile.creation.test.ts
- yarn.lock
GDAL does not support AWS AssumeRole, so assume the role before calling GDAL and provide the accessKey/secrectAccessKey to the GDAL process instead.
> feat: supply aws credentials to gdal if needed

- packages/cog/src/cli/actions/action.batch.ts
Resume failed jobs, by only recomputing the parts that are needed.
> feat: if output files already exist do not overwrite them.

- packages/lambda-xyz/src/imagery/gebco.ts
- packages/lambda-xyz/src/imagery/index.ts
> refactor: typo in variable name

- packages/_infra/src/cogify/index.ts
Expand cluster size for more cog processing
> build: increase cluster size

- packages/lambda-xyz/src/cli/serve.ts
fixing the internal testing URL so it actually works again
> fix: fixing testing url

- packages/_infra/src/config.ts
Adding a bunch of subdomains to help out older browsers.
> build: adding more domains for the tile servers

- packages/cog/src/cog.ts
- packages/shared/src/file/file.s3.ts
Covnert the progress % into a number so it can be tracked better with monitoring
> refactor: to better log progress, it should be a number

- packages/cog/src/builder.ts
Force load GeoAsciiParams so that the projection finder can read it.
> fix: failed to find projections when geoasciiparams are not loaded

- packages/cog/src/builder.ts
- packages/cog/src/proj/index.ts
Fixes: #  
Adds new check for NZGD_2000 gdal tif desc
> fix: support nzgd_2000

- packages/cog/src/cli/actions/action.batch.ts
Some larger COGs were running low on memory, increase memory available to them
> build: increase batch memory for larger COGs

- packages/cog/src/gdal.command.ts
Log gdal error messages at higher reporting level
> fix: capture stder and report on in if it exists

- packages/lambda-xyz/src/cli/serve.ts
Url for dev testing environment is broken.
> fix: correct a broken testing url

- .github/workflows/push.yml
Fixes: #  
Publish task
Added github action for npm push
...
> feat: add npm publish action

- packages/lambda-shared/package.json
- packages/lambda-shared/src/aws/api.key.table.ts
- packages/lambda-shared/src/cli/api.key.ts
- yarn.lock
> feat: cli script to create api keys

- packages/lambda-xyz/src/cli/serve.ts
- packages/lambda-xyz/src/router.ts
> fix: dont allow invalid urls to be passed to the rendering engine.

- packages/lambda-shared/src/__test__/vdom.test.ts
- packages/lambda-shared/src/index.ts
- packages/lambda-shared/src/vdom.ts
To create XML documents use a virtual dom then render it to a string
> feat: simple virtual dom creator

- .github/workflows/push.yml
- packages/cog/src/cli/actions/action.cog.ts
- packages/cog/src/cli/actions/action.job.ts
Add a step to validate that no files were modified in build & lint steps.
> chore: validate that no files need to be formatted

- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/wmts.capability.ts
> fix(wmts): don't add api key if blank

- .github/workflows/push.yml
- packages/_infra/src/config.ts
> chore: enable public development urls

- packages/_infra/package.json
- yarn.lock
> build(deps): aws-cdk 1.31

- packages/lambda-shared/src/aws/tile.metadata.table.ts
> perf(metadata): avoid extra loop when fetching images

- packages/geo/src/projection.ts
- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
> fix(projection.toUrn): Don't include EPSG database version

- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/wmts.capability.ts
> fix(wmts): set max zoom to 22

- packages/cog/src/cli/cogify/action.batch.ts
> fix: action.batch missing await before storeLocal

- packages/lambda-shared/package.json
- packages/lambda-shared/src/__test__/vdom.parse.test.ts
- packages/lambda-shared/src/index.ts
- packages/lambda-shared/src/vdom.parse.ts
- packages/lambda-shared/src/vdom.ts
- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- yarn.lock
Parse VRT files into VDom so we can modify the file locations.
> feat: parse vrt files so we can modify them

- packages/_infra/package.json
- yarn.lock
AWS-CDK does not like being upgraded by dependabot :(
> build(deps): aws-cdk 1.33.1

- packages/cog/src/cog/builder.ts
> chore(cog/builder): log more info for multi-projections

- packages/_infra/package.json
- yarn.lock
Upgrade AWS CDK as dependabot does not do it :(
> build(deps): aws-cdk 1.34.1

- packages/cog/src/proj/__test__/index.test.ts
- packages/cog/src/proj/index.ts
look for the full NZTM name rather than the NZGD which may or may not actually be NZTM
> refactor: improve guessing logic to be more correct

- package.json
- yarn.lock
https://www.npmjs.com/advisories/1500
> security: force yargs-parser to >=18.1.1

- packages/cog/src/cli/cogify/action.job.ts
- packages/cog/src/cog/__test__/cutline.test.ts
- packages/cog/src/cog/constants.ts
- packages/cog/src/cog/cutline.ts
Increase fine zoom level by two for better cog creation
> feat(cog): create finer quadkeys for coverings

- packages/cog/src/cli/cogify/action.cog.ts
- packages/cog/src/cli/cogify/action.job.ts
- packages/lambda-shared/src/file/__test__/file.local.test.ts
- packages/lambda-shared/src/file/file.local.ts
- packages/lambda-shared/src/file/file.s3.ts
Store the job cutline as a gzipped file
> feat(cog): GZip cutline.geojson

- packages/_infra/src/cogify/index.ts
> fix(cli): assume any role provided by the cli

- packages/cog/src/cli/basemaps/__test__/test.update.test.ts
- packages/cog/src/cli/basemaps/action.tileset.update.ts
- packages/cog/src/cli/basemaps/tileset.util.ts
- packages/lambda-shared/src/aws/tile.metadata.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda-xyz/src/tile.set.ts
- packages/tiler-sharp/src/__test__/tile.benchmark.ts
- packages/tiler-sharp/src/__test__/tile.creation.test.ts
- packages/tiler-sharp/src/index.ts
- packages/tiler/src/raster.ts
> feat: support rendering different backgrounds for tiles

- packages/lambda-shared/src/__test__/vdom.test.ts
- packages/lambda-shared/src/vdom.ts
- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/wmts.capability.ts
The TileMatrixSet was missing an identifier for individual imagery sets
> fix(lambda-xyz): add missing identifier for WMTS individual set

- packages/_infra/src/cogify/index.ts
> fix(infra): docker environment needs to be name/value pairs

- packages/cli/src/cli/cogify/action.cog.ts
> fix(cli): jobs are not backwards compatabile yet

- packages/cli/src/cli/cogify/action.cog.ts
- packages/cli/src/cog/job.ts
- packages/cli/src/gdal/gdal.command.ts
- packages/cli/src/gdal/gdal.docker.ts
- packages/cli/src/gdal/gdal.ts
When running gdal commands log out the output of `--version`
> feat: log gdal version

- packages/cli/package.json
- packages/cli/src/cli/basemaps/action.tileset.info.ts
- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/cli/src/cli/cli.table.ts
- yarn.lock
> build(deps): remove chalk in favour of ansi-colors

- packages/cli/src/cog/cog.ts
- packages/cli/src/cog/cog.vrt.ts
- packages/cli/src/gdal/gdal.command.ts
> fix(cli): gdal progress dots are not on every gdal command

- packages/cli/src/cog/cutline.ts
- packages/geo/src/__tests__/bounds.test.ts
- packages/geo/src/__tests__/quad.key.test.ts
- packages/geo/src/__tests__/testhelper.ts
- packages/geo/src/bounds.ts
- packages/geo/src/quad.key.ts
Work towards consolidating NZTM changes
> refactor(geo): remove QuadKey dependency from Bounds

- packages/geo/src/index.ts
- packages/lambda-shared/src/aws/tile.metadata.base.ts
- packages/lambda-shared/src/index.ts
- packages/lambda-shared/src/wmts/wmts.ts
- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/__test__/xyz.util.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda-xyz/src/tile.set.ts
- packages/lambda-xyz/src/wmts.capability.ts
- scripts/detect.unlinked.dep.js
> feat(wmts): support multiple layers and multiple projections

- packages/geo/src/__tests__/tms.quad.key.test.ts
- packages/geo/src/tms.quad.key.ts
> feat(geo): find the closest psuedo quadkeys for a given tile

- packages/geo/src/tile.matrix.set.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/cli/tile.set.local.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda-xyz/src/tile.set.ts
>  feat(lambda-xyz): support rendering tiles where the tile matrix set is not a quad

- packages/_infra/package.json
- yarn.lock
> build(deps): aws-cdk 1.46.0

- packages/landing/scripts/bundle.js
- packages/landing/src/__test__/hash.test.ts
- packages/landing/src/debug.ts
- packages/landing/src/index.ts
- packages/landing/src/url.ts
- packages/landing/static/index.css
- packages/landing/static/index.html
> feat(landing): adding debug information to map when ?debug=true

- packages/landing/src/debug.ts
- packages/landing/static/index.css
> feat(landing): track mouse position in debug mode

- packages/geo/src/__tests__/tile.matrix.set.test.ts
- packages/geo/src/tile.matrix.set.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/routes/tile.ts
> fix(lambda-xyz): 404 when a user requests a tile outside of the tms zoom range

- .kodiak.toml
As it appears in the github tag list near the top
> build: switch to "automerge 🚀"

- packages/landing/src/ui.ts
- packages/landing/static/index.css
- packages/landing/static/index.html
NZTM xyz doesnt really make sense as there is no "standard" xyz that ESRI/QGIS/web mapping uses
> feat(landing): hide xyz nztm

- packages/cli/Dockerfile
> fix(cli): docker index.js in not executable

- packages/landing/static/index.css
- packages/landing/static/index.html
Header/Footer now align in mobile resolutions
Additional work is needed to make the mobile experience better.
Adds github link
> feat(landing): improve styles for mobile devices

- packages/landing/src/config.ts
- packages/landing/src/map.ts
- packages/landing/src/ui.ts
record how long tiles take to load for users
> feat(landing): report tile loading stats

- packages/lambda/src/__test__/router.test.ts
- packages/lambda/src/header.ts
- packages/lambda/src/router.ts
Needed for https://github.com/linz/basemaps-team/issues/227
> fix(lambda): Set Cors header on GET requests

- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/wmts.capability.ts
Fixes: #
Added a Layer/Content/Identifier tag for WMTSCapabilities doc so it can be read by openlayers
> fix(wmts): add identifier

- packages/landing/src/ui.ts
- packages/landing/static/index.html
See https://confluence.linz.govt.nz/pages/viewpage.action?spaceKey=LTS&title=Contact+us+-+basemaps
> feat(landing): Add content to contact us mailto: link

- packages/cli/src/cli/cogify/action.cog.ts
- packages/cli/src/cog/__test__/cog.test.ts
- packages/cli/src/cog/__test__/cog.vrt.test.ts
- packages/cli/src/cog/cog.ts
- packages/cli/src/cog/cog.vrt.ts
- packages/cli/src/cog/job.ts
- packages/cli/src/gdal/__test__/gdal.test.ts
- packages/cli/src/gdal/gdal.cog.ts
- packages/cli/src/gdal/gdal.command.ts
- packages/cli/src/gdal/gdal.docker.ts
- packages/cli/src/gdal/gdal.local.ts
- packages/cli/src/gdal/gdal.ts
- packages/cli/src/index.ts
BREAKING CHANGE: this changes how to get access to a new gdal instance to `Gdal.create()`
> feat: improve access to the GDAL cli

- packages/cli/src/cog/__test__/cog.vrt.test.ts
- packages/cli/src/cog/cog.vrt.ts
`gdalbuildvrt` degrades the image quality if the `-tr` option is given
> fix(cli): improve image quality when fully zoomed in

- packages/cli/src/cog/builder.ts
> fix(cli): correct error message when failing to read

- packages/landing/src/config.ts
- packages/landing/src/map.ts
- packages/landing/src/ui.ts
Events were not actually being sent..
Now they are actually being sent and received in google analytics
> fix(landing): google analytic events were not being sent

- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/__test__/xyz.test.ts
- packages/lambda-xyz/src/wmts.capability.ts
Fixes: #
Added Style tag to Layer/Content setting title/id as default
> fix(wmts): add style tag to wmtscaps

- packages/landing/src/map.ts
This also remembers changes allowing history browsing
> feat(landing): allow changing map position via url

- packages/lambda-xyz/src/index.ts
> feat(lambda-xyz): log out api key used to request the tile

- .github/workflows/push.yml
- package.json
- packages/_infra/src/cogify/index.ts
- packages/_infra/src/edge/lambda.edge.api.key.ts
- packages/_infra/src/serve/lambda.xyz.ts
- packages/_infra/src/version.ts
- packages/cli/package.json
- packages/cli/src/cli/base.cli.ts
- packages/cli/src/cli/cogify/action.batch.ts
- packages/cli/src/cli/folder.ts
- packages/cli/src/gdal/gdal.docker.ts
- packages/cli/src/gdal/gdal.ts
- packages/lambda-api-tracker/package.json
- packages/lambda-xyz/bundle.sh
- packages/lambda-xyz/package.json
- packages/lambda-xyz/src/__test__/index.test.ts
- packages/lambda-xyz/src/cli/serve.ts
- packages/lambda-xyz/src/routes/api.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda/src/lambda.ts
- packages/landing/package.json
- packages/shared/src/__test__/env.test.ts
- packages/shared/src/const.ts
- scripts/bundle.js
- yarn.lock
Lambda@edge does not support environment variabile injection, so we need to hard code these values in
> fix: inject git version and hash into all code

- packages/__tests__/src/rounding.ts
- packages/lambda-xyz/src/__test__/wmts.capability.test.ts
- packages/lambda-xyz/src/png.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda-xyz/src/tile.set.cache.ts
Remove obsolete `EmptyPng`
Rename `roundString` to `roundNumbersInString` and improve its correctness
> chore(lambda-xyz): code tidy up

- packages/cli/src/cog/job.ts
- packages/shared/src/file/file.config.ts
This enables us to provide a very specific file order to the cogification process
> feat(cli): support giving exact list of files to use

- scripts/bundle.js
> build: fix issue where spaces could be present in folder names

- packages/_infra/src/config.ts
- packages/_infra/src/serve/lambda.xyz.ts
> feat(infra): give dev readonly access to production COGs

- packages/cli/src/cli/cogify/action.cog.ts
Fixes: #
Removed version check from action.cog since no longer needed
> fix: remove unneeded semver check

- packages/cli/src/cli/basemaps/__test__/test.update.test.ts
- packages/cli/src/cli/basemaps/action.tileset.update.ts
- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/lambda-xyz/src/__test__/tile.cache.key.test.ts
- packages/lambda-xyz/src/cli/dump.ts
- packages/lambda-xyz/src/routes/tile.ts
- packages/lambda-xyz/src/tile.set.ts
- packages/shared/src/aws/tile.metadata.base.ts
- packages/tiler-sharp/src/__test__/tile.benchmark.ts
- packages/tiler-sharp/src/__test__/tile.creation.test.ts
- packages/tiler-sharp/src/index.ts
- packages/tiler/src/__test__/tiler.test.ts
- packages/tiler/src/raster.ts
- packages/tiler/src/tiler.ts
for some types of imagery nearest is better for resizing
> feat: allow configuration of tile resize kernels

- packages/lambda/src/header.ts
- packages/lambda/src/lambda.ts
ELB Tracing: https://aws.amazon.com/premiumsupport/knowledge-center/trace-elb-x-amzn-trace-id/
Cloudfront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html
> feat(lambda): trace cloudfront request and trace id's

- packages/landing/src/__test__/hash.test.ts
- packages/landing/src/url.ts
> feat(landing): support urls with z14 or 14z

- .eslintrc.js
- .prettierrc.js
- package.json
- packages/bathymetry/src/__test__/stac.test.ts
- packages/bathymetry/src/stac.ts
- packages/cli/src/cli/basemaps/__test__/test.update.test.ts
- packages/cli/src/cli/cogify/action.cog.ts
- packages/lambda-tiler/src/__test__/tile.set.cache.test.ts
- packages/lambda/src/lambda.aws.ts
- packages/landing/src/config.ts
- yarn.lock
convert to LINZ's lint/build/format
> refactor: linz stylejs

- packages/bathymetry/package.json
- packages/bathymetry/src/__test__/stac.test.ts
- packages/bathymetry/src/bathy.maker.ts
- packages/bathymetry/src/index.ts
- packages/bathymetry/src/stac.ts
- packages/cli/src/cli/cogify/action.batch.ts
- packages/cli/src/cog/__test__/cog.stac.job.test.ts
- packages/cli/src/cog/cog.stac.job.ts
- packages/cli/src/cog/stac.ts
- packages/shared/src/__test__/util.test.ts
- packages/shared/src/index.ts
- packages/shared/src/stac/index.ts
- packages/shared/src/util.ts
1. Refactor STAC interface; move to shared.
2. Add a bathymetry collection.json
3. Improve STAC Item compliance in bathymetry and cog creation
> feat(shared): align bathymetry STAC usage with cog creation

- .kodiak.toml
- Include the pull request comment in the merge commit.
- Include co-authors if there are any
- Include a link to the pull request
> build: include more information in kodiak merges

- packages/lambda-tiler/src/routes/tile.ts
- packages/lambda/src/__test__/lambda.test.ts
- packages/lambda/src/lambda.ts
Most of these metrics were duplicated in the log line and can be removed without loosing log information
> feat(lambda): reduce log volumes

- packages/_infra/package.json
- packages/_infra/src/log/__test__/log.filter.test.ts
- packages/_infra/src/log/index.ts
- yarn.lock
> feat(infra): drop out lambda start/end/report logs from being shipped to elasticsearch

- packages/bathymetry/package.json
- packages/bathymetry/src/__test__/hash.test.ts
- packages/bathymetry/src/__test__/stac.test.ts
- packages/bathymetry/src/__test__/test-file.txt
- packages/bathymetry/src/bathy.maker.ts
- packages/bathymetry/src/file.ts
- packages/bathymetry/src/hash.ts
- packages/bathymetry/src/index.ts
- packages/bathymetry/src/mapnik.ts
- packages/bathymetry/src/stac.ts
- packages/cli/src/cog/__test__/cog.stac.job.test.ts
- packages/cli/src/cog/cog.vrt.ts
- packages/cli/src/gdal/gdal.docker.ts
- packages/shared/src/__test__/util.test.ts
- packages/shared/src/file/__test__/file.operator.test.helper.ts
- packages/shared/src/util.ts
Also use source bucket collection.json for title, description, interval and provider details
> feat(bathymetry): allow input and output from s3 bucket

- .github/workflows/push.yml
- .github/workflows/version.yml
This uses the workflow_dispatch event to allow maintainers to version bump from the github ui
> ci: create a workflow to version bump and deploy basemaps

- packages/lambda-tiler/src/__test__/wmts.capability.test.ts
- packages/lambda-tiler/src/__test__/xyz.test.ts
- packages/lambda-tiler/src/wmts.capability.ts
Was referring to a particular EPSG but different EPSGs are collated with the same layer
> fix(lambda-tiler): Remove epsg from wmts layer id

- .github/workflows/push.yml
- packages/shared/src/cli/__test__/git.tag.test.ts
- scripts/tag.sh
> ci: group the deployment steps by env

- packages/_infra/src/serve/index.ts
> feat(infra): check the health of the tiler every 30 seconds

- package.json
- packages/cli/src/cog/job.factory.ts
- packages/lambda-tiler/src/cli/tile.set.local.ts
- packages/linzjs-s3fs/src/__tests__/file.s3.test.ts
- packages/linzjs-s3fs/src/file.s3.ts
- yarn.lock
> fix(linzjs-s3fs): allow fs.list to list buckets and not need a "key"

- packages/_infra/package.json
- packages/_infra/src/analytics/edge.analytics.ts
- packages/_infra/src/config.ts
- packages/_infra/src/edge/index.ts
- packages/_infra/src/index.ts
- packages/_infra/src/log/index.ts
- packages/_infra/src/parameters.ts
- packages/_infra/src/serve/index.ts
- packages/_infra/src/serve/lambda.tiler.ts
- packages/lambda-analytics/README.md
- packages/lambda-analytics/package.json
- packages/lambda-analytics/src/__tests__/file.process.test.ts
- packages/lambda-analytics/src/__tests__/index.test.ts
- packages/lambda-analytics/src/file.process.ts
- packages/lambda-analytics/src/index.ts
- packages/lambda-analytics/src/stats.ts
- packages/lambda-analytics/tsconfig.json
- packages/shared/src/const.ts
- tsconfig.json
- yarn.lock
Create analytics based on usage for long term tracking of api keys and their use.
> feat(lambda-analytics): generate rolledup analyitics from cloudwatchedge logs

- packages/lambda-analytics/src/__tests__/file.process.test.ts
- packages/lambda-analytics/src/__tests__/index.test.ts
- packages/lambda-analytics/src/file.process.ts
- packages/lambda-analytics/src/index.ts
- packages/lambda-analytics/src/stats.ts
> feat(lambda-analytics): allow analytics to be reprocessed by removing  the cached data

- packages/landing/src/__test__/api.test.ts
- packages/landing/src/api.ts
> feat(landing): generate new api key for users every 30 days

- packages/cli/src/cog/job.factory.ts
- packages/lambda-analytics/src/__tests__/index.test.ts
- packages/lambda-analytics/src/index.ts
- packages/lambda-tiler/src/cli/tile.set.local.ts
- packages/linzjs-s3fs/src/__tests__/file.local.test.ts
- packages/linzjs-s3fs/src/__tests__/file.s3.test.ts
- packages/linzjs-s3fs/src/file.local.ts
- packages/linzjs-s3fs/src/file.s3.ts
- packages/linzjs-s3fs/src/file.ts
- packages/linzjs-s3fs/src/index.ts
BREAKING CHANGE: this changes the list return type from a string[] to a
string generator, a utility toArray has been added to convert the
generator back to a string[]
> feat(linzjs-s3fs): .list is now a async generator to allow easier iterating of folders

- .github/dependabot.yml
- package.json
- packages/bathymetry/tsconfig.json
- packages/lambda-analytics/package.json
- packages/lambda-api-tracker/package.json
- packages/lambda-tiler/package.json
- packages/lambda-tiler/src/cli/dump.ts
- packages/lambda-tiler/tsconfig.json
- packages/lambda/tsconfig.json
- packages/landing/package.json
- packages/landing/tsconfig.json
- packages/shared/package.json
- yarn.lock
> build(deps): upgrade @types/node

- packages/cli/src/cli/cogify/action.batch.ts
- packages/cli/src/cog/cog.stac.job.ts
> fix(cli): correct permissions when creating cogs

- package.json
- yarn.lock
> fix(deps): allow yargs to be upgraded to newer versions

- packages/cli/src/cli/basemaps/__test__/tileset.updater.test.ts
- packages/cli/src/cli/basemaps/tileset.updater.ts
- packages/shared/src/aws/__test__/tile.metadata.tileset.test.ts
Was only working for existing tags
> fix(cli): allow using new tag

- .github/CODEOWNERS
> build: add Wentao to code owners 🎉

- packages/_infra/src/serve/index.ts
> feat(infra): actually check the health of the lambda before deploying

- packages/shared/src/aws/__test__/tile.metadata.tileset.test.ts
- packages/shared/src/aws/tile.metadata.base.ts
- packages/shared/src/aws/tile.metadata.tileset.ts
- packages/shared/src/index.ts
I have added an iterator and splitId() into TileMetadataTileSet for vacuum imagery to use. Please have a look. Thanks.
> feat(shared): Add iterator into TileMetadataTileSet.

- packages/cli/src/cli/basemaps/action.export.ts
- packages/cli/src/cli/basemaps/action.import.ts
- packages/cli/src/cli/basemaps/action.invalidate.ts
- packages/cli/src/cli/basemaps/action.tileset.history.ts
- packages/cli/src/cli/basemaps/action.tileset.info.ts
- packages/cli/src/cli/basemaps/action.tileset.tag.ts
- packages/cli/src/cli/basemaps/action.tileset.update.ts
- packages/cli/src/cli/basemaps/tileset.action.ts
- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/cli/src/cli/provider/action.provider.info.ts
- packages/cli/src/cli/provider/action.provider.tag.ts
- packages/cli/src/cli/tag.action.ts
> refactor(cli): standardise the parameter names of all the cli tools

- packages/landing/static/index.css
Currently in dev
After this PR
> fix(landing): fix broken button styling

- packages/cli/src/cog/builder.ts
> fix(cli): detect if differing band counts of imagery is used in a single imagery set

- packages/lambda-tiler/src/__test__/wmts.capability.test.ts
- packages/lambda-tiler/src/wmts.capability.ts
> feat(lambda-tiler): support NZTM2000Quad when serving via WMTS

- packages/bathymetry/src/__test__/stac.test.ts
- packages/bathymetry/src/bathy.maker.ts
- packages/bathymetry/src/index.ts
- packages/bathymetry/src/stac.ts
> feat(bathymetry): support other tile matrix sets for rendering bathymetry

- packages/bathymetry/src/bathy.maker.ts
> fix(bathymetry): actually use the supplied tile matrix rather than defaulting to GoogleTms

- packages/bathymetry/src/index.ts
- packages/geo/src/tile.matrix.set.ts
- packages/lambda-tiler/src/tile.set.ts
- packages/tiler/src/__test__/tiler.test.ts
> feat(bathymetry): generate the bathy tiles based on the output tile matrix set not hard coded

- packages/cli/src/cli/basemaps/tileset.updater.ts
- packages/geo/src/__tests__/tile.matrix.set.test.ts
- packages/geo/src/tile.matrix.set.ts
> fix(geo): correctly find the closest zoom from a given scale

- packages/lambda-tiler/src/__test__/tile.set.test.ts
- packages/lambda-tiler/src/tile.set.ts
> refactor(lambda-tiler): use correct zoom level for filtering

- packages/lambda-tiler/src/__test__/tile.set.test.ts
- packages/lambda-tiler/src/tile.set.ts
> fix(lambda-tiler): correct mapping of high zoom levels

- packages/landing/src/ui.ts
> fix(landing): correctly set the projection for the copy link buttons

- package.json
- scripts/bundle.js
- scripts/detect.unlinked.dep.js
- yarn.lock
> build(deps): switch to @linzjs/style 2.0.0

- packages/lambda-tiler/src/routes/__test__/attribution.test.ts
- packages/lambda-tiler/src/routes/attribution.ts
- packages/lambda-tiler/src/tile.set.ts
since the zoom levels vary based on tile matrix generate a custom attribution with fixed zoom levels
> fix(lambda-tiler): generate a custom attribution for nztm2000quad

- package.json
- yarn.lock
> Build(lerna): Update Lerna dependencies to fix prototype pollution

- packages/landing/package.json
- packages/landing/static/index.html
- yarn.lock
Fixes a issue where the CSS version was out of sync with the javascript version.
> fix(landing): import maplibre styles from the npm package

- packages/linzjs-s3fs/src/abstractions/file.s3.ts
`FsS3.fromRoleArn('arn:...:foo', 'ec2');` Use the EC2 credentials to assume role foo
`FsS3.fromRoleArn('arn:...:bar', process.env.AWS_PROFILE);` Use the $AWS_PROFILE to load credentials from the shared ini and assume role bar
> feat: add fromRoleArn to simplify the creation of s3 bound to specific roles.

- .github/workflows/push.yml
- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/config/src/base.config.ts
- packages/config/src/dynamo/__tests__/config.imagery.test.ts
- packages/config/src/dynamo/dynamo.config.ts
- packages/config/src/index.ts
- packages/config/src/instance.ts
- packages/lambda-tiler/src/__test__/tile.set.cache.test.ts
- packages/lambda-tiler/src/routes/attribution.ts
- packages/lambda-tiler/src/tile.set.cache.ts
- packages/lambda-tiler/src/tile.set.raster.ts
- packages/shared/src/aws/index.ts
This makes it much easier to replace with a different config source (s3/JSON files)
> refactor: simplify the config interface

- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/config/src/base.config.ts
- packages/config/src/color.ts
- packages/config/src/dynamo/dynamo.config.ts
- packages/config/src/index.ts
- packages/lambda-tiler/package.json
- packages/lambda-tiler/src/tile.set.cache.ts
- packages/lambda-tiler/test-serve.js
- packages/server/README.md
- packages/server/bin/basemaps-server
- packages/server/package.json
- packages/server/src/cli.ts
- packages/server/src/index.ts
- packages/server/src/server.ts
- packages/server/tsconfig.json
- tsconfig.json
- yarn.lock
this adds a `basemaps-server` cli that can be used with the linz/basemaps-config repository to create a self hosted cli for the imagery
> feat(server): create a standalone express server

- packages/cli/src/cli/base.cli.ts
- packages/cli/src/cli/basemaps/index.ts
- packages/lambda-tiler/src/cli/dump.ts
- packages/lambda-tiler/src/cli/serve.ts
- packages/server/bin/basemaps-server.js
- packages/server/src/cli.ts
- packages/server/src/server.ts
- packages/shared/src/log.ts
This gives a much better logging output by default
This also enforces pretty printing of logs when run from the console
> feat(server): use the lambda handler directly

- packages/_infra/package.json
- yarn.lock
See https://github.com/aws/aws-cdk/issues/17457
> fix(infrastructure): revert aws-cdk to 1.111 until ALB target bug is fixed

- Dockerfile
> fix(docker): container should only build and not test

- packages/landing/src/components/map.tsx
`Config.map.transformedLocation` is used by update url location which transform current map location to google. But the loadiing map by url need to transform location from google to current map projection.
> fix(landing): Fix the loading map by url coordinates for nztm

- packages/tiler-sharp/src/index.ts
This greatly improves performance where no image parsing/adjustments have to be made to the image.
From ~20-30ms to generally <1ms when serving from a local COG
> perf(tiler-sharp): if the output tile is the exact same as the input tiff tile serve the tiff tile directly

- packages/tiler-sharp/src/index.ts
this reduces the time to create these images from 5-10ms to 0ms.
> perf(tiler-sharp): cache empty images as they are requested a lot

- packages/shared/package.json
- yarn.lock
this includes its own types now so no need for `@types/pino`
> build(deps): pino 7.5.0

- packages/lambda-tiler/src/routes/imagery.ts
Lambda's have a hard limit of 5MB of output before erroring..
> feat(lambda-tiler): compress geojson output to prevent overflowing lambda

- packages/landing/src/components/debug.tsx
> feat(landing): show source id when hovering in the source layer

- packages/cli/src/cli/basemaps/tileset.util.ts
- packages/config/src/base.config.ts
- packages/config/src/dynamo/__tests__/config.imagery.test.ts
- packages/config/src/dynamo/dynamo.config.base.ts
- packages/config/src/dynamo/dynamo.config.cached.ts
- packages/lambda-tiler/src/__test__/tile.set.cache.test.ts
- packages/lambda-tiler/src/routes/attribution.ts
- packages/lambda-tiler/src/tile.set.raster.ts
- feat(config): remove unused helper functions
- fix(config): sometimes batch will not return all keys
> fix(config): fetch all unprocessed keys from dynamo if there are any

- packages/attribution/src/__tests__/attr.test.ts
- packages/config/src/config/imagery.ts
- packages/geo/src/stac/stac.attribution.ts
- packages/lambda-tiler/src/routes/__test__/attribution.test.ts
- packages/lambda-tiler/src/routes/attribution.ts
- feat(config): remove imagery year and resoltuion from config as it is not used
- feat(config): gsd is not used either
> feat(config): remove imagery year and resoltuion from config as it is not used

- CHANGELOG.md
- lerna.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/attribution/CHANGELOG.md
- packages/attribution/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/geo/CHANGELOG.md
- packages/geo/package.json
- packages/lambda-analytics/CHANGELOG.md
- packages/lambda-analytics/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/shared/CHANGELOG.md
- packages/shared/package.json
- packages/tiler-sharp/CHANGELOG.md
- packages/tiler-sharp/package.json
- packages/tiler/CHANGELOG.md
- packages/tiler/package.json
This reverts commit cb432306b10eb3e973db6fdaf85a606884115d55.
> Revert "release: v6.22.0 (#2108)"

- CHANGELOG.md
- lerna.json
- packages/_infra/CHANGELOG.md
- packages/attribution/CHANGELOG.md
- packages/bathymetry/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/geo/CHANGELOG.md
- packages/lambda-analytics/CHANGELOG.md
- packages/lambda-tiler/CHANGELOG.md
- packages/landing/CHANGELOG.md
- packages/server/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/tiler-sharp/CHANGELOG.md
- packages/tiler/CHANGELOG.md
This reverts commit d57532186c445aa3b03efe3d91645c4efb2d714d.
> Revert "release: v6.21.0 (#2104)"

- packages/lambda-tiler/src/__test__/route.test.ts
- packages/lambda-tiler/src/router.ts
- fix(lambda-tiler): decode url paths to support utf8 characters
- test: add emoji tests
> fix(lambda-tiler): decode utf8 path names

- packages/_infra/src/config.ts
- packages/lambda-cog/src/import/make.cog.ts
> feat(lambda-cog): reduce the max pixel size and increase the limit of processing size

- packages/config/src/base.config.ts
- packages/config/src/dynamo/dynamo.config.ts
- packages/config/src/index.ts
- packages/config/src/json/json.config.ts
- packages/config/src/json/log.ts
- packages/config/src/json/parse.provider.ts
- packages/config/src/json/parse.style.ts
- packages/config/src/json/parse.tile.set.ts
- packages/config/src/memory/__tests__/memory.config.test.ts
- packages/config/src/memory/memory.config.ts
- packages/lambda-tiler/src/tile.set.cache.ts
- packages/server/src/cli.ts
- yarn.lock
- feat(config-cli): import configuration cli from linz/basemaps-config
- fix: include bin/
- feat: load screenshot config from file
- feat: add name to log lines
> feat(config): add configuration parser and bundler

- packages/lambda-tiler/package.json
- packages/lambda-tiler/scripts/create.deployment.package.mjs
- packages/tiler-sharp/package.json
- yarn.lock
Fixes "Error: webp: bad image dimensions"
> fix(tiler): down grade sharp to 0.29.2 as we are scaling webp past 16k

- packages/config/src/config/imagery.ts
- packages/config/src/json/json.config.ts
- packages/config/src/json/parse.tile.set.ts
- feat(config): add a category
- feat: wip
> feat(config): add category and title to imagery

- .github/workflows/push.yml
- ci: build containers on every push
- fix: missing file
- refactor: standardise names
- ci: build containers on pull request
- ci: pack landing for the cli container
> ci: pack landing for cli container

- packages/landing/src/components/map.tsx
> fix(landing): remove full screen button in debug mode as it obsures text BM-635

- packages/cli/package.json
- packages/cli/src/cog/__tests__/cog.stac.job.test.ts
- packages/lambda-tiler/src/__tests__/wmts.capability.test.ts
- packages/lambda-tiler/src/wmts.capability.ts
- packages/landing/package.json
- packages/shared/package.json
- packages/shared/src/proj/__tests__/projection.test.ts
- packages/shared/src/proj/__tests__/projection.tile.matrix.set.test.ts
- yarn.lock
> feat: upgrade proj to 2.8.0 as it has improved transverse mercator projection logic BM-631

- packages/lambda-tiler/src/index.ts
Only insert the access control allow origin if the orign header exists
> fix(lambda-tiler): CORS is handled by the function url.

- packages/landing/src/components/debug.tsx
- packages/landing/src/config.layer.ts
- packages/landing/src/debug.map.ts
> feat(landing): Disable the debug.cog checkbox when loading config outside basemaps.

- packages/cli/README.md
- packages/cli/output.json
- packages/cli/src/cli/cogify/action.make.cog.ts
- packages/cli/src/cli/cogify/cutline.ts
- packages/cli/src/cli/index.ts
Here are the output job.json file I generated from testing. 
`["s3://basemaps-cog-test/2193/tauranga-city_urban_2022_0.1m_RGB/01GCWX0SF0D5V65V2A0RZ6VNMC/job.json","s3://basemaps-cog-test/3857/tauranga-city_urban_2022_0.1m_RGB/01GCWX194XVS2VJF5HD5QQNRF9/job.json"]`
> feat(cli): New cli to make cog and create job.json for it.

- packages/landing/src/components/debug.tsx
- packages/landing/src/config.layer.ts
- feat(landing): copy location to source tiff when layer is clicked
- feat: download the same source.json that is used in the map
> feat(landing): improve the geojson download when clicking the "source" button

- packages/landing/src/components/debug.tsx
> feat(landing): add link to WMTS on debug page

- packages/landing/src/components/debug.tsx
- packages/landing/static/index.css
> feat(landing): show a toast message when things are copied

- package.json
- packages/landing/package.json
- packages/landing/preact-shim.js
- packages/landing/src/components/copyable.tsx
- packages/landing/src/components/debug.tsx
- packages/landing/src/components/layer.switcher.dropdown.tsx
- packages/landing/src/components/layout.footer.tsx
- packages/landing/src/components/layout.header.tsx
- packages/landing/src/components/link.tsx
- packages/landing/src/components/map.switcher.tsx
- packages/landing/src/components/map.tsx
- packages/landing/src/debug.map.ts
- packages/landing/src/index.tsx
- packages/landing/tsconfig.json
- scripts/bundle.js
- yarn.lock
Massive lui upgrade 7 major versions! Also moves to react v18
> feat: searchable layer dropdown

- package.json
- packages/bathymetry/src/bathy.maker.ts
- packages/cli/src/cog/__tests__/cog.test.ts
- packages/config/src/dynamo/dynamo.config.ts
- packages/config/src/memory/memory.config.ts
- packages/lambda-analytics/package.json
- packages/lambda-tiler/package.json
- packages/server/package.json
- yarn.lock
- build: upgrade linzjs/style
- build: upgrade types/node too
- build: more typescript fixes
> build: typescript 4.9.x

- packages/cli/src/cli/config/action.import.ts
NZTM200Quad -> NZTM200**0**Quad for generated PR links
> fix(cli):  NZTM2000Quad PR link

- packages/lambda-tiler/src/routes/__tests__/fonts.test.ts
- packages/lambda-tiler/src/routes/fonts.ts
This reverts commit 5d8e0bea0ab0c29c2aa5264c9011a7eb6f51a946.
> Revert "feat(tiler): Support fonts array to fallback to next font if not fond. (#2633)

- packages/cli/Dockerfile
- packages/cli/src/cli/cogify/action.cog.ts
- packages/cli/src/cli/cogify/action.make.cog.ts
- packages/cli/src/cli/cogify/batch.job.ts
- packages/cli/src/cog/constants.ts
- packages/cli/src/cog/cutline.ts
- packages/cli/src/gdal/gdal.docker.ts
Changes
- Support concurrency in cog creation cli.
- Make the chunkJobUnit = concurrency*maxChunkUnit to chunk the more jobs with multi concurrency.
- Fix create-cog to support local source files.
> feat(cli): Add Concurrency for the make cog cli.

- packages/landing/src/components/layout.footer.tsx
following the https://www.digital.govt.nz/standards-and-guidance/nz-government-web-standards/web-usability-standard-1-3/#copyright standard
> feat(landing): add copyright link

- packages/attribution/src/attribution.ts
- packages/landing/src/attribution.ts
- packages/landing/src/components/daterange.tsx
- packages/landing/src/components/debug.tsx
- packages/landing/src/components/layout.header.tsx
- packages/landing/src/components/map.tsx
- packages/landing/src/config.map.ts
- packages/landing/src/index.tsx
- packages/landing/src/tile.matrix.ts
- packages/landing/src/url.ts
- packages/landing/static/index.css
Rough proof of concept to add a date range slider UI to the Basemaps landing page.
> feat: add proof of concept date range slider

- packages/bathymetry/src/stac.ts
- packages/cli/src/cli/server/action.serve.ts
- packages/cli/src/cog/cog.stac.job.ts
- packages/config/src/json/tiff.config.ts
- packages/lambda-tiler/src/cli/render.tile.ts
- packages/lambda-tiler/src/routes/attribution.ts
- packages/server/README.md
- packages/server/src/cli.ts
- packages/server/src/config.ts
- packages/server/src/server.ts
- packages/shared/src/util.ts
- packages/tiler-sharp/src/__tests__/tile.creation.test.ts
- packages/tiler-sharp/src/index.ts
- packages/tiler/src/__tests__/tiler.test.ts
- packages/tiler/src/raster.ts
- packages/tiler/src/tiler.ts
This config option was documented but didn't exist in the code
> fix(server): make --no-config actually load the configuration from tiffs

- packages/config/src/json/tiff.config.ts
GSD are floating points that sometimes vary between tiffs
> fix(server): allow a small variance between GSD

- packages/cli/src/cli/cogify/action.make.cog.pr.ts
- packages/cli/src/cli/github/make.cog.pr.ts
Features:
- Allow disabled flag for the cli
- Add Event category
Bug fixes:
- Couldn't find the last rural layer for adding into config, now we should always add the rural/urban at the bottom of the last one.
- Reprocessed Imagery should be updated existing layer instead of add new one.
> feat(cli): Add disabled flag for the create pr cli, and bug fixes.

- packages/_infra/package.json
- yarn.lock
`cdk deploy *` was only deploying the first stack.
> build: upgrade to cdk 2.81 to fix deployment issue

- packages/cogify/src/cogify/cli/cli.config.ts
- packages/config/src/json/tiff.config.ts
*What does this change aim to achieve?*
Tweaks the `cogify config` command to write out just the URL to a file for consumption by Argo, rather than writing out a JSON array which contains one item.
Slight refactor to the `initImageryFromTiffUrl` function (renamed from `imageryFromTiffUrl`), to improve ease of calling it directly. This involves changing the signature to allow passing a `ConfigProviderMemory` instance into the function, which was previously handled in `initConfigFromUrls` (which calls `initImageryFromTiffUrl`).
*Why is this change being made? What implications or other considerations are there?*
This change will allow the Argo workflow to display just the URL without the surrounding `["..."]` JSON array characters. This will make it easier for users to navigate to the URL …
> feat(cogify): output single URL in cogify config command BM-822

- packages/cli/src/cli/github/github.ts
- packages/cli/src/cli/github/make.cog.pr.ts
*Fix the issue of commit all won't be able to pick new created files. So we need to git add them first before commit.*
*Bug fix*
> fix(cli): new created file need to add to git before commit.

- packages/_infra/src/serve/lambda.tiler.ts
- packages/lambda-tiler/bundle.sh
From initial testing ARM has shown to be quite quick and cheap for rendering tiles, this is designed as a testing change that could
Switch the main lambda tiler into ARM so we can see what impacts it may have
> feat(lambda-tiler): try arm based lambdas

- packages/config/src/json/json.config.ts
After separate individual config files the config bundle process gets very slow when loading and processing each file synchronously. 
This will improve the config bundle speed in the basemaps-config ci process.
Test improvements 3 minutes to 20 seconds on my local machine.
> feat(cli): Update config bundle to running asynchronously.

- packages/lambda-tiler/src/routes/preview.ts
Adds a checkboard background to all preview images that have transparent backgrounds
Currently the preview generator uses a slightly pink background for all transparency this is not consistent with the landing page.
To be more consistent create a checkerboard background of the same color to the landing page.
The tiles are slightly smaller 30px vs 50px so they align with the 1200px x 630px dimensions of the preview image
> feat(lambda-tiler): use the same checker background that the landing does for previews BM-264

- CHANGELOG.md
- lerna.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/lambda-analytics/CHANGELOG.md
- packages/lambda-analytics/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/shared/CHANGELOG.md
- packages/shared/package.json
- packages/smoke/CHANGELOG.md
- packages/smoke/package.json
- packages/tiler-sharp/CHANGELOG.md
- packages/tiler-sharp/package.json
- #2959 
- #2955 
- #2954 
- #2953 
- #2952 
- #2947 
- #2939 
- #2938 
- #2937
> release: v6.45.0

- .github/pull_request_template.md
I find it easier to understand what type of comments to put in each section when I see Motivation/Modification.
Change the pull request template.
> build: switch to motivation/modification wording for template

- .github/pull_request_template.md
Its nice to have everything formatted
Apply the prettier formatter to template markdown files.
> refactor: apply formatter

- .github/workflows/pull-request.yml
Pull request titles are used for change log generation they need to be in conventional format
Adds a github action to validate all pull request titles are conventional.
> ci: lint pull request titles

- .github/workflows/push.yml
- docs/index.css
- mkdocs.yml
Improves the mkdocs setup to make it easier for future expansion
- Link back to basemaps.linz.govt.nz
- Add CC-BY license
- Add LINZ Logo
- Add Google analytics
- Add Light/Dark Mode
- Change header to be LINZ colored
> docs: improve doc build process

- docs/README.md
- docs/configuration.md
- docs/deployment.md
Fixing broken links, images formatting etc..
Fixes broken links, images and formatting 
> docs: minor link and formatting fixes 

- packages/config/src/json/json.config.ts
- packages/config/src/json/tiff.config.ts
bundling configuration fromt he command line should be able to be done from paths that contain imagery not in the Z-X-Y.tiff format, eg NZTM Tiles `CA12_5000_1008.tiff` 
Attempt to load tiffs as Z-X-Y if that fails then fall back a slower process loading the extends from the tiff's themselves.
> fix(config): allow config to be loaded where tiffs are not in Z-X-Y.tiff format

- packages/config/src/json/json.config.ts
The loading queue is deadlocking loading config files wait for imagery which waits for loading config files
loading config files are just all done concurrently and only the imagery loading is done in a queue
> fix(config): prevent deadlocking of loading queue

- package-lock.json
- packages/landing/package.json
- packages/landing/src/attribution.ts
- packages/landing/src/components/map.tsx
Keep current with latest maplibre improvements
Upgrades maplibre to latest and adds a scale to the bottom right corner.
> feat(landing): upgrade maplibre and include scale

- .github/workflows/push.yml
- package-lock.json
- packages/landing/package.json
- packages/landing/serve.mjs
- packages/landing/src/components/layer.switcher.dropdown.tsx
- packages/landing/src/components/layout.footer.tsx
- packages/landing/src/components/layout.header.tsx
- packages/landing/static/index.css
LUI is a linz branding library with all the logos we need, some logos changed a while back and we never updated.
upgrades lui to the latest which modifies a few styles like the header and footer height and logos.
> feat(landing): upgrade lui

- package-lock.json
- packages/_infra/package.json
- packages/_infra/src/serve/lambda.tiler.ts
- packages/cli/Dockerfile
- packages/server/Dockerfile
node 20 is the current lts and supported by aws lambda
upgrades to node 20.
> feat: node 20

- packages/cli/src/cli/util.ts
The error object are updated in the cdk v3. We need to check not found from the new error type.
Update the error catch in the hashObject
> fix(cli): fix the error type for cdk v3 in the s3 hash object

- package-lock.json
- package.json
- packages/shared/src/__tests__/api.test.ts
- packages/shared/src/dynamo/__tests__/config.dynamo.test.ts
- packages/shared/src/dynamo/__tests__/config.imagery.test.ts
Lerna is way out of date, upgrade to 8.x
upgrades lerna to 8.x and fixes a few broken unit tests.
> build: lerna 8

- package-lock.json
- packages/shared/package.json
- packages/tiler/package.json
> fix(tiler): do not read past the end of a tiff BM-948

- packages/config-loader/src/json/tiff.config.ts
Some tiffs provide their resolution or GSD in measurements other than meters, we use meters for all the math we do.
Gives a very rough approximation of meters when given a image in degrees.
> feat(config-loader): support loading tiffs not in meters

- packages/config-loader/src/json/__tests__/tiff.config.test.ts
- packages/lambda-analytics/src/__tests__/file.process.test.ts
- packages/lambda-analytics/src/__tests__/index.test.ts
- packages/lambda-analytics/src/index.ts
- packages/lambda-tiler/src/routes/__tests__/fonts.test.ts
- packages/lambda-tiler/src/routes/__tests__/preview.index.test.ts
- packages/lambda-tiler/src/routes/__tests__/sprites.test.ts
- packages/lambda-tiler/src/routes/__tests__/tile.json.test.ts
> fix: some tests commented out

- packages/smoke/src/wmts.test.ts
To be more confident the system has deployed well we need to validate that endpoints after a deployment is made.
Adds basic smoke tests for WMTS serving
> feat(smoke): basic wmts validation

- package-lock.json
- packages/landing/package.json
> build: upgrade maplibre to v4

- packages/lambda-tiler/src/index.ts
We are logging too much information by default overloading our logging system, we need to reduce the logs, we can randomly sample requests
set logger to info by default and in 1% or 5% of requests we should either do trace or debug logging
> feat(lambda-tiler): randomly sample requests with trace logging

- packages/cli/src/cli/config/action.import.ts
- packages/cogify/src/cogify/cli/cli.config.ts
- packages/server/src/route.layers.ts
- packages/shared/src/imagery.url.ts
Cogify is not generating working preview links for DEM/DSMs
Create preview links that output color-ramps for cogify configs
> feat(cogify): support config creation from tilesets with outputs

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/smoke/CHANGELOG.md
- packages/smoke/package.json
> release: v7.1.1

- packages/cli/src/cli/config/action.import.ts
- packages/cli/src/cli/config/config.diff.ts
Check and Compare the `collections.json` between old and new vector data, and output the feature changes for the Pull request comments.
Generate addition feature changes from `import` cli which can be added into config pull requests comments.
> feat(cli): Output the feature changes for the vector update

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/smoke/CHANGELOG.md
- packages/smoke/package.json
> release: v7.2.0

- packages/cli/src/cli/config/config.diff.ts
Just found we missing a skip for no version updates.
Add a skip if no version changes
> fix(cli): Should skip if no lds version for the feature changes.

- .github/workflows/smoke-test.yml
Add a new workflow that runs smoke tests for the pull requests.
A new workflow called `smoke` which run a local server and run the smoke tests on the server.
> build: Add smoke test for the pull request BM-1012 BM-1010

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
- packages/config-loader/CHANGELOG.md
- packages/config-loader/package.json
- packages/lambda-analytics/CHANGELOG.md
- packages/lambda-analytics/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/shared/CHANGELOG.md
- packages/shared/package.json
- packages/smoke/CHANGELOG.md
- packages/smoke/package.json
> release: v7.3.0

- .github/pull_request_template.md
removes the checklist option as it was not being used,
updates to the new template based off [argoproj/workflows](https://github.com/argoproj/argo-workflows)
> build: switch to new pr template based off argoworkflows

- package-lock.json
- packages/landing/package.json
There are a number of UX bug fixes in maplibre that would be good to be included
Upgrades maplibre to v4.4.1
Will validate that the screenshots render correctly
> build: upgrade maplibre to v4.4.1

- packages/_infra/src/edge/index.ts
Add the terrain key into the cloud front cache
Key is missing it the cloud front cache.
> feat(infra): Add terrain cache key into cloud-front.

- packages/cogify/package.json
`dist/` contains the bundled cli so you do not need all the deps installed it was missing from the package and the container
ensure dist is published.
> fix(cogify): publish dist folder

- package-lock.json
- package.json
- packages/lambda-tiler/src/routes/preview.ts
- packages/lambda-tiler/src/routes/tile.xyz.raster.ts
- packages/shared/package.json
Typescript v5.5.x was failing to build `@basemaps/tiler` causing the entire build to fail
remove a unused package.json import which was causing it to fail
> fix: compiler issue with typescript v5.5.x

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
- packages/config-loader/CHANGELOG.md
- packages/config-loader/package.json
- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/lambda-analytics/CHANGELOG.md
- packages/lambda-analytics/package.json
- packages/lambda-tiler/CHANGELOG.md
- packages/lambda-tiler/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/shared/CHANGELOG.md
- packages/shared/package.json
- packages/tiler-sharp/CHANGELOG.md
- packages/tiler-sharp/package.json
> release: v7.6.0

- package-lock.json
- packages/_infra/package.json
- packages/_infra/src/index.ts
the newer version of the tagging library renames some tags.
upgrade linz's tagging library to latest  to keep upto date with the latest tags
> build: upgrade tags to v1.6

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/_infra/CHANGELOG.md
- packages/_infra/package.json
- packages/landing/CHANGELOG.md
- packages/landing/package.json
> release: v7.8.0

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/bathymetry/CHANGELOG.md
- packages/bathymetry/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cogify/CHANGELOG.md
- packages/cogify/package.json
> release: v7.11.1

- packages/cli-config/src/cli/action.import.ts
We will need to provide preview links and report for NZTM vector map if exists.
Update the code to include NZTM previews from the tileset layers.
> feat(cli-config): Support vector preview links and reports for NZTM. BM-1253

- .github/workflows/push.yml
- .github/workflows/screenshot.yml
LINZ security team blocks all the third party github actions on 7th July
> build: Remove third party github actions.

- .github/workflows/push.yml
Stop using GITHUB_TOKEN for release-please
> fix: stop using GITHUB_TOKEN for release-please

- .github/workflows/push.yml
add required permissions for release please
https://github.com/linz/basemaps/actions/runs/17255349314/job/48965937776
> fix: add required permissions for release please github action

- .github/workflows/push.yml
prod workflows not kicked off as looking for release-please release
revert to old method from https://github.com/linz/basemaps/commit/ba3830590c8c3163f02d0f67760d1d1595c51cef
> fix: remove release-please from prod deploy

- .github/workflows/containers.yml
- .github/workflows/push.yml
- packages/tiler-sharp/src/pipeline/decompressor.zstd.ts
- packages/tiler/package.json
Master is failing to deploy into dev due to a miss import of some packages
add config as a dependency for the tiler
adjust other imports to remove references to shared.
> fix: correct import paths

- .github/workflows/push.yml
broke publishing to npm, https://github.com/linz/basemaps/actions/runs/17903251645/job/50899817388
> fix: publish to npm after release-please

- .github/workflows/push.yml
add smoke test fix to prod: https://github.com/linz/basemaps/pull/3514
> fix: prod smoke test with correct glob

- .github/workflows/release-please.yml
publish release not run due to: https://github.com/googleapis/release-please-action/issues/912
> fix: release-please release_created workaround
