lefthook.yml
package.json
yarn.lock

Enforce commit language with a commit hook
`git commit -m 'foo'` will now fail

build: adding commitlint git hook

---

tsconfig.base.json

Fixes a bug where you could not ctrl + click class names and end up a the class source in vscode.

build: allow jumping to source in different packages

---

.github/workflows/master.yml

Master deployment pipeline is broken, because it is missing access keys to do a `deploy:synth`
Master build pipeline should now work

build: since we are looking up a vpc deploy:synth needs access keys

---

packages/_infra/package.json

aws cdk cannot ask for deploy approval as there is no tty
Master branch should be able to deploy

build: aws cdk cannot ask for deploy approval as there is no tty

---

packages/shared/src/lambda.ts

Pino only serializes errors if they are labeled "err"

fix: log errors into err so pino will serialize them

---

packages/shared/src/metrics.ts
packages/tiler/src/__test__/tile.benchmark.test.ts

Start tracking basic timings for how long it takes to open, parse and render a tile

feat: adding basic benchmark to track tile render performance

---

packages/lambda-api-tracker/src/index.ts
packages/lambda-api-tracker/src/validate.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/index.ts
packages/shared/src/__test__/lambda.test.ts
packages/shared/src/__test__/log.spy.ts
packages/shared/src/index.ts
packages/shared/src/lambda.ts
packages/shared/src/log.ts
packages/shared/src/metrics.ts
packages/tiler/src/__test__/tile.benchmark.test.ts
packages/tiler/src/__test__/tile.creation.test.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

`JSON.stringify(1n)` throws a exception
Restructure logging so that the stream can be overriden rather than disabled.
This allows the logger to continue working so it can be tested
Modifies the logger so that during tests we no longer disable it.

fix: bigint logging does not work

---

packages/lambda-xyz/src/index.ts
packages/lambda-xyz/src/png.ts

Serve up a 1x1 pixel png, instead of 404.
This allows better caching of the png.
...

feat: serve 1x1 pixel png instead of 404

---

packages/shared/src/lambda.response.alb.ts
packages/shared/src/lambda.response.cf.ts

All headers are passed into these functions as lower case, need to lowercase them before using them.
...

fix: headers need to be lower cased

---

packages/lambda-xyz/src/cli/index.ts
packages/lambda-xyz/src/tiff.ts

Paths were getting two "/"'s causing key not found errors eg "foo//bar" vs "foo/bar"

fix: fixing path loading for s3 cogs

---

packages/shared/src/__test__/quad.key.test.ts
packages/shared/src/quad.key.ts

Quadkey intersection was using the wrong root tile.
Root tile intersections of "" works without extra logic.

fix: 0 is not the root tile "" is

---

packages/_infra/src/edge/lambda.edge.api.key.ts

Lambda deployment versions are only required when using lambda@edge, we do not currently have this hooked up and is causing the build to sometimes fail.

build: remove lambda version

---

packages/_infra/src/cogify/index.ts

Up the CPU limits so more than one c5 instance will be spawned.
Also allow 9xlarge, which starts provides 10G networking speeds.

fix: allow more than one c5 instance to process COGs

---

packages/lambda-xyz/src/tiff.ts

Fixes a off by one error in the generation of bathy, this should remove the empty line on the anti meridian

fix: new bathy imagery which improves the render quality

---

packages/cog/src/cli/actions/action.batch.ts
packages/cog/src/cli/actions/action.cog.ts
packages/cog/src/cli/actions/action.job.ts
packages/cog/src/cog.ts

Add the base folder name as the name of the imagery set, this is used in names and job definitions.

refactor: improve the logging of imagery set names while processing COGs

---

packages/lambda-xyz/src/index.ts

Tiffs need to be initialized before trying to access them.

fix: wait for the tiffs to load before trying to serve them

---

packages/_infra/src/serve/lambda.xyz.ts
packages/lambda-shared/src/const.ts
packages/lambda-xyz/src/index.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

Logging out the exact image and tiles used for the composition allows easier debugging of image issues

refactor: when runnning in debug mode increase the verbosity of logging

---

package.json
packages/_infra/package.json
yarn.lock

AWS-CDK cannot be bumped by dependabot as it cannot upgrade everything at the same time.
So manually bumping the dep.

build(deps): aws-cdk 1.28

---

packages/lambda-xyz/src/__test__/index.test.ts
packages/lambda-xyz/src/index.ts

Lambda functions use `index.js > handler()` as the invocation point.
The function must be exported.

fix: lambda functions need a "handler" to be exported to run

---

packages/lambda-xyz/src/cli/serve.ts
packages/landing/static/index.html

1. landing page tiles url
2. `cli/serve.ts` to forward correct url

fix: update landing page and cli/serve to include aerial/3857

---

packages/_infra/src/config.ts

Use the newly created `tiles.dev.basemaps.linz.govt.nz`

chore: rename dev url to dev.basemaps.linz.govt.nz

---

packages/lambda-shared/src/__test__/api.path.test.ts
packages/lambda-shared/src/api.path.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/routes/tile.ts

Allow requests for jpeg and webp image formats in addition to PNG
Check that server responds with image of requested type

feat(tile): serve png, webp and jpeg

---

packages/lambda-api-tracker/src/__test__/xyz.request.test.ts
packages/lambda-api-tracker/src/index.ts
packages/lambda-shared/src/header.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/routes/tile.ts

Set `WMTSCapabilities.xml` response header `cache-control: max-age=0` for api-tracker and tile requests 
...
Using a different api key should result in different `ResouceURL` elements.

feat(wmts): set cache-control max-age=0 for WMTSCapabilities.xml

---

LICENSE
package.json
packages/_infra/package.json
packages/cog/package.json
packages/geo/package.json
packages/lambda-api-tracker/package.json
packages/lambda-shared/package.json
packages/lambda-xyz/package.json
packages/landing/package.json
packages/metrics/package.json
packages/tiler-sharp/package.json
packages/tiler/package.json

LINZ has suggested using MIT as the default licensing for new projects.

docs: switch to MIT license

---

packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/routes/tile.ts

Check etag against file contents and respond with 304 if not modified

fix(wmts): respond with 304 if not modified

---

packages/landing/package.json

node scripts can not be directly exectued
either need to `chmod +x ` and `#!/usr/bin/env node`
or to just run the node cli

build: ensure deploy script can be run

---

.github/workflows/push.yml
packages/cog/package.json
packages/lambda-api-tracker/package.json
packages/lambda-shared/package.json
packages/lambda-xyz/package.json
packages/tiler-sharp/package.json
packages/tiler/package.json
scripts/detect.unlinked.dep.js

Verify that there are no unlinked deps inside the monorepo.

build: should fail build if unlinked dependencies are used

---

packages/cog/src/cli/cogify/__test__/action.batch.test.ts
packages/cog/src/cli/cogify/action.batch.ts

When `cogify batch` is started store job imagery information in the metadata db

feat: store metadata imagery on cog creation

---

packages/lambda-xyz/src/__test__/wmts.capability.test.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/wmts.capability.ts
packages/tiler/src/raster.ts

1. Change image format order for ArcGIS Pro
2. Rename TileMatrixSet to GoogleMapsCompatible

fix(wmts): change image format order for ArcGIS Pro

---

.github/workflows/push.yml

Configure the AWS environment once rather than per command

build: configure aws access keys once

---

packages/cog/src/cli/basemaps/action.imagery.import.ts
packages/cog/src/cli/basemaps/index.ts
packages/cog/src/cli/cogify/__test__/action.batch.test.ts
packages/cog/src/cli/cogify/action.batch.ts
packages/lambda-shared/src/aws/tile.metadata.table.ts

Import imagery into the database from existing s3 buckets.
`./basemaps import -j s3://.../3857/wellington_urban_2017_0.10m/01DZMDXXEA1DEQDRY2F56PQ8EE/job.json`

feat: allow importing existing imagery into database

---

packages/_infra/package.json
packages/cog/src/cli/basemaps/action.imagery.import.ts
yarn.lock

Upgrades aws-cdk to 1.32.2
Removes excess await

Build/aws cdk 1.32.2

---

packages/cog/src/cog/__test__/cog.cutline.test.ts
packages/cog/src/cog/cog.cutline.ts

s3 paths are different for gdal /vsis3/ rather than s3://

fix(cutline): ignore path when updating vrt

---

packages/cog/package.json
packages/cog/src/cog/builder.ts
packages/cog/src/cog/cog.ts
packages/cog/src/proj/__test__/index.test.ts
packages/cog/src/proj/index.ts
packages/geo/src/__tests__/projection.test.ts
packages/geo/src/__tests__/quad.key.test.ts
packages/geo/src/projection.ts
packages/geo/src/quad.key.ts
yarn.lock

`global-mercator` npm is no longer needed as `@mapbox/tilebelt` has needed functions

refactor(cog): remove global-mercator npm

---

packages/cog/src/cog/__test__/cog.test.ts
packages/cog/src/gdal/__test__/gdal.test.ts
packages/cog/src/gdal/gdal.config.ts
packages/cog/src/gdal/gdal.ts

Fixes: #  
Problem occurring with white edges and random pixel artefacts appearing on dataset boundaries
Changes the default resampling method from cubic to bilinear to prevent generation of edge artefacts
Addresses issue https://app.zenhub.com/workspaces/basemaps-5d3f61dd0406610875ab93c6/issues/linz/basemaps-team/121

fix: default resampling cubic to bilinear

---

.github/workflows/push.yml

We are unable to use configure-aws-actions twice in the same job, so only login right before the deployment

build: fix deployment to prod

---

packages/landing/static/index.html

Using a query parameter `?i=:tileSetName` eg `?i=aerial`

feat(landing): support different imagery sets other than aerial

---

packages/lambda-shared/src/__test__/api.path.test.ts
packages/lambda-shared/src/api.path.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/routes/tile.ts

This allows any tile set in the database to be served, rather than 404ing on anything that is not "aerial"
TODO we should really lookup the WMTS stuff from the database too.

fix(serve): allow any tile set name to be used

---

packages/tiler/package.json
packages/tiler/src/__test__/tiler.test.ts
packages/tiler/src/tiler.ts

Non square COGs were being shifted up from their intended position

fix(tiler): position non square COGs correctly

---

packages/cog/src/cli/cogify/action.job.ts
packages/cog/src/cog/__test__/cog.test.ts
packages/cog/src/cog/cog.ts
packages/cog/src/cog/types.ts
packages/cog/src/gdal/gdal.config.ts
packages/cog/src/gdal/gdal.ts

This also bumps the quality number from 75 -> 90
This seems to add about 25% more to file size from my small test cases.
https://gdal.org/drivers/raster/cog.html

feat(cli): support webp quality setting

---

packages/cog/src/cli/cogify/action.job.ts
packages/cog/src/cog/builder.ts
packages/cog/src/cog/cog.vrt.ts
packages/cog/src/cog/types.ts

Source projection can be used as a fallback when the source imagery does specify its projection
Allows processing of imagery sets that are missing a projection.  Add argument `--src-proj 2193` when running `cogify job`

feat(cog): Allow supply of source projection

---

packages/_infra/src/cogify/index.ts
packages/cli/src/cli/base.cli.ts

- inside of batch use the environment variables
- otherwise look it up from the package.json
- fall back to git-rev-sync

fix(cli): git hash cannot be fetched inside the docker cli

---

packages/cli/src/cli/basemaps/__test__/test.update.test.ts
packages/cli/src/cli/basemaps/action.tileset.history.ts
packages/cli/src/cli/basemaps/tileset.util.ts
packages/lambda-shared/src/aws/__test__/tile.metadata.table.test.ts
packages/lambda-shared/src/aws/__test__/tile.metadata.tileset.test.ts
packages/lambda-shared/src/aws/tile.metadata.imagery.ts
packages/lambda-shared/src/aws/tile.metadata.tileset.ts
packages/lambda-shared/src/aws/tile.metadata.ts
packages/lambda-xyz/src/cli/validate.ts
packages/lambda-xyz/src/tile.set.ts

Changed to compare year and resolution if priority the same.
Resolves linz/basemaps-team#159

fix(lambda-shared): fix order equal priority images are sorted

---

packages/cli/src/cog/__test__/cog.test.ts
packages/cli/src/gdal/gdal.ts

SPARSE_OK is new in GDAL 3.2
see https://github.com/OSGeo/gdal/pull/2551

feat(cli): output sparse cogs by default

---

packages/cli/src/cog/builder.ts

The refactor of removing Google Mercator code from `geo` broke the logic in `getTiffResolution`

fix(cli): fix regression in calculating image zoom resolution

---

packages/lambda-xyz/src/cli/tile.set.local.ts

Can now serve a individual COG rather than a folder
./test-serve.js foo.tiff

feat(cli): allow rendering of a single cog

---

packages/geo/src/__tests__/tms.quad.key.test.ts
packages/geo/src/index.ts
packages/geo/src/tms.quad.key.ts

feat(geo): generate a quadkey mapper for tile sets that are not quite square

---

packages/lambda-xyz/src/cli/tile.set.local.ts

`node -r source-map-support/register ./build/cli/serve.js /path-to/2193-serve`
dir format:
```
2193-serve/100_sentinel/03202112.tiff
2193-serve/100_sentinel/03202131.tiff
2193-serve/100_sentinel/03203.tiff
...
2193-serve/500_auckland/032211032.tiff
...
2193-serve/500_wellington/032233223.tiff
...
```

feat(lambda-xyz): Serve local images with set priority

---

.github/workflows/push.yml
packages/landing/deploy.js

feat(landing): track with google analytics if $GOOGLE_ANALYTICS is set

---

packages/cli/src/cli/cogify/action.cog.ts
packages/cli/src/cog/__test__/cutline.test.ts
packages/cli/src/cog/__test__/quadkey.vrt.test.ts
packages/cli/src/cog/cutline.ts
packages/cli/src/cog/job.ts
packages/cli/src/cog/quadkey.vrt.ts

If a COG is on the border of the source imagery then the cutline blending can interfere if it is
truncated to the same boundary line. We need to add padding that is at least as wide as the blend
value to avoid alpha artefacts of these edges. The value used will include 100 extra pixels to allow
adjacent imagery to be included in edge calculation data.

fix(cli): Take in to accound blend size when creating edge COGs

---

packages/cli/src/cog/__test__/quadkey.vrt.test.ts
packages/cli/src/cog/quadkey.vrt.ts

Fix regression missing argument '-allow_projection_difference'

fix(cli):  quadkey.vrt missing argument 

---

packages/landing/src/ui.ts
packages/landing/static/index.css
packages/landing/static/index.html

feat(landing): copy link button

---

packages/_infra/src/version.ts
packages/cli/src/cli/cogify/__test__/semver.test.ts

using tag=HEAD breaks semver comparision

fix(cli): show number of commits since last tag

---

packages/cli/src/cli/base.cli.ts
packages/cli/src/cli/cogify/action.cog.ts
packages/cli/src/cog/builder.ts
packages/shared/src/index.ts
packages/shared/src/logger.fatal.error.ts

`cogify cog` was detecting `job.json` version mismatch but was exiting the process with code 0 (success); now exits with code 1.

fix(cli): ensure fatal errors set process exit code to 1

---

packages/cli/src/cog/__test__/cog.vrt.test.ts
packages/cli/src/cog/cutline.ts

This was causing three COGs to use a cutline that has self intersecting edges.
This is an interim fix. A more comprehensive change is in the works.

fix(cli): don't reduce cutline when building a cog

---

.github/workflows/push.yml
audit-resolve.json
package.json
yarn.lock

When audit issues are not fixed in a timely manner allow change to ignore issues for a time period.

chore(ci): use npm-audit-resolver

---

packages/cli/package.json
packages/cli/src/cli/cogify/action.cog.ts
packages/cli/src/cog/__test__/builder.test.ts
packages/cli/src/cog/__test__/clipped.multipolygon.test.ts
packages/cli/src/cog/__test__/cog.vrt.test.ts
packages/cli/src/cog/__test__/cutline.test.ts
packages/cli/src/cog/__test__/source.tiff.testhelper.ts
packages/cli/src/cog/builder.ts
packages/cli/src/cog/clipped.multipolygon.ts
packages/cli/src/cog/cog.vrt.ts
packages/cli/src/cog/cutline.ts
packages/cli/src/cog/job.ts
packages/cli/src/cog/types.ts
packages/cli/src/lineclip.d.ts
packages/geo/src/__tests__/bounds.test.ts
packages/geo/src/bounds.ts
packages/geo/src/geo.json.ts
packages/shared/src/tms/__test__/projection.tile.matrix.set.test.ts
packages/shared/src/tms/projection.tile.matrix.set.ts
yarn.lock

Use clipline to reduce polygon when we don't care about degenerate edges. When we do care call
intersection to remove the degenerate edges.
Store image bounds not polygons in SourceMetadata and also store in CogJob. This reduces
floating-point errors when combining source imagery bounds into composite polygons.
Note:
The Martinez polygon-clipping libraries can suffer from errors when lines align. Other intersection
libraries are intractable for the size of coastline polygons.  A solution is to call intersection
after first calling clipline.

fix(cli): mitigate polygon intersection errors

---

packages/cli/src/cog/__test__/clipped.multipolygon.test.ts
packages/cli/src/cog/clipped.multipolygon.ts
packages/cli/src/cog/cog.vrt.ts
packages/cli/src/cog/cutline.ts

Some unnecessary cogs were being created because intersecting bounds but not intersecting polygons
was resulting in degenerate-edges-only-polygons which were not being interpreted as empty. By always
removing the degenerate edges we loose some performance but get the correct results.
We could restore most of the performance with some extra logic but for simplicity's sake it is not worth it.

fix(cli): make clipMultipolygon always remove degenerate edges

---

packages/landing/src/map.ts
packages/landing/src/nztm2000.ts

Also set default zoom level to 3 for NZTM

feat(landing): limit nztm to its extent

---

packages/landing/static/index.html

Fix "About [B]asemaps", "Get [s]tarted" and "Git[H]ub"

fix(landing): Fix typos in side menu

---

packages/landing/src/map.ts
packages/landing/static/index.html

This means that arrow keys will now be used for map control, 
~hope noone needs arrow keys for input boxes?~ arrow keys in Input boxes work fine!

fix(landing): dont require clicking on the map for keyboard events

---

packages/geo/src/__tests__/bounds.test.ts
packages/geo/src/bounds.ts
packages/tiler/src/tiler.ts

Overview tiles that do not align with the requested zoom level often leave multiple pixel gaps
between COGs. This fix reduces that size of that gap.

fix(tiler): try to minimize the error when rounding boundaries

---

packages/cli/src/cog/job.ts

Was adding cutline to job but not writing it to output dir causing an error when trying to build a
cog.

fix(cli): Don't add cutline properties to CogJob when not used

---

packages/cli/src/cli/cogify/action.cog.ts
packages/cli/src/cli/cogify/action.job.ts
packages/cli/src/cog/__test__/cog.test.ts
packages/cli/src/cog/__test__/cutline.test.ts
packages/cli/src/cog/cog.ts
packages/cli/src/cog/cutline.ts
packages/cli/src/cog/job.ts
packages/cli/src/cog/types.ts
packages/cli/src/gdal/gdal.config.ts
packages/geo/src/__tests__/tile.matrix.set.test.ts
packages/geo/src/tile.matrix.set.ts
packages/landing/src/nztm2000.ts

This is for use with creating the gebco COG because the default process can't handle the
anti-meridian and one cog is optimal for the gebco layer.

feat(cli): Allow creation of one cog covering entire extent

---

packages/bathymetry/src/stac.ts

`packageJson.gitHead` is added when the package is published, so if it exists its from a npm install'd `@basemaps/bathymetry`

fix(bathymetry): allow bathy command to be run outside of git repo

---

packages/__tests__/src/rounding.ts
packages/cli/src/cog/cutline.ts
packages/geo/src/wmts/wmts.ts
packages/lambda-xyz/src/__test__/tile.set.cache.test.ts
packages/lambda-xyz/src/__test__/tile.set.test.ts
packages/lambda-xyz/src/__test__/wmts.capability.test.ts
packages/lambda-xyz/src/__test__/xyz.test.ts
packages/lambda-xyz/src/cli/serve.ts
packages/lambda-xyz/src/cli/validate.ts
packages/lambda-xyz/src/routes/tile.ts
packages/lambda-xyz/src/tile.set.cache.ts
packages/lambda-xyz/src/tile.set.ts
packages/lambda-xyz/src/wmts.capability.ts
packages/lambda/src/__test__/api.path.test.ts
packages/shared/src/api.path.ts
packages/shared/src/aws/__test__/tile.metadata.table.test.ts
packages/shared/src/aws/__test__/tile.metadata.tileset.test.ts
packages/shared/src/index.ts
packages/shared/src/proj/__test__/projection.test.ts
packages/shared/src/proj/__test__/projection.tile.matrix.set.test.ts
packages/shared/src/proj/projection.tile.matrix.set.ts
packages/shared/src/proj/projection.ts
packages/shared/src/proj/tile.set.name.ts
packages/tiler/src/raster.ts

When the tile set name is not supplied create a WMTSCapabilities xml file with all supported Layers
including individual layers from composite tileSets.
When the projection is not supplied create a WMTSCapabilities xml file with layers for all supported
target projections.
Allow fetching sub imagery tiles by the parent imagery name plus the child imagery set name. For
example `/v1/tiles/aerial@beta:tasman_rural_2018-19_0-3m/2193/8/405/321.png`
Group projections for same imagery.
Set the `ows:BoundingBox` for each layer to the extent of the layer
Set the `ows:WGS84BoundingBox` also (after the `ows:BoundingBox`). Currently if the bounding box
crosses the anti-merdian just make the boundingbox the world extent. It may be possible to instead
create two bounding boxes on each side of the …

feat(lambda-xyz): Serve WMTSCapabilities for all TileSets

---

packages/lambda/src/lambda.ts

Makes it easier to filter for `@type: "report"` across services

feat(lambda): tag all report logs as "report"

---

scripts/bundle.js

fix `"'${envVar}'"` to be `"${envVar}"`

fix(build): Don't inner quote define strings

---

packages/geo/src/__tests__/bounds.test.ts
packages/geo/src/bounds.ts
packages/tiler/src/tiler.ts

The bias used by `tiler.ts` is 0.2 so that it will round down at < 0.7 and round up at >= 0.3 instead of down at < 0.5
and up at >= 0.5. This leads to tiles favouring covering a pixel larger area than before.

feat(geo): Add an optional bias when rounding bounds

---

packages/cli/src/cli/cogify/action.job.ts
packages/tiler-sharp/src/__test__/tile.creation.test.ts
packages/tiler-sharp/src/index.ts
packages/tiler/src/__test__/tiler.test.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

Use lanczos3 when up sizing. This is a fix to reduce artefacts when rendering the topo-50 nztm
layer.
Allow supplying source order when creating CogJob; needed when ordering is important or a source
directory contains more than one imagery set as in the case of topo-50.

fix(tiler): Use nearest smoothing when down sizing

---

packages/linzjs-s3fs/src/__tests__/file.local.test.ts
packages/linzjs-s3fs/src/composite.error.ts
packages/linzjs-s3fs/src/file.local.ts
packages/linzjs-s3fs/src/file.s3.ts
packages/linzjs-s3fs/src/index.ts

use 403 and 404 for errors across s3 and local instead of fs:EACESS or fs:ENOENT and s3:NotFound

feat(s3fs): expose standard error codes for not found and forbidden

---

packages/cli/src/cli/basemaps/tileset.util.ts

See #1034
Was invalidating, say, `/v1/tiles/topo50/2193/*`; now is `/v1/tiles/topo50/EPSG:2193`

fix(cli): use the same url pattern as WMTS to invalidate cache

---

packages/lambda-xyz/src/__test__/index.test.ts
packages/lambda-xyz/src/routes/api.ts

Cloudfront was caching these requests

fix(lambda-xyz): Stop health and ping response being cached

---

packages/lambda/src/__test__/api.path.test.ts
packages/shared/src/api.path.ts

This path `/v1/tiles/aerial/EPSG:3857/12/4009/2602` was throwing an error

fix(shared): Don't error if tile ext missing

---

.github/dependabot.yml

Dependabot does not do a good job updating these dependencies as they all need to be bumped at the same time.

build: ignore aws-cdk from dependabot

---

packages/cli/src/cli/basemaps/__test__/test.update.test.ts
packages/cli/src/cli/basemaps/action.tileset.history.ts
packages/cli/src/cli/basemaps/action.tileset.info.ts
packages/cli/src/cli/basemaps/action.tileset.update.ts
packages/cli/src/cli/basemaps/tileset.util.ts
packages/cli/src/cli/cogify/action.batch.ts
packages/cli/src/gdal/gdal.command.ts
packages/lambda-tiler/src/__test__/tile.set.cache.test.ts
packages/lambda-tiler/src/cli/serve.ts
packages/lambda-tiler/src/cli/validate.ts
packages/lambda-tiler/src/tile.set.cache.ts
packages/lambda-tiler/src/tile.set.ts
packages/shared/src/aws/__test__/tile.metadata.imagery.test.ts
packages/shared/src/aws/__test__/tile.metadata.table.test.ts
packages/shared/src/aws/__test__/tile.metadata.tileset.test.ts
packages/shared/src/aws/tile.metadata.base.ts
packages/shared/src/aws/tile.metadata.imagery.ts
packages/shared/src/aws/tile.metadata.tileset.ts
scripts/examples/index.openlayers.wmts.3857.html

sometimes we want to display the same imagery but with different rules at different zoom levels

feat: allow imagery with the same id in the rendering process twice

---

packages/linzjs-s3fs/src/__tests__/file.s3.test.ts
packages/linzjs-s3fs/src/file.s3.ts

Previously only code of 'NotFound' was throwing 404; 'NoSuchKey' threw 500
Now uses the Aws `statusCode` instead of aws code as error type.

fix/linzjs-s3fs: throw 404 CompositeError if read throws NoSuchKey

---

packages/landing/static/index.css

fix(landing): Don't use auto for svg height

---

README.md

The README referred to BSD-3, while the LICENSE file is MIT. Updated badge and text to match the file.

chore: update license referred to in README to MIT

---

packages/lambda-api-tracker/src/__test__/xyz.request.test.ts
packages/lambda-api-tracker/src/index.ts

A lot of sites will use foo.com or www.foo.com interchangeably

feat(lambda-api-tracker): remove www. from referer tracking

---

packages/bathymetry/src/__test__/stac.test.ts
packages/bathymetry/src/stac.ts
packages/cli/src/cog/__test__/cog.stac.job.test.ts
packages/cli/src/cog/cog.stac.job.ts
packages/cli/src/cog/stac.ts
packages/landing/scripts/bundle.js
packages/landing/scripts/deploy.js
packages/landing/scripts/util.js
packages/landing/static/json-schema/stac-basemaps-extension/1.0/schema.json
packages/shared/src/stac/index.ts

* Add linz basemaps schema.json
* Fix `extent/spatial/bbox` to `number[][]`
* `description` is always required
* Set `stac_version` to `1.0.0-beta.2`
* Don't use `projection` extension for `collection.json`

fix: STAC files should comply to 1.0.0-beta.2 of the specification

---

packages/shared/src/__test__/api.path.test.ts
packages/shared/src/api.path.ts

`tileXyzFromPath` was not checking that the number of parts to the url was at least 5 causing index
lookups past the end of the array.

fix(lambda-tiler): regression in invalid url parsing causing 500 Error

---

packages/bathymetry/src/__test__/stac.test.ts
packages/cli/src/cog/__test__/cog.stac.job.test.ts
packages/lambda-tiler/src/routes/__test__/attribution.test.ts
packages/shared/src/stac/index.ts

fix: Remove dashes from CC-BY-4.0 license text

---

packages/landing/scripts/deploy.js
packages/landing/static/examples/index.html
packages/linzjs-geojson/src/multipolygon/convert.ts

When deploying changed files the logic to determine the mime-type was returning the wrong
type. Fixed by passing the file extension instead of whole path.
Also deploy `examples/index.html` as `examples` and `examples/` because Cloudfront doesn't handle `index.html`
files in sub directories.

fix(landing) Deploy mime type wrong

---

.github/workflows/push.yml

Now that there are multiple repositories for basemaps share the secrets across both repositories

ci: use organisation secrets

---

packages/cli/src/gdal/gdal.command.ts
packages/linzjs-s3fs/src/__tests__/file.s3.test.ts
packages/linzjs-s3fs/src/file.s3.ts
packages/linzjs-s3fs/src/index.ts
packages/shared/src/aws/__test__/tile.metadata.table.test.ts
packages/shared/src/aws/api.key.table.ts
packages/shared/src/aws/credentials.ts
packages/shared/src/aws/index.ts
packages/shared/src/aws/tile.metadata.base.ts
packages/shared/src/file/index.ts

Using `import * as AWS from 'aws-sdk'` Imports a ton of types which are generally not needed which greatly inflate the typescript compile time.
By using `import S3 from 'aws-sdk/clients/s3'` this seems to drop builds by 2-3 seconds per project

build: improve build times

---

packages/lambda-tiler/src/routes/health.ts

Fixes: #
Static files are located at the same directory after bundle, which causes the following error.
`    "err": {
"type": "Error",
"message": "ENOENT: no such file or directory, open '/static/expected_tile_3857_252_156_z8.png'",
"stack": "Error: ENOENT: no such file or directory, open '/static/expected_tile_3857_252_156_z8.png'",
"errno": -2,
"code": "ENOENT",
"syscall": "open",
"path": "/static/expected_tile_3857_252_156_z8.png"
},`

fix(lambda-tiler): health endpoint cannot open static files.

---

packages/lambda-tiler/src/routes/health.ts

Fixes: #
We now filter the path based the health.js. More secure.

fix(lambda-tiler): filter the path for static file correctly.

---

.github/workflows/push.yml

Regression in landing script caused GOOGLE_ANALYTICS not to be set in browser code.
Fixing by ensuring that bundle is run during the deploy step so that the same env vars are present.

fix(deploy): Missing GOOGLE_ANALYTICS

---

packages/lambda-analytics/src/__tests__/index.test.ts
packages/lambda-analytics/src/index.ts

this function only processes back to the start of the year so if there are less than 24 days since the start of the year it will process less than the `MaxToProcess`

test(lambda-analytics): correct test counts for the start of year

---

packages/shared/src/log.ts
packages/shared/src/vdom.parse.ts

We were republishing these types out of @basemaps/shared causing dependent libs to have these two `@types` libraries installed when using typescript.

fix(shared): remove dependency on @types/sax and @types/pino

---

packages/landing/src/config.ts
packages/landing/src/url.ts

by default process.env.TILE_HOST is set to "" not undefined

fix(landing): correct broken wmts/xyz links in side bar

---

packages/attribution/package.json
packages/attribution/src/attribution.ts
packages/bathymetry/src/__test__/stac.test.ts
packages/bathymetry/src/stac.ts
packages/cli/src/cog/__test__/cog.stac.job.test.ts
packages/cli/src/cog/cog.stac.job.ts
packages/cli/src/cog/stac.ts
packages/geo/README.md
packages/geo/package.json
packages/geo/src/index.ts
packages/geo/src/stac/index.ts
packages/geo/src/stac/stac.attribution.ts
packages/lambda-tiler/src/routes/__test__/attribution.test.ts
packages/lambda-tiler/src/routes/attribution.ts
packages/landing/src/ol.attribution.ts
packages/shared/src/index.ts

`@basemaps/shared` is getting to be quite a large library with lots of dependencies, lets only import it if we really need it.
as `@basemaps/attribution` is a library others may install, reduce the number of dependencies needed

feat(attribution): remove `@basemaps/shared` dependency to make it smaller to install

---

packages/lambda-tiler/src/__test__/wmts.capability.test.ts
packages/lambda-tiler/src/wmts.capability.ts

This was creating a TileMatrixSet definition per use which was causing the file size to explode when multiple layers were used as each layer would export a copy of each TileMatrixSet they used.

fix(lambda-tiler): only export the tile matrix set once per epsg code

---

packages/landing/src/__test__/hash.test.ts
packages/landing/src/url.ts

`window.location.port == null` was failing and then causing the `:` to be added into the url even when the default port `:443` was being used.
`window.location.origin` handles the scheme, port and domain joining for us and fixes the problem

fix(landing): correct the WMTS url for arcgis users

---

.github/PULL_REQUEST_TEMPLATE.md

Since we do not use github issues it makes no sense to show the fixed issues

build: remove github pull request template

---

package.json
yarn.lock

https://github.com/yargs/y18n/compare/v5.0.4...v5.0.5

build(deps): Upgrade y18n to 5.05 to fix the prototype pollution issue.

---

packages/attribution/src/__tests__/attr.test.ts
packages/attribution/src/attribution.ts

See BM-113 for more information

fix(attribution): disable lat/lng bounds checking until bad bounds are fixed.

---

packages/linzjs-s3fs/src/index.ts

Fixes a issue where `fsa.read('./cache')` would throw on relative paths

fix(s3fs): default to using the local file system

---

packages/_infra/src/config.ts
packages/landing/static/examples/index.maplibre.compare.3857.html
packages/landing/static/examples/index.maplibre.opacity.3857.html
packages/landing/static/examples/index.maplibre.vector.3857.html

This fixes a inconsistency where some things are pointing to `tiles.` and some are not

fix: default to basemaps.linz.govt.nz rather than tiles.basemaps.linz.govt.nz

---

packages/lambda-tiler/bundle.sh
packages/lambda-tiler/package.json
scripts/bundle.js

`farmhash` is a c lib and needs to be bundled as a c lib

fix(lambda-tiler): bundle farmhash correctly

---

packages/config/src/dynamo/dynamo.config.ts
packages/lambda-tiler/src/cli/serve.ts
packages/lambda-tiler/src/tile.set.cache.ts

This fixes a issue where a database update is applied but some lambdas will hold onto the old config until they get restarted

fix(config): do not cache tile sets forever as they can be updated

---

packages/_infra/src/serve/index.ts
packages/_infra/src/serve/lambda.tiler.ts

From some inital performance testing this greatly reduces the time for the lambda to serve a tile as it does not have to traverse multiple networks between LINZ, ALB and VPCs

feat(infra): move lambda into the same VPC as the ALB

---

packages/lambda-tiler/package.json
packages/lambda-tiler/src/__test__/index.test.ts
packages/lambda-tiler/src/__test__/xyz.test.ts
packages/lambda-tiler/src/__test__/xyz.util.ts
packages/lambda-tiler/src/cli/dump.ts
packages/lambda-tiler/src/cli/serve.ts
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__test__/health.test.ts
packages/lambda-tiler/src/routes/health.ts
packages/server/package.json
packages/server/src/server.ts
yarn.lock

This forces query strings to be lower cased to allow `?api=foo&API=bar`

build(deps): linzjs/lambda 1.1.0

---

packages/cli/src/cli/base.cli.ts

CommonJS does not have import.meta.url and when bundled dies with `TypeError: Invalid URL`
remove the package.json lookup as it is not really required.

fix(cli): correct path issues with ESM modules being bundled into docker containers

---

packages/lambda-tiler/src/cli/tile.set.local.ts
packages/lambda-tiler/src/tile.set.cache.ts
packages/lambda-tiler/src/tile.set.raster.ts
packages/server/src/cli.ts

`basemaps-server` CLI can now be pointed at a folder of COGs
```
./basemaps-server /home/blacha/cogs
```
aswell as being pointed at the basemaps configuration repo
```
./basemaps-server /home/blacha/basemaps-config/config
```

feat(server): add ability to serve a folder full of tiffs

---

packages/cli/Dockerfile

Docker build is currently broken due
> @basemaps/infra:   Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 23.222.12.50 443]
This is caused by https://github.com/nodesource/distributions/issues/1266
We can remove this workaround once it is fixed upstream

fix(cli): work around certificate issues

---

packages/shared/src/file/__test__/file.local.test.ts
packages/shared/src/file/index.ts

this fixes a issue where the server cannot find tiffs in paths like "some_folder/foo.tiff" or "c:\bar.tiff"

fix(server): use default of local file system for unknown paths

---

packages/_infra/src/serve/lambda.tiler.ts

Increasing memory size increases the cpu count used for image recompression

feat(infrastructure): increase performance of lambda function

---

packages/_infra/src/serve/lambda.tiler.ts

This cache size change means the lambda's no longer run out of memory #1882

perf: lower the lambda size as the timeout bug has been fixed

---

packages/landing/src/components/map.tsx

Rather than starting to load aerial imagery then switching to the "correct" layer

fix(landing): load the correct layer on first load

---

packages/bathymetry/src/bathy.maker.ts
packages/cli/package.json
packages/cli/src/cog/builder.ts
packages/lambda-tiler/package.json
yarn.lock

p-limit is needed to run the basemaps server but its not listed as a dependency
```
npm install @basemaps/server
npx basemaps-server foo // "Cannot find package 'p-limit'"
````

fix(lambda-tiler): p-limit is a needed dependency

---

packages/landing/src/components/layer.switcher.dropdown.tsx

It was showing up as "layer:[object HTMLSelectElement]"

fix(landing): correctly track the event name of the layer

---

packages/_infra/package.json
packages/attribution/package.json
packages/bathymetry/package.json
packages/cli/package.json
packages/config/package.json
packages/geo/package.json
packages/lambda-analytics/package.json
packages/lambda-tiler/package.json
packages/landing/package.json
packages/server/package.json
packages/shared/package.json
packages/tiler-sharp/package.json
packages/tiler/package.json

This reverts commit d57532186c445aa3b03efe3d91645c4efb2d714d.
Since v6.21.0 was never published to NPM the deployment process will fail until it is, this reverts all the versions back to pre v6.21.0 numbers a new v6.22.0 will be published later.

Revert "release: v6.21.0 (#2104)"

---

packages/cli/src/cli/cogify/__test__/action.batch.test.ts
packages/cli/src/cli/cogify/action.batch.ts

AWS Batch does not allow unicode in job names so replace the job name with a hex digested hash

fix(cli): allow unicode job names

---

.github/workflows/push.yml

Windows builds are taking 5+ minutes linux build and deploy complete in around 5 minutes

ci: stop waiting for windows builds before deploying

---

CHANGELOG.md
lerna.json
packages/_infra/CHANGELOG.md
packages/_infra/package.json
packages/attribution/CHANGELOG.md
packages/attribution/package.json
packages/bathymetry/CHANGELOG.md
packages/bathymetry/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/config/CHANGELOG.md
packages/config/package.json
packages/geo/CHANGELOG.md
packages/geo/package.json
packages/lambda-analytics/CHANGELOG.md
packages/lambda-analytics/package.json
packages/lambda-tiler/CHANGELOG.md
packages/lambda-tiler/package.json
packages/landing/CHANGELOG.md
packages/landing/package.json
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/tiler-sharp/CHANGELOG.md
packages/tiler-sharp/package.json
packages/tiler/CHANGELOG.md
packages/tiler/package.json

- AWS CDK v2
- Names in attribution json for QGIS
- Convert http 500 errors to 404 when tilesets cannot be found

release: v6.24.2

---

packages/lambda-tiler/src/routes/__test__/health.test.ts

MacOSX sometimes takes too long and fails to execute these tests

test: increase test timeout

---

packages/lambda-tiler/src/__test__/tile.import.test.ts
packages/lambda-tiler/src/routes/import.ts

Removed `ctx.override!.id = id;`, as `await CogJobFactory.create(ctx);` will set a new uild if id not exists.

feat(lambda-tiler): Remove the job id to use ulid and update HTTP status code.

---

packages/landing/src/components/debug.tsx
packages/landing/src/components/map.tsx
packages/landing/src/config.debug.ts

This removes the clutter when trying to create screenshots with tools like playwright.
it also adds a `map-loaded` div once the map has loaded in screenshot mode.

feat(landing): remove debug overlays to make it easier to screenshot

---

packages/_infra/src/cogify/index.ts
packages/_infra/src/serve/db.ts
packages/config/src/dynamo/dynamo.config.ts

This should fix the following problems, when insert and update records to dynamodb.

fix(infra): Fix the cog batch job to put record to dynamodb.

---

packages/landing/src/components/debug.tsx

This removes all text, now its just the attribution shown

fix(landing): remove the version information from the screenshot view

---

packages/cli/src/cli/cogify/action.job.ts

Processing ID need to pass action.job cli as a parameter, in order to prepare the JobContext in batch with the processingId.

feat(cli): Pass processingId to action job cli for the batch job.

---

packages/lambda-tiler/src/__test__/wmts.capability.test.ts
packages/lambda-tiler/src/routes/__test__/wmts.test.ts
packages/lambda-tiler/src/routes/tile.wmts.ts
packages/lambda-tiler/src/wmts.capability.ts

Some services (ArcGIS) only support the first ResourceURL
Some services (Leaflet) randomly pick from the list of ResourceURL
Adding a ?format= allows the user to specify which output imagery format they want the wmts to supply
Also supports multiple formats wit h`?format=jpeg&format=png` to provide a user preference list.

feat(lambda-tiler): allow selection of output format for wmts with ?format=

---

packages/cli/src/cli/cogify/action.cog.ts
packages/cli/src/cli/folder.ts

This should fix the following problem when we process multiple tiffs in one batch job.

feat(cli): Make a sseperate folder for each tiff for group cogs batch job.

---

packages/tiler-sharp/src/__tests__/tile.creation.test.ts
packages/tiler-sharp/src/index.ts

When resizing past the webp limit of 16k x 16k extract the correct region form the source and scale it directly to the target output file

fix(tiler-sharp): resize to the target window after extracting the region

---

packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__tests__/fonts.test.ts
packages/lambda-tiler/src/routes/__tests__/memory.fs.ts
packages/lambda-tiler/src/routes/fonts.ts
packages/lambda-tiler/src/routes/sprites.ts
packages/server/src/cli.ts
packages/server/src/server.ts
packages/shared/src/const.ts
packages/tiler-sharp/package.json
yarn.lock

Using `/v1/fonts` over `/v1/glyphs` as the uri as that is what tileserver-gl uses

feat(lambda-tiler): serve assets via /v1/sprites and /v1/fonts

---

packages/cli/src/cli/server/action.serve.ts
packages/landing/src/components/debug.tsx
packages/landing/src/config.debug.ts

This adds another checkbox to show the bounding box of the generated COGs  while in debug mode.
Additional both `Source` and `Cog` now link to their geojson source files so they can be downloaded.

 feat(landing): show cog extents in debug mode

---

packages/lambda-tiler/src/routes/__tests__/wmts.test.ts
packages/lambda-tiler/src/routes/tile.wmts.ts

ArcGIS Pro has "format" as a reserved word and cannot be used.
BM-636

feat(landing): support ?tileFormat as a alias to format BM-636

---

packages/lambda-tiler/src/__tests__/wmts.capability.test.ts
packages/lambda-tiler/src/wmts.capability.ts

fix(lambda-tiler): correct wgs84 bounding box when layers are large BM-631

---

packages/landing/src/attribution.ts

We are now using the improved titles which no longer start with geographx
Example titles to be ignored
> New Zealand 8m DEM Hillshade (2012)
> New Zealand 8m DEM Texture Shade (2012)

fix(landing): ignore all layers with " dem " in the title

---

.github/workflows/push.yml

To fix this:
`github.head_ref`  is used for `pull_request` events.
>  This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target
`push` does not have a value.
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

ci: head_ref doesnt exist on "push"

---

.github/workflows/containers.yml

Previously it was making two container hashes and the order of the tags was
- major.minor, major
- latest, major.minor.patch

ci: correct the ordering of docker tags in github webui

---

.github/workflows/containers.yml
packages/_infra/src/edge/index.ts
packages/attribution/src/attribution.ts
packages/cli/src/cli/overview/overview.wmts.ts
packages/geo/src/stac/index.ts
packages/geo/src/stac/stac.attribution.ts
packages/lambda-tiler/src/__tests__/wmts.capability.test.ts
packages/lambda-tiler/src/__tests__/xyz.util.ts
packages/lambda-tiler/src/routes/__tests__/wmts.test.ts
packages/lambda-tiler/src/routes/attribution.ts
packages/lambda-tiler/src/routes/tile.json.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/lambda-tiler/src/routes/tile.wmts.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/__test__/filter.test.ts
packages/lambda-tiler/src/util/config.loader.ts
packages/lambda-tiler/src/util/filter.ts
packages/lambda-tiler/src/wmts.capability.ts
packages/shared/src/__tests__/util.test.ts
packages/shared/src/util.ts

This adds `?date[before]=` and `?date[after]=` to a number of routes to filter the imagery down to a specific date rate.
These dates are inclusive so `?date[before]=2022` its a `less than or equal`.

feat: filter layers by date

---

packages/lambda-tiler/src/util/config.loader.ts

When starting a server without assets all urls fail with this error, assets are not required.

fix(lambda-tiler): do not crash server when assets are not found

---

packages/tiler-sharp/src/index.ts
packages/tiler/src/__tests__/tiler.test.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

This should reduce the amount of error when scaling large aspect ratios eg 512x16

fix(tiler): when scaling rectangles if the scaleX and scaleY differ scale using the larger dimension BM-772

---

packages/config/src/json/tiff.config.ts
packages/lambda-tiler/src/cli/render.tile.ts

the server automatically handles the scaling, so GSD numbers of tiff do not need to be consistent across imagery.

fix(server): gsd does not actually need to match

---

packages/config/src/json/tiff.config.ts

fixes:
```
(node:355570) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. 
Please close FileHandle objects explicitly using FileHandle.prototype.close().
In the future, an error will be thrown if a file descriptor is closed during garbage collection.
```

fix(server): close tiff connections once they have been queried

---

packages/tiler-sharp/src/index.ts
packages/tiler/src/__tests__/tiler.test.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

This reverts commit c498856b1851026d0f3cb87fc9be4ac8cb0b4bc2.

Revert "fix(tiler): when scaling rectangles if the scaleX and scaleY differ scale using the larger dimension BM-772 (#2693)"

---

packages/landing/src/components/map.tsx

- Changes the layer fade animation to use the built-in MapLibre transition `raster-opacity-transition` when fading layers rather than repeatedly updating the `raster-opacity` ourselves in JavaScript as before.
- Adds an fade transition when previous layers are being removed, which makes the appearance less jarring.
- Reduces the fade time to 750ms from 1000ms.
The order of operations is now:
- The date range sliders are moved.
- We check if the layers which would be visible in the map bounding box within the date range specified have changed.
- If they have, we add a new layer with the source set to the new date after and date before values.
- The new layer fades in over 750ms.
- If the tiles for the new layer take longer than 750ms to load, they continue to load.
- Once the new layer has …

feat: use transition property for fades, add fade when removing layer

---

packages/landing/src/components/debug.tsx

Adds a count of the number of files in the imagery configuration to the debug viewer

feat(landing): show number of COGs in current imagery

---

packages/_infra/package.json
packages/_infra/src/analytics/edge.analytics.ts
packages/_infra/src/serve/lambda.tiler.ts
packages/lambda-analytics/package.json
packages/lambda-tiler/package.json
yarn.lock

now that AWS supports node 18 we should upgrade
This is a bigish change as `aws-sdk` is no longer bundled by AWS, so we need to include it in our built lambda's
https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
some time in the future we should also migrate to aws-sdk v3.

feat: upgrade lambdas to nodejs 18

---

packages/_infra/package.json
yarn.lock

Moving to >=2.80 causes deployments to fail with
```
Unable to make progress anymore among: Edge := pending stack
```

build: rollback cdk to 2.79.x as 2.80 introduces breaking changes

---

packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/routes/__tests__/attribution.test.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts

This reverts commit db3ff1b09f849a26d7287925c7b57d71e1fa6d76.
Research documentation suggest to use 200 Transparent Image.
https://github.com/linz/basemaps/blob/master/docs/api/empty-tiles.md

Revert "feat(lambda-tiler): return 204 no content instead of a empty images (#2829)"

---

packages/cogify/src/cogify/cli/cli.config.ts

Makes the URL handler similar to how the parser works https://github.com/linz/basemaps/blob/master/packages/landing/src/url.ts#L53

fix(cogify): correct ordering of lat lon

---

packages/cogify/src/cogify/cli/cli.cog.ts
packages/cogify/src/cogify/parsers.ts

Adds a `--from-file` option to the `cogify create` command. This has been added to simplify passing multiple arguments to `cogify create` inside an Argo workflow.

feat: add --from-file option to cogify create command

---

packages/tiler-sharp/src/index.ts

Without a `.raw()` the `sharp.toBuffer()` will compress the image back into the input format which is mostly webp, this reduces tile creation time by approx 25% for my simple tests

feat(tiler-sharp): do not recompress intermediate tiffs

---

packages/lambda-tiler/src/cli/render.tile.ts
packages/tiler/src/tiler.ts

When scaling imagery sometimes with rounded pixel math the aspect ratio can skew too far in one direction, by re running the math with a lower rounding bias we can sometimes get a better aspect ratio output

fix(tiler): allow modification of the rounding bias to help reduce aspect ratio skews

---

packages/linzjs-geojson/src/multipolygon/__tests__/area.test.ts
packages/linzjs-geojson/src/multipolygon/area.ts

Adds calculation of the area of GeoJSON rings, and refactors the calculation of polygon and multipolygon areas to use this ring area calculation. Docstrings and tests are added for each of the Area methods.

feat(linzjs-geojson): add Area.ring() method and Area tests

---

packages/cli/Dockerfile

This been saved in the incorrect location.
`"type":"Error","message
":"Cannot find module '@linzjs/style/.prettierrc.js'\nRequire stack:\n- /app/basemaps-config/.prettierrc.cjs\n- /app/index.cjs"`

fix(cli): Correct the path of linzijs prettierrc.js location.

---

packages/cli/src/cli/config/action.import.ts

As we separated expired/disabled configs as individual config files in [basemaps-config](https://github.com/linz/basemaps-config) repo. Now we need the ci process to automatically pick the config changes and inserts for individual imagery.
- Update the basemaps cli import command to output changes for all tileset configs that only have a single layer.
- relocate and reuse the prepare preview links logic into separated functions
- Tested locally and test output markdown will update into PR comments soon.
[BM-869]: https://toitutewhenua.atlassian.net/browse/BM-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cli): Update the import cli to output preview links for individual configs. BM-869

---

.github/workflows/containers.yml
packages/cli/Dockerfile
packages/cli/package.json
packages/cli/src/cli/github/make.cog.pr.ts
yarn.lock

When we make changes to config file in the basemaps-config repo, we need to format it before commit. Current way of using prettier is broken because we need to install @linzjs/style into the cli docker container. A better solution is just run prettier in the config directory before commit the changes.
- Remove all the prettier stuff from cli
- Run npx prettier in the chirld process in config repo.
[BM-810]: https://toitutewhenua.atlassian.net/browse/BM-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cli): Create pull request cli to format the config files by npx prettier. BM-810

---

packages/cli/src/cli/github/make.cog.pr.ts

When we make changes to config file in the basemaps-config repo, we need to format it before commit. Current way of using prettier is broken because we need to install @linzjs/style into the cli docker container. A better solution is just run prettier in the config directory before commit the changes.
- Remove all the prettier stuff from cli
- Run npx prettier in the chirld process in config repo.
[BM-810]: https://toitutewhenua.atlassian.net/browse/BM-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cli): Run npm install in the basemaps-config to install the @linz/style

---

packages/cogify/src/cogify/cli/cli.config.ts
packages/cogify/src/cogify/cli/cli.cover.ts
packages/cogify/src/cogify/parsers.ts
packages/cogify/src/cutline.ts
packages/cogify/src/tile.cover.ts

*What does this change aim to achieve?*
Updates the cogify CLI commands to ensure that arguments representing folder paths have trailing slashes. Adds a `UrlFolder` parser for cmd-ts which parses the input string as a URL, and appends a trailing slash if it's missing. Changing the type from `string` to `URL` (via the `Url` or new `UrlFolder` parsers) involved changing places that use these values to construct other paths. Where these are passed to `fsa` functions, these are converted back to strings using `urlToString`.
*Why is this change being made? What implications or other considerations are there?*
Parts of the cogify commands were using strings for paths, while other parts were using URLs. This led to a situation where a string path was created by `fsa.joinAll()` which did not have …

feat(cogify): ensure cogify path-like args have trailing slashes. BM-858

---

packages/cli/src/cli/config/action.imagery.config.ts
packages/cogify/src/cogify/cli/cli.config.ts

*Cloudwatch logs not capture the imagery id, which can't output id into the slack notifications for create-config.*
*Fix the log add imagery id*
*Log change not required*

feat(cli): Add imagery id in the create config done log for slack notifications.

---

packages/cogify/src/cutline.ts

Fixing a import path, so that running the command from the console works
Imports need to include ".js" or nodejs cannot find the files.

fix(cogify): correct import path

---

packages/config/src/json/__tests__/config.loader.test.ts
packages/config/src/json/tiff.config.ts

Most of LINZs imagery is currently stored in S3 with the format `'s3://linz-imagery/:rgion/:name/:projection/:imageryType/` this structure means basmeaps guesses the imagery name as `:imageryType` so all imagery is called "rgb" 
This makes a ignore list of common folder structures LINZ uses which do not make sense as imagery names, eg "rgb", "dem_1m" or "3857" 
Instead it traverses up the imagery path to see if there is a better name, 
before this change a imagery path of `'s3://linz-imagery/auckland/auckland_sn5600_1979_0.375m/2193/rgb/` would be called "rgb" after this change it is called "auckland_sn5600_1979_0.375m"

fix(config): do not use "rgb" or projection codes for imagery names

---

packages/cogify/src/cogify/cli/cli.cog.ts

Adds `--concurrency` to all multiple `gdal_translate` to run at the same time.
In COG Creation `gdal_translate` often has peaks of CPU usage across all cores and then goes down to 1 core for long periods, by running multiple `gdal_translates` on the same machine we can increase the usage of the CPU

feat(cogify): add --concurrency to allow concurrent gdal_translates

---

packages/cogify/src/cogify/cli/cli.cog.ts

Skips creating a COG in the `cogify create` command if an input item STAC (from `cogify cover`) does not contain any source tiffs.
`cogify cover` can currently create instructions to create a target COGs from no source tiffs. When this happens, the `cogify create` command crashes. To allow in progress Argo workflows to complete, we need to allow the `cogify create` command to skips any of these item STAC files which have been created by `cogify cover`.

fix: skip creating cog when no source files BM-860

---

packages/landing/src/components/layer.switcher.dropdown.tsx

Orders the categories in the layer selector dropdown on the landing page, so that the new 'Scanned Aerial Imagery' category appears after Urban and Rural layers.
Currently the order of categories in the dropdown is based on the order in which they appear in the WMTS file which the landing page loads the layers from. This could change over time as new layers with different alphabetical order are added.

feat(landing): Order the categories in the layer dropdown BM-880

---

packages/cogify/src/cogify/cli/cli.config.ts
packages/lambda-tiler/src/cli/render.preview.ts
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/validate.ts
packages/tiler-sharp/src/index.ts
packages/tiler/src/__tests__/tiler.test.ts
packages/tiler/src/tiler.ts

Adds a new endpoint `/v1/preview` which generates `og:image` previews for a specific location.
```
/v1/preview/:tileSet/:tileMatrixSet/:z/:lon/:lat
```
example:
```
/v1/preview/aerial/WebMercatorQuad/177.3998405/-39.0852555
```
When people share links to basemaps they are currently presented with the same image of Lyttelton, which while really nice looking is not representative of what they are actually get a link to.
This is the first step in providing an actual image of the area people are linked to, I will add a screenshot tester of this too.

feat(lambda-tiler): create preview images for og:image BM-264

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/static/index.css

Increase the visual prominence of the category heading in the layer dropdown on the landing page. It does this by:
- Increasing the size, from 75% layer name size to 90% layer name size.
- Darkening the colour, from a light grey `#999999` to  LUI teal `#00425d`
- Adding 1px of letterspacing, common typographic practice for all caps text to improve legibility.
**Before**:
**After:**
After adding the georeferenced historical imagery layers to Basemaps, there are many more layers in the dropdown than before. The category of these layers is also more important than before when searching, thus increasing the visual prominence of the category header will improve the UX when searching for a layer in the dropdown.
~~The method of inserting styles into the `react-select` `Select` component feels …

feat(landing): increase visual prominence of category in layer dropdown

---

packages/config/package.json
packages/config/src/json/__tests__/config.loader.test.ts
packages/config/src/json/json.config.ts
packages/config/src/json/tiff.config.ts

Sometimes when tiffs are create they are created outside the bounds of where the source tiff actually has data. 
`gdal_translate` will then create a completly empty tiff, as the tiffs are created with `sparse_ok=true` the internal tiff tag `TileOffsets`  which contains the file offsets for all the internal tiles will contain offsets of `0` with byte length of `0`.
If all the offsets are `0` then there is no data inside the tiff.
We are seeing a large number of empty tiffs being imported into our configuration and until we can clean out the source locations it is easier to check the tiff to see if it contains data, when we are creating the configuration.
I have tested this with the current [linz/basemaps-config](https://github.com/linz/basemaps-config) configs and it found 4,548 empty tiff …

feat(config): detect empty images and ignore them

---

packages/lambda-tiler/src/routes/__tests__/preview.index.test.ts
packages/lambda-tiler/src/routes/preview.index.ts

Start forwarding the config location to the preview images if a config  exists
To preview external imagery from a config location, the preview url needs to include the `?config` without it, the preview imagery will not be able to create a preview of the imagery.

fix(lambda-tiler): generate previews from config urls too

---

packages/cli/src/cli/config/action.imagery.config.ts
packages/cogify/src/cogify/cli/cli.config.ts

adds a `urlPreview` to all logs about imagery being created
When slack generates a alert for new imagery it needs to know how to make a preview thumbnail, this adds a log key `urlPreview` that can be used to make a pretty thumbnail for new imagery.

feat(cli): include urlPreview for preview links

---

packages/cli/src/cli/config/action.imagery.config.ts
packages/config/src/json/__tests__/config.loader.test.ts
packages/config/src/json/tiff.config.ts

When [topo-workflows](https://github.com/linz/topo-workflows) processes imagery, it puts all the resulting imagery tiffs into `flat/`, when we attempt to create a config from this folder it names the imagery "flat" this name  is not very helpful for determining what the imagery is of.
Ignores `flat/` from folder names when guessing imagery names.

fix(config): ignore the argo folder "flat/" in guessing imagery names

---

packages/cli/src/cli/config/action.import.ts

The new cogify workflow deprecate the old job.json and use covering.json to prepare jobs. We need fix the import to be able to support both job.json and covering.json. 
We try to get gsd from job.json first, if not exist we loop for covering.json. Also, I have moved the prepare url inside the if condition to stop these s3 read and only try to get job.json if there is a change in config.

Fix(cli): Import config to get target zoom from covering.json

---

packages/config/src/json/json.config.ts

The queue in config bundle never get await cause a empty config returned earlier before processed.
Fix the problem by adding return for the queue function.

fix(cli): Fix the missing return in plimit queue.

---

packages/tiler-sharp/src/index.ts

Some imagery is being combined with the background image causing white lines around the imagery when a background color is used.
When using a transparent background the problem goes away
This is caused by the imagery being mixed with the background as part of the composition process.
`ret.info.*` contains extra metadata which can change how imagery is overlayed into the output file, by only allowing the metadata we want `height`, `width` and `channels` this restricts the output image creation process to how we want.

fix(tiler-sharp): do not multiply imagery with the background color BM-885

---

packages/cogify/src/cogify/gdal.command.ts

To create the highest quality overviews, tell GDAL to create new overviews directly from the source imagery
Because we are mostly importing RGBA imagery from webp COGs now instead of straight geotiffs, overviews now exist and GDAL is starting to automatically use them.
The overviews are generally lossly already so using them as a base to create more overviews means we are compounding the lossy compression.

fix(cogify): ignore existing overviews so they are not recompressed

---

packages/config/src/json/json.config.ts
packages/config/src/memory/memory.config.ts

`ts_all` config might generate different layer orders from each build, we should sort this before update to dynamoDb.
Add a sort for the ts_all layers, by layer.name.

feat(cli): Sort the ts_all config by the imagery name.

---

packages/cogify/src/cogify/covering.ts
packages/cogify/src/tile.cover.ts

skip creating output tiles with <1 pixel of coverage
When reprojecting imagery sometimes tiny slithers of overlaps are detected the cogify command would attempt to create a tiff which sometimes has no actual data in it. 

feat(cogify): skip creating any tiles that are below 1 pixel in coverage

---

packages/landing/src/components/map.switcher.tsx

The map switcher button in the bottom right switches the layers as well as the layer dropdown, we currently only track that a layer is switched and not which source is clicked
Start tracking when the map-switcher is used to switch layers

feat(landing): track when the map switcher is clicked

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/src/components/map.switcher.tsx
packages/landing/src/config.map.ts

The server currently does not provide a full list of tilesets to the client, so some layers need to be hard coded into the layer switcher. 
Adds the new new historical imagery tilesets into the layer switcher dropdown

feat(landing): hard code scanned aerial imagery layers BM-892

---

packages/lambda-tiler/src/util/__test__/config.loader.test.ts
packages/lambda-tiler/src/util/config.cache.ts
packages/lambda-tiler/src/util/config.loader.ts

When failed to get config file from s3, return correct error code in logs and remove the 500 error in #proj-basemaps-alerts
Catch the error from `fsa.readJson(config)`, and throw correct error code and message.

fix(lambda-tiler): Catch the error code while reading the config file in api. BM-898

---

packages/landing/src/config.map.ts

Fixes a broken tileset link name
a extra " was added to the tileset name.

fix(landing): correct broken tileset name

---

README.md

Release rollback in basemaps is very simple as it all build inside the github actions. We need add some documentation about it for developer to process rollback easily.
Add section of deployment rollback after deployment section.

doc: Add release rollback documentation

---

packages/config/src/json/json.config.ts

We are trying to add slash at the end of all the urls in the basemaps-configs. 
https://github.com/linz/basemaps-config/pull/809
This will fix the bundle to find the correct imagery id from the both new and old url.

feat(cli): Allow bundle to guess the imagery ID from the url with slash ending.

---

packages/cli/Dockerfile

The old node js installation in docker is deprecated. Update to use the new one based on https://github.com/nodesource/distributions#installation-instructions

fix(cli): Fix the installiation of node js in the cli container. BM-916

---

packages/_infra/src/config.ts
packages/config/src/json/__tests__/config.loader.test.ts
packages/lambda-tiler/src/util/config.loader.ts

LINZ is starting to suffix s3 buckets with a rough indication to the quality of data inside of the bucket a "scratch" bucket is a temporary storage location and should have a data lifecycle rule set to delete data after 90/180 days.
Adds Workflows and Basemaps scratch buckets to allowed locations

feat: allow reads from linz "-scratch" buckets TDE-906

---

packages/cli/Dockerfile
packages/cli/src/gdal/gdal.docker.ts
packages/cogify/src/cogify/gdal.runner.ts

Upgrade gdal to 3.7.2 to fix the webp CVE
Upgrade the cli docker container version to 3.7.2

build: Upgrade the cli container to use gdal 3.7.2

---

.github/workflows/push.yml

JIRA is now tracking when our tickets transition between enviroments, but is currently not tracking nonprod very well
To better align with JIRA enviroment wording change "nonprod" to "dev"

ci: switch to "dev" as the main nonprod enviroment to be more consistent with JIRA

---

packages/cli/src/cli/util.ts
packages/landing/scripts/deploy.js

Fixing a bug where cloudfront would rate limit us from invalidations
- Invalidate only top level directories
- upload 10 files at a time

fix: reduce the number of cloudfront invalidations

---

packages/cli/src/cli/util.ts
packages/landing/scripts/deploy.js

Deployment crashed with "NotFound" error, which can be thrown from a head object
Fix the deployment failure.

fix: head can throw "NotFound"

---

packages/landing/scripts/deploy.js

Deployments currently fail due to too many wildcards, limit the wild cards to the top level directories eg "/docs*" not "/docs/example/foo*"
Invalidate top level directories and add more logging / debugging information.

fix: only invalidate top level directories

---

packages/config/src/json/__tests__/config.loader.test.ts

MacOSX sometimes fails to run the unit tests as it times out, see https://github.com/linz/basemaps/actions/runs/6805045858/job/18503816927#step:2:889
Update the unit test timeouts to 1 second.

fix: macosx sometimes timesout when running filesystem tests

---

.github/workflows/push.yml

Build is failing due to a folder being owned by root
create the folder early so the docker container does not create it, which causes it to be owned by root.

ci: fix permissions of dist folder as it can end up being owned by root

---

.github/workflows/push.yml

Environment variables like google analytics were not being set to mkdocs, which prevents it from adding them to the docs
proxy environment variables into docker

ci: ensure env vars are passed to mkdocs

---

.github/workflows/containers.yml

CLI containers are currently being published as basemaps/server for major `server:v6` and major.minor `server:v6.20` tags.
correct the tag name for server

ci: publish the correct container for major and major.minor tags

---

.github/workflows/push.yml

To be consistent with the rest of LINZ rename our environments to `nonprod` and `prod`
Rename environments to `prod` and `nonprod`

ci: rename enviroments to be consistent with the rest of linz BM-923

---

packages/config/src/json/__tests__/tiff.config.test.ts
packages/config/src/json/tiff.config.ts
packages/server/src/config.ts
packages/shared/src/__tests__/util.test.ts

When starting a server directly from tiffs we need both the `all` tileset so the UI finds imagery, we also need to allow for both `/imagery/otago` and `/imagery/otago/` to be supplied to the STAC loader.
Search two locations for STAC collection.json if the target is not a folder
Create the virtual `all` tileset for servers started from imagery

fix(server): create missing all tileset and stac lookup locations

---

packages/server/src/cli.ts
packages/server/src/route.layers.ts
packages/server/src/server.ts

When starting the server against local tiff imagery it is sometimes very hard to know what imagery was actually loaded
when running a local server adds a `/layers` URL to  give a preview of imagery

feat(server): layer preview page for local debugging

---

.github/workflows/push.yml
package.json
yarn.lock

Typedocs was installed as a POC it is not working very well and is slowing the build pipeline down quite a lot.
Removes typedoc from the build pipeline

docs: remove typedocs for now as it is slowing down the build too much

---

packages/cli/src/cli/config/action.bundle.ts
packages/config/src/config/config.bundle.ts

Assests are optional and should not be required to make a configuration bundle
ensure the assets are set as optional remove the required flag from the bundler cli

fix(cli): assets are optional

---

docs/developer-guide/README.md
docs/operator-guide/quick-start.md

single line code blocks sometime overflow the line, which makes it hard to read.
fixes some formatting errors and typos
moves most longer code blocks into multi line statements

docs: move to multiline to remove scroll bars

---

packages/cli/src/cli/config/action.bundle.ts
packages/cli/src/cli/config/action.import.ts
packages/cli/src/cli/config/config.diff.ts
packages/cli/src/cli/config/config.update.ts
packages/config/src/json/json.config.ts
packages/config/src/memory/memory.config.ts

It is useful to compare configuration bundles, but they contain too many ids and values that could rotate. The import command can compare two configurations while ignoring the changes in ids.
compare config bundles using `--target config.json`

feat(cli): compare config bundles using --target config.json

---

packages/cogify/src/cogify/cli/cli.cog.ts
packages/cogify/src/cogify/stac.ts
packages/config/src/index.ts

As cogify does not  have the exact bounding polygon of the data inside the tiff, there are occasions where a tiff is created outside the extent of the data. this tiff is empty and gdal will create a empty sparse tiff.
These tiffs are useless and should be ignored/deleted.
Check the output tiff to see if its empty before uploading it.

fix(cogify): prevent empty tiffs from being stored

---

packages/cli/src/cli/config/action.import.ts

Virtual tile sets such as `ts_all` are needed when importing into dynamodb as they are materialized and stored into dynamo.
re-adds virtual tileset creation before applying the diff. 

fix(cli): virtual tilesets are required for importing into dynamo

---

packages/config/src/json/json.config.ts

The empty tiff checker was designed to remove empty tiffs from the configuration as we had 9,000 tiffs that were empty. It greatly slows down the build pipeline. 
We have since deleted the tiffs and have added logic to prevent them being uploaded in future.
remove the `isEmpty` check when creating config from tiffs.

feat(config): disable the empty tiff checker

---

packages/cli/src/cli/config/action.import.ts
packages/cli/src/cli/config/config.diff.ts
packages/cli/src/cli/config/config.update.ts

Changes were not being formatted correctly in the new config differ, refactor how the changes are  being processed improving logic around duplicate layers.
Check for all layers being used.

feat(cli): show which layers are being deleted from the aerial config

---

packages/lambda-tiler/bundle.sh

the arm lambda function is not getting the correct build of the new libvips
force arm install

fix(lambda-tiler): fixup up bundling of arm libvips

---

package-lock.json
packages/_infra/package.json
packages/_infra/src/index.ts
packages/_infra/src/parameters.ts
packages/cli/package.json
packages/cli/src/cli/util.ts
packages/shared/package.json

Upgrade to sdk v3 version.
Only upgrade for _infra and cli package. The shared package will require chunkd to upgrade together.

build: Upgrade to sdk v3 for infra and cli package

---

packages/landing/src/components/map.tsx

The upgrade of maplibre broke the bounds check for NZTM.
Reduces the bounds slightly to fix what looks to be a rounding error.

fix(landing): reduce bounds for nztm BM-394

---

packages/landing/scripts/deploy.mjs

Deployments are broken as a string is being passed into a function requiring a URL
use a URL instead of a string.

fix(landing): use urls to upload files

---

packages/cogify/src/preset.ts

Some of our elevation data is only accurate to around 1m (or more) so storing as 10mm uses a lot of space.
Creates a 1M LERC MaxZError overview configuration

feat(cogify): add 1m preset

---

packages/config-loader/src/json/json.config.ts

Nontileed tiffs were being considered empty
allows non tilled tiffs to be imported.

fix(config-loader): do not assumed nontiled tiffs are empty

---

packages/cogify/src/bin.ts
packages/config-loader/src/json/json.config.ts
packages/shared/src/file.system.ts

Reduce the memory usage and number of requests made when loading tiff information from 10,000s of tiffs
removes the tiff caching/chunking logic from cogify and reduces the number of reuqests needed to check if a tiff is empty.

fix(cogify): remove tiff caching while creating tile covering

---

packages/cogify/src/cogify/cli/cli.config.ts

The new fsa from chunkd is not gzipping file based on the extension, we need to gzip file before uploading.
fix the places that upload gz files.

fix(cli): gzip the config before uploading to s3.

---

packages/cogify/src/cogify/cli/cli.cog.ts

Cog creation got a type error when asset is not defined for invalid cog. 
```
"type":"TypeError","message":"Cannot read properties of undefined (reading 'href')"
```
Log "null" when type is not defined.

fix(cogify): Fix the broken log for invalid cog with no assets defined.

---

packages/landing/src/components/map.tsx

the scale control does not function correctly in NZTM so to disable the control.
Disables the scale control when the tile matrix is not Google (3857)

fix(landing): disable scale control for NZTM as it is wrong BM-394

---

packages/config/src/config/tile.set.ts
packages/config/src/index.ts
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/__test__/validate.test.ts
packages/lambda-tiler/src/util/validate.ts

when rendering more complex raster data types there needs to be a configuration on how to convert the source raster images into a RGBA output to be consumed. This is needed so that DEM and DSM can be configured into TerrainRGB and other formats such as color ramps.
Allows configuration of how output tiles are created on a per tileset basis

feat: allow configuration of output tile types base of tileset configuration BM-932

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/parse.tile.set.ts
packages/config-loader/src/json/tiff.config.ts
packages/config/src/memory/memory.config.ts
packages/geo/src/formats.ts
packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/__tests__/wmts.capability.test.ts
packages/lambda-tiler/src/cli/render.preview.ts
packages/lambda-tiler/src/cli/render.tile.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/health.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/routes/tile.xyz.vector.ts
packages/lambda-tiler/src/util/__test__/validate.test.ts
packages/landing/src/url.ts
packages/tiler-sharp/src/__tests__/tile.benchmark.ts
packages/tiler-sharp/src/__tests__/tile.creation.test.ts
packages/tiler-sharp/src/index.ts
packages/tiler/src/raster.ts

Enum types causes issues with future eslint rules we want to introduce its easier to just remove the types.
Removes ImageFormat and VectorFormat enums and replaces them with string types.

fix!: remove ImageFormat and VectorFormat due to linting errors

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/tiff.config.ts
packages/config/src/config/tile.set.ts
packages/config/src/memory/memory.config.ts
packages/geo/src/formats.ts
packages/geo/src/index.ts
packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/routes/__tests__/attribution.test.ts
packages/lambda-tiler/src/routes/tile.json.ts

Format was meant to be used to allow imagery configuration to specify the output configuration, this has been superceeded by "outputs" and was never actually used.
Removes "format" from imagery configuration

feat(config)!: remove unused format tag

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/tiff.config.ts

some tiffs are getting closed via the garbage collector rather than safely using `.close()
Ensures that when tiffs are created the are closed cleanly.

fix(config-loader): close tiffs rather than letting the gc close them

---

package-lock.json
packages/config-loader/src/json/__tests__/tiff.config.test.ts
packages/config-loader/src/json/tiff.config.ts
packages/config/src/config/tile.set.ts
packages/config/src/memory/memory.config.ts
packages/lambda-tiler/scripts/create.deployment.package.mjs
packages/lambda-tiler/src/cli/render.preview.ts
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/validate.ts
packages/tiler-sharp/package.json
packages/tiler-sharp/src/__tests__/tile.benchmark.ts
packages/tiler-sharp/src/__tests__/tile.creation.test.ts
packages/tiler-sharp/src/index.ts
packages/tiler-sharp/src/pipeline/decompressor.lerc.ts
packages/tiler-sharp/src/pipeline/decompressor.ts
packages/tiler-sharp/src/pipeline/pipeline.color.ramp.ts
packages/tiler-sharp/src/pipeline/pipelines.ts
packages/tiler/src/raster.ts

To allow more complex dynamic rendering options, We need a way to specifiy a pipeline full of processing steps to be run on the raw imagery to create a 4 band RGBA output.
Adds a pipeline to imagery rendering 

feat(tiler)!: support custom raster processing pipelines'

---

packages/tiler-sharp/src/pipeline/decompressor.lerc.ts
packages/tiler-sharp/src/pipeline/pipeline.color.ramp.ts

We currently only have and expect float32 Lerc files, so lets error if we get something different.
Dissallows anything other than float32 for lerc

fix: only allow f32 lerc

---

packages/tiler-sharp/src/pipeline/__tests__/terrain.rgb.test.ts
packages/tiler-sharp/src/pipeline/pipeline.terrain.rgb.ts
packages/tiler-sharp/src/pipeline/pipelines.ts

Terrain RGB is a common format for sharing tiled elevation services,
for some rough performance numbers,
TerrainRGB encoding for common tile sizes:
```
256x256 - 2ms
512x512 - 5ms
```
Both lossless webp and png can be used, however lossless webp is much slower to compress
```
webp  14KB  100ms
png   28KB  5ms
```
adds support for float32 datasets to be converted on the fly to TerrainRGB

feat(tiler-sharp): add terrain-rgb pipeline

---

docs/operator-guide/gebco.md

We need process gebco data into basemaps once a year once gebco get new updates. But there is a bug in cogify (BM-935) when deal with NZTM2000Quad on Wsg84 source within the whole world scale, as the out put extent is not clipped as expected multi-polygons. 
This bug is only happens when the source file is too large that crossing the whole world, and existing the logic is very complex, so if trying to fix it might have a high risk to broke some existing process. As a result, we decide to using gdal to reproject he gebco into 2193 before using cogify importing the data. 
This PR contains the documents of dgal commands that using to re-project gebco data.
Add docs for the gdal commands.

docs: Document the gdal command to re-project gebco into 2193.

---

packages/config-loader/src/json/tiff.config.ts
packages/config/src/config/tile.set.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/server/src/config.ts
packages/tiler-sharp/src/index.ts

TerrainRGB needs to be lossless compressed, this adds the abilities for pipelines to customise how they create the output eg resizeKernels and lossless parameters
allows outputs to define resize kernels

feat(tiler-sharp): allow outputs to customise how output is compressed

---

packages/_infra/src/edge/index.ts
packages/config-loader/src/json/tiff.config.ts
packages/config/src/config/tile.set.output.ts
packages/config/src/config/tile.set.ts
packages/config/src/index.ts
packages/config/src/memory/memory.config.ts
packages/lambda-tiler/src/cli/render.preview.ts
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/validate.ts
packages/landing/src/url.ts
packages/server/src/route.layers.ts
packages/shared/src/imagery.url.ts

inline parameters in the  URL were hard to parse and did not allow for future expansion of pipeline configuration, by moving to a query parameter the pipline can be configured easier and has opportunities for expansion later.
switches from a inline url to a query parameter for pipline selection

feat: move to query parameters for pipeline selection

---

packages/landing/static/examples/index.maplibre.elevation.html

To give users a idea of how to interact with elevation services, add a example of using terrain-rgb to create a hillshade and 3d map view in maplibre
adds a maplibre 3d/hillshade example.

feat(landing): add example of maplibre elevation with terrain-rgb

---

packages/smoke/src/base.ts
packages/smoke/src/fonts.ts
packages/smoke/src/tile.test.ts

To be more confident the deployed system is working as expected expand the smoke test coverage
add a few smoke tests to validate tiles are rendered and returned.

feat(smoke): add tests to validate tiles are served BM-975

---

packages/shared/src/file.system.ts

Allow basemaps to access data from nz-elevation bucket.

feat(shared): Allow access to s3 nz-elevation public bucket.

---

packages/shared/src/file.system.ts

We want to read some file from basemaps-config repo in order to make smoke test. Http access are required first.

feat(shared): Allow basemaps file systemt to access http files.

---

packages/lambda-tiler/package.json

Fixes:
> (Error: ENOENT: no such file or directory, open '/var/task/lerc-wasm.wasm')
LERC needs to be next to where the lerc-wasm.wasm file is located by bundling the lerc file it breaks the path for lerc.

fix(lambda-tiler): lerc needs to be external to allow wasm import

---

packages/config-loader/src/json/__tests__/config.loader.test.ts
packages/config-loader/src/json/__tests__/tiff.config.test.ts
packages/config-loader/src/json/tiff.config.ts
packages/config/src/config/imagery.ts
packages/config/src/index.ts

We only care about names of bands, using common names as `float32` or `uint8` is more common in this codebase
Moves from a complex object for band type to just the datatype.
```
const band = { type: 'uint', bits: 8 } 
// to
const band = 'uint8'
```

feat(config): use shorter band names for band information

---

packages/cli/src/cli/config/action.bundle.ts
packages/cogify/src/cogify/cli/cli.config.ts
packages/config-loader/src/json/__tests__/tiff.load.test.ts
packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/tiff.config.ts
packages/server/src/config.ts

Basemaps Server and Basemaps Config importer were using two seperate configuration loading paths when reading metadata from tiff source files.
This greatly increases the number of requests needed to load configuration from tiff files, a caching layer will need to be added later.
Use the same code path between server and config bundling when reading metadata about tiff files.

feat(config): use the same config loader for server and cli

---

packages/cli/src/cli/config/action.bundle.ts
packages/cogify/src/cogify/cli/cli.config.ts
packages/config-loader/src/json/__tests__/tiff.load.test.ts
packages/config-loader/src/json/imagery.config.cache.ts
packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/tiff.config.ts
packages/server/src/cli.ts
packages/server/src/config.ts

When loading config from tiff files we open every tiff to validate that is in a format that basemaps can read, this can take a long time for large datasets
Adding a `--cache s3://config-cache/` to commands will cache the config for reuse in these locations which greatly reduces the number of files needed to be read to load a config
Adds a configuration cache that can be specified by the user to cache imagery config loading.

feat(config-loader): cache imagery configs to speed up loading times

---

packages/lambda-tiler/src/cli/render.tile.ts
packages/lambda-tiler/src/routes/preview.ts
packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/landing/src/components/map.tsx
packages/shared/src/file.system.ts
packages/tiler-sharp/src/index.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

Resizing/resmapling after the pipelines are applied is very wasteful as we apply a pipeline then only use a very low percentage of data.
Adds a direct resize/resample on the input data rather than resampling the output.

feat(tiler-sharp): directly resize/resample DEM inputs rather than RGBA outputs

---

packages/tiler-sharp/src/__tests__/tile.creation.test.ts
packages/tiler-sharp/src/index.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts
packages/tiler/src/__tests__/tiler.test.ts
packages/tiler/src/raster.ts
packages/tiler/src/tiler.ts

Nearest neighbor while really fast doesn't give the best visual output for most of our usecases
switch to bilinear resampling by default.

feat(tiler): add bilinear resampler for DEM/DSM

---

packages/config/src/config/tile.set.output.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts

NO_DATA value needs to be set in the output of resizing otherwise a value of 0 is assumed.
Set NO_DATA if it is encountered while resizing.

fix(tiler-sharp): resampling should set no-data

---

packages/tiler-sharp/src/pipeline/pipeline.resize.ts

When cropping images bilinear resampling is currently applied, this does not need to happen as it should just be a one to one copy of the data
Directly crops a image using sub array slices.

fix(tiler-sharp): do not resample if its not needed

---

packages/server/src/server.ts
packages/shared/src/file.system.ts

We have buckets in multiple regions, when requesting data using the default client it will throw a 301 moved error rather than fetching the data from the bucket.
If we know the region ahead of time we should create new s3 clients for those regions to save the request -> failure -> retry flow.
Retry bucket reads when reading across region

fix(shared): allow reading of buckets from other regions

---

packages/smoke/src/index.test.ts

the index.html preview generation was broken due to a weirdness with cross region buckets
this was not picked up by unit tests
Validate that the preview cards are being added to the index.html.

feat(smoke): smoke test preview index.html generation

---

packages/cli/src/cli/config/action.bundle.assets.ts

The bundle asset got broken after update to URL type of paths. The removing leading "/" shouldn't remove it if no leading "/", and the output font paths should be decoded from URL to remain the same as existing version.
I have uploaded some example screenshot of comparing prod and broken asset files.
- Check leading slash before removing, leading slash can be introduced if the input asset location doesn't have slash at end.
- decode the file path from url

fix(cli): Fix the bundling asset that remove extra letter at path and decode font paths.

---

packages/geo/src/__tests__/slug.test.ts
packages/geo/src/slug.ts

We need to truncate the bearing and pitch in url which stay the same as maplibre. 1dp for bearing and 0dp for pitch
Update the `fromSlug` function to include the truncate bearing and pitch output in string.

feat(geo): Truncate bearing and pitch values in url.

---

packages/geo/src/slug.ts
packages/lambda-tiler/src/routes/__tests__/preview.index.test.ts
packages/lambda-tiler/src/routes/preview.index.ts
packages/lambda-tiler/src/routes/preview.ts
packages/server/src/route.layers.ts
packages/shared/src/imagery.url.ts
packages/shared/src/index.ts

We need preview URLS so that we can display a list of DEM layers in the layer viewer
Adds support for pipelines for preview url generation when viewing the landing page.

feat(lambda-tiler): show the first pipeline as the preview instead of a broken image

---

packages/cogify/src/cogify/cli.ts
packages/cogify/src/cogify/cli/cli.cog.ts
packages/cogify/src/cogify/cli/cli.validate.ts
packages/cogify/src/cogify/gdal.command.ts
packages/cogify/src/cogify/gdal.runner.ts
packages/cogify/src/cogify/stac.ts
packages/cogify/src/preset.ts

Baseamps generally uses three GDAL commands to convert imagery/DEM/DSMs into COGS
build a VRT
`gdalbuildvrt tiffs.vrt *.tiff`
Apply cutline and warp
`gdalwarp -of vrt warped.vrt tiffs.vrt -wo ... `
Convert the warped to a COG
`gdal_translate -of COG warped.vrt`
When reprojecting we often change the resolution of a TIFF to better align with the desired output tile matrix this is done with a `-tr` inside the `gdal_translate` step.
We have found that with just a single `-tr` in the `gdal_translate` it leads to suboptimal COG creation with artifacts.
adding another `-tr` to the warp resolves the issue.
- Adds `-tr` to the gdalwarp to fix some rendering issues
- Adds a `cogify validate` to validate tiffs are what basemaps is expecting.
- 

fix(cogify): improve DEM quality when reprojecting and scaling BM-987

---

packages/cogify/src/cogify/cli/cli.config.ts
packages/cogify/src/cogify/gdal.runner.ts

some log keys are duplicated causing indexing exceptions in elasticsearch
renamed a couple of conflicting log keys.

fix(cogify): log key collisions

---

packages/landing/src/components/debug.tsx

Debug page flashes on and off when panning around the map
adding and removing layers causes maplibre to redraw the layer, we should only remove layers if we need to.

fix(landing): do not remove and re-add the same layers

---

packages/landing/src/components/debug.tsx

When viewing terrain in NZTM the terrain is too flat, this is caused by the NZTM projection hacks to allow Maplibre to render NZTM, it offsets the zoom level by 2 which means everything is approx 4x smaller.
When viewing in NZTM set the terrain to be approx 4x higher than what we use in 3857.

feat(landing): exaggerate the terrain when viewing in NZTM BM-983

---

packages/lambda-tiler/src/routes/preview.ts
packages/server/src/route.layers.ts

Previews for RGBA datasets are currently broken as the decompressor does not know how to decompress 4 band RGBA
Only use the pipeline decompressor if a pipeline is defined.

fix(lambda-tiler): only use a compose pipeline if a pipeline is defined

---

packages/lambda-analytics/src/__tests__/file.process.test.ts
packages/lambda-analytics/src/file.process.ts
packages/lambda-analytics/src/stats.ts

Tracking what is being rendered is quite helpful to know what is useful to people, we are not currently tracking if a tile is a terrain-rgb or color-ramp
Add extra stats about terrain-rgb vs color-ramp vs rgba outputs.

feat(lambda-analytics): track pipeline usage BM-964

---

packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/smoke/src/tile.test.ts

.jpg is currently throwing a error , we should allow .jpg tiles
> Error: Invalid image format "jpg"
allow jpg as a valid extension

fix(lambda-tiler): allow .jpg for jpeg images

---

packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/smoke/src/tile.test.ts

image/jpeg is the correct mime type for jpeg images, 
converts image/jpg into image/jpeg when users request '.jpg' tiles.

fix(lambda-tiler): content type for jpg should be image/jpeg

---

packages/cli/src/cli/config/action.import.ts

Out config import are broken when prepare changes for individual vector tileset.
Remove the hard coded topographic logic and update to support all vector tilset inside changes.

fix(cli): Fix config import to prepare changes for individual vector config.

---

packages/cli/src/cli/config/action.import.ts
packages/cli/src/cli/config/config.diff.ts

The current gh comment for config changes looks not very good. Need to update it clearer to read.

feat(cli): Update the changed format looks nicer in the github comment

---

packages/landing/src/components/map.tsx

`ScaleControl` can't be removed for NZTM200Quad projection which broken the layer dropdown in nztm200quad.
- set `controlScale` to null after remove.

fix(landing): Fix the ensure scalecontrol for the NZTM2000quad projection. BM-1004

---

packages/cli/src/cli/config/config.diff.ts

The check vector update output is not working as expected, and take everything as new inserts.
- Fix it as it didn't take the existing one into comparison.

fix(cli): Fix the check vector diff outputs. BM-1013

---

package-lock.json
packages/cli/Dockerfile
packages/smoke/package.json
packages/smoke/src/base.ts

A configuration change in https://github.com/linz/basemaps-config broke the smoke check tests, It would be nice to run the smoke checker on config changes before deploying them.
Exposes the smoke checker as a package inside the basemaps/cli container so it can be used by https://github.com/linz/basemaps-config

feat(cli): expose the smoke checker in the CLI container so linz/basemaps-config can use it BM-1010

---

packages/lambda-tiler/src/__tests__/wmts.capability.test.ts
packages/lambda-tiler/src/wmts.capability.ts
packages/smoke/src/base.ts
packages/smoke/src/wmts.test.ts

As we recently changed the basemaps configuration to use the raw tiff values for extent rather than the name of the tile, the extents of each layer has slightly changed.
This works for most layers except ones which cover the entire world, for example `0-0-0.tiff` this can lead to slight floating point errors in the extents between the TileMatrix and the tiff.
If the imagery extent is outside the bounds of the tile matrix fall back to the extent of the tile matrix.

fix(lambda-tiler): ensure wmts limits extent to the bounding box of the tile matrix extent BM-1012

---

package-lock.json
packages/_infra/package.json
packages/_infra/src/config.ts
packages/_infra/src/index.ts

Common CICD tags helps us understand how resources are managed inside our AWS accounts
see https://github.com/linz/cdk-tag for more information on the tags created.
Applies common github CICD tags to all basemaps resources. 

feat: apply common aws cicd tags across basemaps infra

---

packages/cogify/src/bin.ts
packages/shared/src/__tests__/fqdn.test.ts
packages/shared/src/file.system.middleware.ts
packages/shared/src/file.system.ts
packages/shared/src/index.ts

In our kubernetes cluster we are seeing perodic DNS resolution failures, 
see https://github.com/linz/argo-tasks/pull/940 for more information
force FQDN to be used for S3 requests when using cogify 
Should, lambda-tiler also use FQDNs ?

feat(cogify): force fully qualified domain names for s3 to reduce DNS load TDE-1084

---

packages/landing/src/components/debug.tsx

It would be helpful to view a DEM/DSM as just the hillshade, can we turn off the color-ramp and terrain-rgb visualisations with a “layer: off”? 
Add a off option after the sourceIds, which make it not as default.

feat(landing): Add off for the dem/dsm layer dropdown in debug page. BM-1019

---

packages/landing/src/components/debug.tsx
packages/landing/src/config.map.ts

Outputs layers not showing up when using the `i` query parameter to viewing elevations data. Cause the `Config.map.styleId` will return the empty styleId. 
- Using layerId when `style` query parameter not specified. 
- Showing 'off' when there is no selectedSrouce for the layer dropdown.

fix(landing): ensure the layer dropdown always showing for all outputs. BM-1001

---

packages/landing/src/config.map.ts

We are able to get individual imagery by the `?style=` request parameter only, but this will not populate to the related virtual tilesetId and set default as `ts_aerial`. 
- We can set `layerId` as style id first before set as default `aerial`.

fix(landing): Fix the set the tileset id same as style when only style parameter been set.

---

package-lock.json
packages/smoke/package.json

Smoke test should be able to running in the cli container, but it is missing the ulid depenency.
Install ulid for smoke

fix(smoke): Smoke test is missing ulid dependency to running inside the container.

---

.github/workflows/containers.yml
packages/cli/Dockerfile

Running smoke test inside basemaps container missing static files for health endpoint test.
Copy the static files into basemaps container.

fix(cli): Copy static files into cli container for health smoke test.

---

packages/shared/src/dynamo/dynamo.config.ts

Dynamo is sometimes erroring with throttling exception, we currently have retries set at 3 retires
```
stack: ThrottlingException: Throughput exceeds the current capacity of your table or index. 
DynamoDB is automatically scaling your table or index so please try again shortly.
If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html
at qke (/var/task/index.js:20:5520)
````
Increase the retry count to 5, so that it retries more before erroring.

fix(shared): retry dynamodb queries more times BM-1008

---

packages/tiler-sharp/src/pipeline/__tests__/terrain.rgb.test.ts
packages/tiler-sharp/src/pipeline/pipeline.terrain.rgb.ts

Very small height values are overflowing terrain rgb, eg the Mariana trench which cause rendering artifacts.
clamps the values of terrain rgb to the possible pixel ranges (0,0,0 -> 255,255,255)

fix(tiler-sharp): clamp elevation to the bounds of terrain rgb BM-1028

---

packages/cogify/src/preset.ts

After testing with different config, we decide to use 1cm/2cm on the lerc config.
- Update existing 1mm/10mm lerc config

feat(cogify): Update the configs for lerc presets to include 1cm/2cm lerc. BM-1035

---

packages/tiler-sharp/src/index.ts
packages/tiler-sharp/src/pipeline/__tests__/terrain.rgb.test.ts
packages/tiler-sharp/src/pipeline/decompressor.ts
packages/tiler-sharp/src/pipeline/pipeline.color.ramp.ts
packages/tiler-sharp/src/pipeline/pipeline.terrain.rgb.ts

Terrain RGB tiles can be quite large at low (z0-z10) zoom levels the blue channel of the terrainRGB represents around 25M of vertical accuracy, when viewing tiles where 1 pixel is 1,000m sub meter accurarcy is not required.
from initial test cases this can reude the tile size by 50%+ 
tile z_x_y | Before | After | Bytes saved | % reduction
-- | -- | -- | -- | --
03_7_4 | 3,607 | 2,737 | -870 | -24.12%
04_15_9 | 7,802 | 4,305 | -3,497 | -44.82%
05_31_19 | 23,031 | 8,872 | -14,159 | -61.48%
06_63_39 | 64,024 | 23,827 | -40,197 | -62.78%
07_126_79 | 110,251 | 45,738 | -64,513 | -58.51%
08_252_159 | 66,791 | 28,809 | -37,982 | -56.87%
09_505_319 | 125,658 | 64,711 | -60,947 | -48.50%
10_1010_639 | 143,054 | 91,446 | -51,608 | -36.08%
11_2020_1278 | 98,940 | 62,342 | -36,598 | -36.99% …

feat(tiler-sharp): reducde the z precision of terrain-rgb to generate much smaller tiles for low z levels BM-1002

---

packages/cogify/src/cogify/__test__/covering.test.ts
packages/cogify/src/cogify/cli/cli.cover.ts

The nz-elevation stac imagery name doesn't include the `dem_1m` prefix. We need to add it into basemaps imagery name and s3 path
Find the prefix from the nz-elevation source, and update the imageryName

fix(cogify): Fix the elevation target path to include dem/dsm. BM-1040

---

packages/landing/src/components/map.tsx

Now that the elevation terrain rgb service is live add a elevation toggle to the landing page.
Adds the maplibre elevation control onto the landing page

feat: add elevation control to landing page BM-993

---

packages/lambda-tiler/src/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

We should allow url configurable tileMatrix in the styleJson source instead hard coded. So we can create raster style config for different tileMarix in basemaps-config.
- Only replace if {tileMarix} exists in the source url, so this won't broken any existing configs.

feat(lambda-tiler): Update the tileMatrix from stylejson source if exists.

---

packages/lambda-tiler/src/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

We should remove metadata, sprite, glphys if not defined from style config. empty sprite or glphys will broken the maplire.
```json
{
"version": 8,
"id": "st_aerial",
"name": "aerial",
"sources": {
"basemaps-aerial": {
"tileSize": 256,
"tiles": [
"[https://dev.basemaps.linz.govt.nz/v1/tiles/aerial/WebMercatorQuad/{z}/{x}/{y}.webp?api=c01hzzbj62y83k27kw7pd89jsw1&config=TmVmbYRQjL9T2JWgyaSie193b4D1qZnBD8hjaSqPFYSsEvEYYhaGYKrcnYE9V7NUW5A8WmuM3FpWejcebdKmVDGzTMLXbMvmCSs2XouTFdCmeHCAfTLyzMmr3YxANL1"
],
"type": "raster"
},
"basemaps-terrian": {
"tileSize": 256,
"tiles": [
"https://dev.basemaps.linz.govt.nz/v1/tiles/elevation/WebMercatorQuad/{z}/{x}/{y}.png?api=c01hzzbj62y83k27kw7pd89jsw1&config=TmVmbYRQjL9T2JWgyaSie193b4D1qZnBD8hjaSqPFYSsEvEYYhaGYKrcnYE9V7NUW5A8WmuM3FpWejcebdKmVDGzTMLXbMvmCSs2Xo …
```

fix(lambda-tiler): Remove the stylejson metadata, sprite, glphys if no required.

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/src/config.map.ts

The elevation layer is a special case as its not really usable as a standard baselayer with out a pipeline to tell the renderer how to render it, 
Adds the terrain layer with a pipeline defaulted to terrain-rgb

feat(landing): add elevation terrain-rgb to layer drop down BM-993

---

packages/geo/src/__tests__/slug.test.ts
packages/geo/src/slug.ts
packages/landing/src/components/map.tsx

Allows users to see more of the horizon by upping the maxPitch from 60 to 80
sets the maxPitch to 80 degrees, this is somewhat experimental 

feat(landing): allow more tilting so users can see more of the horizon BM-993

---

packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

We want the individual raster tileset to include elevation terrain source if there is on exists in the config.
Add default terrain raster-dem source for `tileSetToStyle`.

feat(lambda-tile): Enable elevation source in the individual raster style json.

---

packages/config-loader/src/json/__tests__/tiff.load.test.ts
packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/parse.tile.set.ts

Allows configuration objects to use colors as `{r: 255, g: 255, b:255, alpha: 255}` as well as  `#ff00ffff`
parse background colors as rgba hex strings or objects

fix(config-loader): allow rgb color objects

---

packages/lambda-tiler/src/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

Invalid tile matrix to tile set relationship is a configuration problem and should not be a 500 error
swaps the 500 response to 400.

fix(lambda-tiler): tile matrix not supported is a 400 not 500

---

packages/config-loader/src/json/__tests__/tiff.load.test.ts
packages/config-loader/src/json/tiff.config.ts

The tiff tag SampleFormat is optional and should be treated as a uint if not found
ref: https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html
> A reader would typically treat an image with undefined data as if the field were not present (i.e. as unsigned integer data).
Assume sample format is a uint when SampleFormat is not defined.

fix(config-loader): data type is optional for tiffs

---

.github/workflows/screenshot.yml

3D map screenshots is currently not stable, we want to enable it after fixed. So we lock the screenshot cli back to v1.5 now.
- Lock screenshot cli to [v1.5
](https://github.com/linz/basemaps-screenshot/commit/f4071b205a16325957280b56138c20b0d7bef13f)

ci: Lock the screenshot version to v1.5 to excludes the 3d map tests.

---

packages/landing/static/examples/index.html
packages/landing/static/examples/index.maplibre.elevation.3857.html

The elevation example already existed but the colors were slightly too light,
Add the elevation example to the examples index, and darken the hill shade
before:
after:

feat(landing): add elevation example

---

package-lock.json
packages/cogify/package.json
packages/cogify/src/cogify/cli/cli.cover.ts
packages/cogify/src/preset.ts
packages/cogify/src/tile.cover.ts

for some datasets we are overzooming them by a signficiant amount to align them to a output tile matrix zoom level.
For example a 1M DEM will be overzoomed to z18 0.59m, z17 is 1.19M it is closer to the 1M but is slightly lower quality.
By adding `--base-zoom-offset=-1` we can force cogify to underzoom some datasets where to save storage space.
This can also be used with more zoom offsets to create signficantly smaller output files for a sample dataset `whanganui_2022_0.075m` which by default creats 20GB of COGs at z21.
By using `-3` or `-4` can greatly reduce the size of the dataset
```
114M    z17_whanganui_2022_0.075m (-4)
477M    z18_whanganui_2022_0.075m (-3)
```
Reducing Webp quality from 90% to 80% quality can additionally reduce the output file size even further. ~200MB for z18. …

feat(cogify): set zoom offsets for cogify to create smaller output files

---

packages/cogify/package.json

the latest container is currently broken when looking for `cogify` as it is pointing to a file that doesnt exist `./dist/index.cjs`.
The dist/index.cjs is only created after a `npm run bundle` but bundle is not run until after cogify is published to npm.
force dist/index.cjs to be created before a `npm pack` can be run using the prepack npm lifecylce event.
manually rebuilt with `npm pack` to ensure that a dist/index.cjs exists

fix(cogify): correct loading path for "cogify" bin

---

packages/cogify/src/cogify/cli/__test__/cli.cover.test.ts
packages/cogify/src/cogify/cli/cli.cover.ts

When importing imagery into basemaps we know if there is a source stac collection at the first step, but we only warn that we cannot find it.
In most of our import processes not having a stac collection should be a errro
Add `--require-stac-collection` to throw a error if a stac collection cannot be found when createing a cover
Added new integration test to covering creation with and without the new flag.

feat(cogify): error early if no source collection.json is found BM-1047

---

packages/_infra/src/edge/index.ts
packages/config/src/config/vector.style.ts
packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/landing/src/components/map.tsx
packages/landing/src/config.map.ts
packages/landing/src/tile.matrix.ts
packages/landing/src/url.ts

We want a terrain request parameter that shareable for map with 3d terrain enabled. This will need new aerial style config to added after merge. https://github.com/linz/basemaps-config/pull/916
- Add terrain setting in `getStyle` api when `?terrain=LINZ-Terrain`
- Update landing page to lisen the terrain event to set terrain parameter.
- Unit tests added for tileset to style and style to style in getStyle Api
- Landing page tested with terrain button to update the request parameter.

feat(landing): Add terrain parameter in the url

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/src/components/map.tsx
packages/landing/src/config.map.ts
packages/landing/src/url.ts

When copying XYZ terrain-rgb links, only lossless formats (PNG) are supported by default all links are webp.
Force PNG for XYZ and WMTS terrain-rgb links
Tested in local debug mode.

fix(landing): use png for terrain-rgb xyz links BM-1041

---

packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

We need to ensure a terrain source in all style json configs before the production release. Then we could do another config release for add terrain source into style config. https://github.com/linz/basemaps-config/pull/916
Check and add terrain source for get style config api.

feat(lambda-tiler): Ensure terrain source for all style json configs.

---

packages/_infra/src/analytics/edge.analytics.ts

Buckets should have BlockPublicAccess set to BlockAll by default
Force the analytic cachcing bucket to have the flag set

fix(infra): force block public access on s3 buckets TDE-1207

---

packages/landing/src/url.ts

Due to a typo in the comparision all layers were getting ?format= appended, only WMTs needs it.
Force PNG `tileFormat` format WMTS links with terrain-rgb

fix(landing): only force wmts to have tileFormat BM-1041

---

packages/lambda-tiler/src/routes/tile.style.json.ts

Ensure terrain for the tileset that have outputs
Add terrain source for `tileSetOutputToStyle`.

fix(lambda-tiler): Fix the missing LINZ-terrain source for the elevation layer.

---

package-lock.json
packages/landing/package.json

Upgrade maplibre to latest version, so we can have sky box support. https://github.com/maplibre/maplibre-gl-js/pull/3645

build: Upgrade the maplibre to v4.5

---

packages/lambda-tiler/src/routes/__tests__/wmts.test.ts
packages/lambda-tiler/src/routes/tile.wmts.ts
packages/lambda-tiler/src/wmts.capability.ts

When viewing elevation via WMTS you need to supply a terrain-rgb pipeline
adds a default pipeline to wmts outputs if requested
Removes unused filter logic

fix(lambda-tiler): wmts should support tile pipelines

---

packages/landing/src/components/debug.tsx
packages/landing/src/config.debug.ts
packages/landing/src/debug.map.ts
packages/landing/src/tile.matrix.ts

Load capture-area.json into the debug checkbox if exist, and make it easier to download for imagery data managers to use.
Add new checkbox for capture area and show a doubled line the polygon on the map.

feat(landing): Add capture area into debug page. BM-1048

---

packages/landing/src/components/debug.tsx

We need to disable the checkbox if capture-area.geojson not exist or can't be loaded as source.
Use same way to disable it as cog checkbox.

feat(landing): Disable capture area checkbox if capture-area.geojson not exists.

---

packages/landing/src/url.ts

Debug page cog and capture-area checkbox should get the geojson file from target config parameter. 
This will fix the problem of not found gejson file with a config paramemeter

fix(landing): Need to pass config parameter into imagery api

---

packages/config-loader/src/json/parse.style.ts
packages/config/src/config/vector.style.ts
packages/lambda-tiler/src/routes/tile.style.json.ts

Update the config style parser and loader to include sky in the stylejson.
Add sky type into stylejson

feat(config): Update the config to support sky in the style json. BM-1052

---

packages/lambda-tiler/src/routes/__tests__/imagery.test.ts
packages/lambda-tiler/src/routes/imagery.ts

Currently geojson files are generally just shown to the user when clicked from inside a browser most of our usecases want these files locally so it would be preferred if they download
Force download all imagery geojson files using content-disposition

fix(lambda-tiler): prefer geojson files to be downloaded  BM-1048

---

.github/workflows/screenshot.yml
packages/config/src/config/vector.style.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/landing/src/components/debug.tsx
packages/landing/src/components/map.tsx
packages/landing/src/config.debug.ts

We have default LINZ-Terrain source been added for all styleJson, this could be added into terrain drop down as well.
Also, we should support terrain for NZTM2000Quad tileMatrix
- Filter LINZ-Terrain into the terrain and hillshade dropdown
- Enable terrain controle and set terrain exaggeration with 4.4 for NZTM

fix(landing): Support Terrain for NZTM and add default LINZ-Terrain into debug

---

packages/shared/src/__tests__/api.test.ts
packages/shared/src/api.ts

The expiring 90 day keys are causing issues for GIS users, as their tools generally just dont show any errors the layers just don't show up, which makes it very difficult for them to know why they are not seeing aerial imagery.
allow consumer keys to last for ever
unit tests passing

feat(shared): allow old api keys BM-1057

---

package-lock.json
packages/_infra/package.json
packages/_infra/src/index.ts

To better monitor the basemaps service a responder team needs to be set so that others inside LINZ know who to contact if something goes wrong.
Sets the responder team to "LINZ - Basemaps"

feat(infra): add responder team tag

---

packages/landing/src/components/debug.tsx
packages/landing/src/config.map.ts

We want debug page to view terrain for individual config files that doesn't have elevation tileset inside. Using the same logic of linz-aerial slider and get the elevation data from the production or dev config based on the host.
Add a new LINZ-Terrain-Prod source layer in the terrain and hillshade dropdown that points to the basemaps production data for debugging.

feat(landing): Add LINZ-Terrain-Prod for debug 3d map with production elevation data. BM-1058

---

packages/landing/src/components/debug.tsx

Source id tracking logic was broken in commit 07b8aebd6dbc25045647739999f2d3e5f2602106 with https://github.com/linz/basemaps/commit/07b8aebd6dbc25045647739999f2d3e5f2602106#diff-935afb39a4daeb9c30850cda3e20eecf1fb8f5086b9172fef9a5e8539e5e99f5R529
return the state name back to `featureSource` and `featureCog`
Tested locally hover is now working as expected.

fix(landing): put back the sourceId tracking logic BM-1062

---

packages/landing/src/components/map.switcher.tsx

Landing page map switcher on the bottom left doesn't set the map location when bearing or pitch is 0.
The map switcher sets the bearing and pitch by the update location from config. But it is skip setting when pitch or bearing is null. We should also set to 0 if null.

fix(landing): Fix the map switcher that setting bearing and pitch to 0. BM-1063

---

.github/workflows/screenshot.yml
packages/landing/src/components/debug.tsx

We want to fix the 3d screenshots in PR.
- When setting 3d in screenshots, we want to force load config from url and wait for 2s.
- Updated to the latest screenshot cli which removes bearing and pitch to save computing.
- Only do 5 tests on 3d map screenshots to keep the workflow running around 4 mins.
- Stop showing `debug.terrain` and `debug.terrain` in url when it is `off`

ci: Enable 3d screenshots in the basemaps. BM-1054

---

packages/landing/src/url.ts

We got terrain request parameter been passed to xyz and wmts api which is confusing people and these api also not support terrain. So we should only limit the terrain to pass into get style json only.
Only add terrain for style url.
-- Removed from xyz and wmts
-- Only keep for style json url.

fix(landing): Only pass terrain request parameter to get style json api. BM-1068

---

packages/lambda-tiler/src/routes/tile.xyz.raster.ts
packages/lambda-tiler/src/util/__test__/cache.test.ts
packages/lambda-tiler/src/util/source.cache.ts

Fetching data from remote services can and will error on occasion, the promises to fetch data from tiffs has two `.then()` one of the `.then()` has a associated `.catch()` the other does not, this leads to a `UnhandledPromiseRejection` 
Do not use a `.then()` without `.catch()`
Unit test addded.
also checked the code base for more usages of `void ....then()` without .catch and they only occur in the landing page.

fix(lambda-tiler): prevent unhandled promise rejections when the rejection is handled BM-1067

---

packages/_infra/src/edge/index.ts
packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/landing/src/components/map.label.tsx
packages/landing/src/components/map.switcher.tsx
packages/landing/src/components/map.tsx
packages/landing/src/config.map.ts
packages/landing/src/tile.matrix.ts
packages/landing/src/url.ts
packages/landing/static/index.css

For additional context in aerial imagery its helpful to add vector layers such as placename and roads
Allow landing page to request a combined aerial and label style json
Add button to enable/disable showing of labels on aerial layer
Testing locally, but would be nice to test more in dev

feat(landing): show labels on landing page

---

packages/lambda-tiler/src/util/__test__/cache.test.ts
packages/lambda-tiler/src/util/source.cache.ts
packages/lambda-tiler/src/util/swapping.lru.ts

when requests fail, sometimes they can be retried later and succeed, right now we are caching the error state.
On error remove the cached tiff/tar from the cache
added unit tests.

fix(lambda-tiler): do not keep failed tiffs in memory

---

packages/shared/src/dynamo/__tests__/config.dynamo.test.ts
packages/shared/src/dynamo/dynamo.config.base.ts

all of our unit tests use the memory config provider which ensures the keys start with the correct prefix
In dynamodb configs force the prefix to be added if its not present.
updated unit tests

fix(shared): allow unprefixed query keys

---

packages/_infra/src/edge/index.ts

Deployments are currently failing due to a AWS limit of 10 cache keys per behaviour
Remove deprecated cache keys
Will see if it fixes the deployment

fix(infra): reduce cache keys below 10 to prevent deployment errors

---

packages/lambda-tiler/src/routes/tile.style.json.ts
packages/landing/src/components/map.label.tsx

It would be nice to know how people are asking for layers to be rendered with labels enabled
Track users clicking on labels
Track styleJsons being created with labels enabled
Will check google analytics after deployed.

feat(landing): track label button clicks BM-1066

---

packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/landing/src/components/map.label.tsx
packages/landing/src/url.ts

Joining layers with the labels can cause invaldi style jsons to be created, check that the layer ids do not overlap before joining.
Check all layers have unique layerIds before joining them together
unit tests.

fix(lambda-tiler): do not join layers where ids would be duplicated

---

packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/routes/tile.xyz.vector.ts

We now have a collection of vector tiles in NZTM2000Quad, it would be useful to allow the server to serve them.
The original logic was a saftey mechanisim to prevent 3857 tiles being served to NZTM2000Quad requests.
Remove NZTM2000Quad restrictions from vector tile endpoint
unit tests + manually tested with config https://github.com/linz/basemaps-config/pull/967

feat(lambda-tiler): remove restrictions on 3857 from vector tiles

---

packages/lambda-tiler/src/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/__tests__/tile.style.json.test.ts
packages/lambda-tiler/src/routes/tile.style.json.ts
packages/lambda-tiler/src/util/__test__/nztm.style.test.ts
packages/lambda-tiler/src/util/nztm.style.ts

NZTM2000Quad is offset by two zoom levels from web mercator quad, when the stylejsons are created for both projections the style json needs to adjust all the zoom levels by two
Convert styles zoom offsets automatically when asking for a NZTM2000Quad style json
updated comments across the style json endpoint
refactored the style generation into a single point.
unit tests

feat(lambda-tiler): automatically rescale style JSON's into NZTM2000Quad when requests

---

packages/linzjs-geojson/src/index.ts
packages/linzjs-geojson/src/util/__test__/iterate.test.ts
packages/linzjs-geojson/src/util/__test__/truncate.test.ts
packages/linzjs-geojson/src/util/iterate.ts
packages/linzjs-geojson/src/util/truncate.ts

We have had a need to reproject and truncate geojson objects and instead of copying the logic into multiple locations add it to the geojson helper we have here.
Add truncate to truncate lat lon pairs to by default 8 decimal places
Add iterate to iterate over all the points in a geojson feature
unit tests and is currently in use in other code bases.

feat(linzjs-geojson): add iterate and truncate utilities for geojson

---

packages/landing/src/components/map.label.tsx

the labels view requires the "labels" style to exist, this generally does not exist inside of custom configs.
Hide the label button when custom configs on the debug page.
Manually tested with current debug page.

fix(landing): hide label button on debug page as its broken BM-20

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/static/index.css

When browsing around the map the layers list is very long and its hard to know could be shown from the current view
Add a checkbox to limit the layer list by the approximate bounding box of the map.

feat(layer): add option to limit layer list by extent BM-883

---

packages/geo/src/stac/stac.attribution.ts
packages/lambda-tiler/src/routes/attribution.ts
packages/landing/src/attribution.ts
packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/src/config.map.ts
packages/landing/src/tile.matrix.ts
packages/landing/src/url.ts

The filter layer intersection logic is currently guessing the extent that the user is viewing
Store the extent that the user is looking at when the map pans
tested locally

feat(landing): store the maps bounds to provide a better bounding box intersection

---

packages/landing/src/components/layer.switcher.dropdown.tsx
packages/landing/src/config.map.ts

As a Basemaps user, I want the `Topolite` layer and the `Scanned Aerial Imagery Basemaps` category to appear at the top of the `Layers` dropdown for easier access.
1. Reordered the categories as they are shown in the `Layers` dropdown.
2. Added the `Topolite` layer to the list of default layers.
1. Moved the `Scanned Aerial Imagery Basemaps` category to the top of the `Layers` dropdown below the `Basemaps` category.
| Before | After |
| - | - |
| ![][img_1] | ![][img_2] |
[img_1]: https://github.com/user-attachments/assets/4a147b31-422e-4aff-927f-57ad76e18b64
[img_2]: https://github.com/user-attachments/assets/29dc0513-93aa-495d-b1aa-04dc8c69ead3
2. Added the `Topolite` layer to the list of default layers.
| Before | After |
| - | - |
| ![][img_3] | ![][img_4] |
[img_3]: …

feat(landing): adjust layers dropdown BM-1079

---

docs/quick-start.md

There was a broken link.
Removed a character so there is no longer a broken link.
N/A

docs: fix typo in quick-start.md

---

.github/workflows/containers.yml
packages/server/Dockerfile

Server container failed v1/health endpoint check because missing the static files from lambda-tiler.
Copy the file into the server container

fix(server): Copy the static health check files into server container

---

.github/workflows/containers.yml
packages/cli/Dockerfile

The [cli container](https://github.com/linz/basemaps-config/actions/runs/11096451992/job/30827033370?pr=984) requires lerc to be installed which come from server.
`
node:internal/modules/cjs/loader:1228
throw err;
^
Error: Cannot find module 'lerc'
Require stack:
- /app/index.cjs
at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
at Module._load (node:internal/modules/cjs/loader:1051:27)
at Module.require (node:internal/modules/cjs/loader:1311:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/app/index.cjs:190419:27)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load …

fix(cli): Install server package in the cli container to inlcude lerc.

---

packages/lambda-tiler/src/index.ts
packages/shared/src/file.system.ts
packages/shared/src/index.ts
packages/shared/src/log.ts

Requests tracing has been broken for a while (not entire sure when it broke)
It is very very helpful to have statistics on the number of s3 requests required to make a tile
- `requestCount` is reserved for the number of lambda invocations so move to `fetchCount` for number of fetches
- include the fetchIds to trace hot fetches
- increase the percent of requests with tracing enabled
- Use async local storage to gain access to the logger for the request that triggers the log message, this fixes a bug where the request may be in `trace` but the fetch is using the base logger which is set to `info` so no logs are generated.
Ran locally and verified logs are now appearing.

fix(lambda-tiler): correctly log fetch requests

---

packages/landing/src/components/debug.tsx

Debug.hillshade keep loading network because the skip check with un-prefix hillshade sourceId and get the hillshade layer been removed and added for every rendering. 
Correct the check sourceId with prefixed one.
Tested with locally build, was infinite loading before fix, and only load once after fix.

fix(landing): Fix debug hillshade infinite loading. BM-1110

---

package-lock.json
packages/_infra/package.json
packages/_infra/src/analytics/edge.analytics.ts
packages/_infra/src/serve/lambda.tiler.ts

since the end of 2023, lambda functions can now output JSON as their logging format, since all of our other logs are structured move to JSON logs for everything
Convert lambda functions to log as JSON
Need to verify everything is working correctly after deploy, eg alerts/log shipping

build: set lambda to log as JSON

---

packages/landing/src/components/feature.updates.tsx
packages/landing/src/components/new-features/3d.map.tsx

We want to capture the event of pop screenshot in google analyst, also try to enable the 3d map pop up for 3 months and see how it goes.
- Add gEvent for both open and close of 3d map pop up
- Set the end date to 31th Jan 2025

feat(landing): Update new feature pop ups to include google analytics. BM-1113

---

package-lock.json
packages/shared/package.json
packages/shared/src/file.system.ts

We have been seeing some tiff files intermitently fail to load when loading across AWS accounts, this was tracked down a failure to register a AWS roleArn against the target bucket when the roleArn was used in multiple different buckets
Use the more general "onFileSystemFound" as "onFileSystemCreated" only happens once per roleArn.
Tested locally

fix: register file systems correctly when using duplicate roleArns BM-1055

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/parse.tile.set.ts
packages/config/src/config/tile.set.ts
packages/tiler-sharp/src/index.ts
packages/tiler/src/raster.ts

As raster Topo map got edge effects on low zoom levels usually below zoom 6, like following. 
We have tests that with output resize kernel of `mitchell` and disable the fastShrinkOnLoad for lower scales levels will fix this problem. 
- Add the resiseKernel setting in the config bundle, so that we can bundle it into server.
- disable `fastShrinkOnLoad` for the `resize.scale`less than 0.125.
- Not fix yet: The virtual tileset for `topo-raster-50k` and `topo-raster-250k` won't fix as we can't propagate the resize kernel from combined tileset -> imagery config -> virtual tileset. Unless we add optional resizeKernal property for imagery config. 
Local test.

feat(config): Add resizeKernel into the config tileset then disable fastShrinkOnLoad. BM-1146

---

.github/workflows/containers.yml
.github/workflows/pull-request-container.yml

The master branch should be have tested code run on it, sometime we need containers to be built and pushed so that we can use the containers in other locations eg github actions or argo workflows
adds a "container" label that can be added to pull requests to generate containers for the server and CLI

build: create containers from pull requests for testing

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/parse.tile.set.ts
packages/config/src/config/tile.set.ts
packages/tiler-sharp/src/index.ts
packages/tiler/src/raster.ts

We are adding the background in the imagery importing process(#3379), so we don't need this for fixing the edge effects.
This reverts commit bd3357e5c6dee34a6e458a2ac956643468f8fb2c.

revert(config): Add resizeKernel into the config tileset then disable fastShrinkOnLoad.

---

packages/landing/src/components/map.label.tsx
packages/landing/src/config.map.ts

We need to add topo-raster style into the layer dropdown and have the labels disabled for it.
Add another hardcode topo-raster style for the layer dropdown. We will need to clean up all the hardcode category in BM-1154

feat(landing): Add topo-raster into layer dropdown. BM-1153

---

packages/landing/src/components/layer.switcher.dropdown.tsx

We want to locate the topo-raster individual layers category just above bathmetry
Add Topographic between Event and Bathymetry

feat(landing): insert the 'topographic' category and layers between the 'event' and 'bathymetry' categories. BM-1119

---

packages/lambda-analytic-cloudfront/src/__test__/analytics.test.ts
packages/lambda-analytic-cloudfront/src/date.ts
packages/lambda-analytic-cloudfront/src/useragent/agents/gis.ts
tsconfig.json

`lambda-analytic-cloudfront` was missing from the project reference and was not being built
Add `lambda-analytic-cloudfront` to the project references so it builds

refactor: add missing project reference

---

packages/_infra/src/analytics/edge.analytics.ts

A path was typoed causing the cdk deployment to fail
corrected typo in path
ran a `cdk synth` locally to validate path

fix(infra): correct dist path location

---

packages/lambda-tiler/src/cli/render.tile.ts
packages/tiler-sharp/src/pipeline/__tests__/pipeline.color.ramp.test.ts
packages/tiler-sharp/src/pipeline/decompressor.lerc.ts
packages/tiler-sharp/src/pipeline/decompressor.ts
packages/tiler-sharp/src/pipeline/pipeline.color.ramp.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts

We are getting datasets that have other datatypes than float32 that need to be expanded into 4 band RGBA so basemaps can render them.
A common type is a one band `uint8` which is generally a grey scale dataset which can be directly band expanded from `0` to `r:0, g:0, b:0, alpha: 255` and `255` to `r:255, g:255, b:255, alpha: 255`
Added support for `uint8` and `uint32` with the tiler piplines
TODO: it would be nicer to handle the datatypes more generically, to hopefully avoid giant switch case statements, we should in theory be able to trust that lerc gives us the correct typed array for instance.
Added unit tests and rendered it locally

feat(tiler-sharp): support uint32 and uint8 source datasets for color-ramp

---

packages/tiler-sharp/src/pipeline/__tests__/pipeline.resize.test.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts

When resampling `uint` it can end up resampling slightly high or low eg resampling `1` can result in `1.00..01` or `0.99999..`
When setting a number on a Uint8Array floating point numbers are truncated, so `0.9999` will be rounded down to `0` rather than up to `1`.
When resampling `uint` round numbers before assigning them.
Added unit test to validate rounding

fix(tiler-sharp): when resampling uint round numbers rather than truncate

---

package-lock.json
packages/landing/package.json

This reverts commit de4fbf501701801a7eaffbca70f426424fc970d1.
We are seeing some minor shifts in panning/zooming behaviour in 3d mode that we want to explore more before upading the production service to maplibre5
Reverts maplibre 5.0 upgrade.

fix: revert "build: maplibre v5.0.0 (#3387)"

---

CHANGELOG.md
lerna.json
package-lock.json
packages/_infra/CHANGELOG.md
packages/_infra/package.json
packages/bathymetry/CHANGELOG.md
packages/bathymetry/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/cogify/CHANGELOG.md
packages/cogify/package.json
packages/config-loader/CHANGELOG.md
packages/config-loader/package.json
packages/config/CHANGELOG.md
packages/config/package.json
packages/lambda-analytic-cloudfront/CHANGELOG.md
packages/lambda-analytic-cloudfront/package.json
packages/lambda-analytics/CHANGELOG.md
packages/lambda-analytics/package.json
packages/lambda-tiler/CHANGELOG.md
packages/lambda-tiler/package.json
packages/landing/CHANGELOG.md
packages/landing/package.json
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/tiler-sharp/CHANGELOG.md
packages/tiler-sharp/package.json

* **infra:** correct dist path location ([#3390](https://github.com/linz/basemaps/issues/3390)) ([46f8fb8](https://github.com/linz/basemaps/commit/46f8fb8ede7163172dd9cf29ad8c779bcd327d2f))
* revert "build: maplibre v5.0.0 ([#3387](https://github.com/linz/basemaps/issues/3387))" ([#3394](https://github.com/linz/basemaps/issues/3394)) ([d441be2](https://github.com/linz/basemaps/commit/d441be2b75f507fab53df62422bed79af3eb0df3))
* **tiler-sharp:** when resampling uint round numbers rather than truncate ([#3392](https://github.com/linz/basemaps/issues/3392)) ([d02e56f](https://github.com/linz/basemaps/commit/d02e56febebc6c729fd3213390bdc5bbb66f419f))
* **cogify:** add background color support for overriding transparent pixels BM-1146 ([#3379](https://github.com/linz/basemaps/issues/3379)) …

release: v7.14.0

---

.github/workflows/screenshot.yml

`getsentry/action-visual-snapshot` has been deprecated and archived, it is no longer supported, github has recently removed support for the artifacts API it was using to store the images, causing all of these actions to fail.
Fork the github action and update it to support the newer github actions artifacts API.
this is a temporary fix with the intention to replace this github action with another more supported action in the near term.
Checking to see if the build succeeds after this is merged.
ref: https://github.com/linz/basemaps-config/pull/1039

build: upgrade visual snapshot to support new artifacts api

---

.github/workflows/containers.yml

There is a bug causing container builds to fail if the commit message contains a backtick "\`"
When github replaces the commit message it directly inserts it into the script without any escaping
```javascript
const x = ${{ github....commit_message }}
// directly replaced no quotes included, and includes \n as line breaks
const x = build: fix text.
body text here
some `comments` in the body
```
using `toJson()`
```typescript 
const x  = ${{ toJson(...commit_message) }}
// all escaped and includes a starting "
const x = "build: fix text.\nbody text here\nsome `comments` in the body"
```
using `toJson` and backticks
```typescript 
const x  = `${{ toJson(...commit_message) }}`
// Broken string
const x = `"build: fix text.\nbody text here\nsome `comments` in the body"`
//        ^ …
```

build: fix text escaping for multiline with "`" commit messages

---

packages/shared/src/file.system.ts

We have a number of configuration files to allow reading and writing of S3 buckets across accounts, sometimes it's useful to join a collection of access lists together to provide a more comprehensive list of credentials for the calling service.
Allow credentials to be loaded from multiple sources using either a comma separated list or a JSON list, this behavior is the same as the workflows inside of argo
https://github.com/linz/argo-tasks/blob/master/src/fs.register.ts#L132
Logic is taken from argo tasks, and will be tested in argo.

feat(shared): support multiple credential locations

---

packages/lambda-analytic-cloudfront/src/__test__/analytics.test.ts
packages/lambda-analytic-cloudfront/src/date.ts
packages/lambda-analytic-cloudfront/src/handler.ts

Log processing is done in batches and is restricted to at most one hour behind, there is a bug in the existing logic where logs processing can be delayed by upto a day.
This is caused by the looping logic where it subtracts one day then loops over the 24 hours of that day, so if the time is close to the day start (eg 1am utc) the logs are processed upto midnight of the day before, if the current time is close to the end of the day (eg 11pm utc) the logs will be processed up to midnight the day before.
Move the processing logic to start looping from one hour ago, 
Exclude any timestamps that are in the future.
Unit tests

fix(lambda-analytic-cloudfront): process logs upto one hour ago

---

packages/lambda-tiler/src/__tests__/config.data.ts
packages/lambda-tiler/src/routes/__tests__/xyz.test.ts
packages/lambda-tiler/src/util/validate.ts

If a tileset has only one output pipeline eg `color-ramp`, The user should not be required to add `?pipeline=color-ramp` when fetching a tile from the xyz api, it should default to the only pipeline in the tileset.
The basemap's UI does not currently allow the user to select the pipeline
Qhen there is only one pipeline automatically select it for the renderer
Tested locally against Hillshade Igor and unit tests

fix(lambda-tiler): automatically choose pipelines

---

packages/lambda-tiler/src/routes/__tests__/fonts.test.ts
packages/lambda-tiler/src/util/config.loader.ts

We currently store all of the configuration in both dynamodb and s3, inside dynamodb each config object is stored as by the config id eg `ts_aerial` in s3 all the configuration is stored a single bundle JSON file.
In DynamoDB each tileset and imagery is stored individually this can lead to a huge number of requests on dynamo as lambda functions are spun up, for instance loading the standard `ts_aerial` tile set will then load 400 imagery records for each of the individual layers inside the configuration.
This query load as lambdas are spun up can trigger throttling issues with dynamodb, the lambdas will attempt to retry the queries sometimes taking multiple seconds to load the required layers or in the worse case the lambda will hit the retry limit without successfully retrieving the …

feat(lambda-tiler): load config from s3

---

packages/tiler-sharp/src/pipeline/__tests__/pipeline.resize.test.ts
packages/tiler-sharp/src/pipeline/pipeline.resize.ts

When applying a crop on a 1-band `unit8` the crop should not change the datatype to `float32`.
Changing the data type to `float32` changes the default `color-ramp` to one used by elevation, which causes hillshades to be rendered green
Igor hillshade before Fix:
After Fix:
Ensure the input data type is preserved when output datatype is made
Unit tests and raw tiles rendered.

fix(tiler-sharp): when resizing preserve input data type

---

packages/tiler-sharp/src/pipeline/__tests__/pipeline.color.ramp.test.ts
packages/tiler-sharp/src/pipeline/colorize/color.ramp.ts
packages/tiler-sharp/src/pipeline/colorize/colorize.ts
packages/tiler-sharp/src/pipeline/colorize/grey.scale.ts
packages/tiler-sharp/src/pipeline/pipeline.color.ramp.ts

Currently when expanding a `uint8` color into a 4-band RGBA `uint8,uint8,uint8,uint8` the `color-ramp` is used which is not designed for a direct color mapping. 
For a 1024x1024 tile the current color ramp implementation takes approx 7ms to convert a 1-band to 4 band grey scale, using a direct band expansion drops the time taken to approx 1ms.
This pull requests creates a simple color mapper where given a input value (eg 240) it is propagated to the R,G and B bands of the output eg `240,240,240` creating a grey scale image from a one band input.
Create a specialised `Colorizer` for one band inputs that is significantly (5x) faster than  using a color ramp directly
Unit tests to validate inputs and outputs are the same between implementations

perf(tiler-sharp): split greyscale  color ramps into specalized function

---

packages/geo/src/index.ts
packages/landing/src/components/map.switcher.tsx
packages/landing/src/components/map.tsx
packages/landing/src/tile.matrix.ts

We have datasets in CITM2000 we need a way to easily view them in CITM2000, the landing page as it uses maplibre needs to have custom projection logic for each tile matrix it uses, which is currently hardcoded and missing CITM
Remove the hard coded list of projections from the landing page, reusing the existing list that the server supports.
Tested locally with CITM2000 imagery from 1982

fix(landing): support viewing CITM2000Quad

---

packages/landing/src/components/layout.header.tsx

API keys not expiring after 90 days, make that clear in the UI
Updated text from `API keys expire after 90 days, if a longer duration is needed please request a developer API key` to `These API keys are for individual users. For use in shared or public maps, apps or tools, please request a free Developer API key.`
| Before | After |
| - | - |
| ![][img_before] | ![][img_after] |
[dsm-config]: https://github.com/linz/basemaps-config/blob/master/config/tileset/elevation.dsm.json
[img_before]: https://github.com/user-attachments/assets/10649af1-cf5e-433c-82b1-c69326303135
[img_after]: https://github.com/user-attachments/assets/565aaf45-c692-4a89-9408-90948aedb1f4

feat(landing): change text 90day api keys to single user api keys BM-1181

---

packages/landing/src/config.map.ts

We've recently published an [Elevation DSM Basemap][dsm-config]. This work add a new "Elevation DSM" entry to the `Layers` dropdown, so that customers can view the new Basemap in our application.
1. Added a new "Elevation DSM" entry to the `Layers` dropdown.
2. Renamed the existing "Elevation" entry to "Elevation DEM".
| Before | After |
| - | - |
| ![][img_before] | ![][img_after] |
[dsm-config]: https://github.com/linz/basemaps-config/blob/master/config/tileset/elevation.dsm.json
[img_before]: https://github.com/user-attachments/assets/1cf65ae8-fd0d-4f95-9590-709a57723aba
[img_after]: https://github.com/user-attachments/assets/e68dbba3-0d09-43ec-8d30-5ebaf1ec9cad

feat(landing): add dsm to layer dropdown BM-1248

---

CHANGELOG.md
lerna.json
package-lock.json
packages/landing/CHANGELOG.md
packages/landing/package.json

* **landing:** Add hillshade and hillshade igor into the layer dropdown. BM-1250 ([#3425](https://github.com/linz/basemaps/issues/3425)) ([a02fb6a](https://github.com/linz/basemaps/commit/a02fb6a250f2a7d66d0bd6640f72a6ea4ad8322a))

release: v7.17.0

---

packages/cli-raster/package.json
packages/geo/package.json
packages/landing/package.json
scripts/detect.unlinked.dep.mjs

There is a weird behaviour in this monorepo that when importing packages that are present inside the monorepo can be imported freely anywhere inside the monorepo, but when the package is published it needs to exist inside the package.json or it will not be installed correctly.
We have a script that detects when this happens `scripts/detect.unlinked.dep.mjs` but it was only functioning for `@basemaps/*` packages in this repository there are a few `@linzjs/` packages.
Ensure linzjs packages are also checked as part of CI
Add the missing links between a few packages and `@linzjs/geojson` and `@linzjs/metrics`
`detect.unlinked.dep.mjs` found these packages once it was updated to include looking for `@linzjs`
Fixes #3438

fix: ensure all linzjs packages are correctly labeled as deps

---

packages/_infra/src/serve/lambda.tiler.ts
packages/lambda-tiler/src/util/__test__/validate.test.ts
packages/lambda-tiler/src/util/validate.ts
packages/shared/src/const.ts

We have seen a increase of consumer api keys using scripted methods to pull large amounts of data from basemaps.linz.govt.nz these users should be using bulk data access methods like linz/imagery or limz/elevation, as the keys are only consumer we have no easy way of contacting them.
Our only option is to disable their keys and hope that they reach out.
Add a environment variable to allow us to block API keys 
unit tests and further tests in nonprod.

feat(lambda-tiler)!: allow API keys to be disabled BM-1281

---

.github/workflows/push.yml

a github environment secret sets the api key blocks, but it was not being passed to the CD process so the blocks are not being set automatically on deployment.
Allow the CD process to have access to the blocked api keys
will check nonprod after deployment.

fix: ensure api key blocks are set in ci/cd

---

packages/config/src/memory/memory.config.ts
packages/lambda-tiler/src/__tests__/index.test.ts
packages/lambda-tiler/src/routes/version.ts

I would like to know what configuration is in use on each instance of basemaps, we have a version endpoint `/v1/version` that gives the build information (commit hash, github actions run id) but does not say what configuration is being used.
If the current configuration has a `id` and `hash` return those as `{ config: { id, hash} }`
```json
{ 
"id": "cb_01JTQ7ZK49F8EY4N5DRJ3XFT73", 
"hash": "HcByZ8WS2zpaTxFJp6wSKg2eUpwahLqAGEQdcDxKxqp6" 
}
```
Unit tests + running locally

feat(lambda-tiler): expose configuration id and hash if present

---

packages/_infra/src/serve/lambda.tiler.ts

Dev deployments are currently broken as the enviroment variable is `''` and not `null` so the check to skip blocked keys is not guarding correctly
Check for string length to see if there is any content
diffed locally.

fix: parsing of blocked api keys

---

.github/workflows/containers.yml

When releases are made, the production `v8.0.1` tag is created after the containers are built causing the containers to be released on the wrong tag.
Ensure the production tags are created before containers are tagged.
Wait for containers to build

build: ensure production tags are made before container tags are made

---

packages/shared/src/file.system.ts

Allow basemaps to access data from nz-coastal bucket.
Assign `nz-coastal` as a bucket that can be accessed without signing the requests.

feat(shared): allow access to s3 nz-coastal public bucket

---

CHANGELOG.md
lerna.json
package-lock.json
packages/_infra/CHANGELOG.md
packages/_infra/package.json
packages/bathymetry/CHANGELOG.md
packages/bathymetry/package.json
packages/cli-config/CHANGELOG.md
packages/cli-config/package.json
packages/cli-raster/CHANGELOG.md
packages/cli-raster/package.json
packages/cli-vector/CHANGELOG.md
packages/cli-vector/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/config-loader/CHANGELOG.md
packages/config-loader/package.json
packages/lambda-analytic-cloudfront/CHANGELOG.md
packages/lambda-analytic-cloudfront/package.json
packages/lambda-analytics/CHANGELOG.md
packages/lambda-analytics/package.json
packages/lambda-tiler/CHANGELOG.md
packages/lambda-tiler/package.json
packages/landing/CHANGELOG.md
packages/landing/package.json
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json

* remove quoting from rimraf commands ([#3434](https://github.com/linz/basemaps/issues/3434)) ([58f31da](https://github.com/linz/basemaps/commit/58f31da0a56a654366881bfb39310f8adabcbd93))
* **cli-vector:** analyse mbtiles BM-1270 ([#3444](https://github.com/linz/basemaps/issues/3444)) ([e721392](https://github.com/linz/basemaps/commit/e721392d52866ef0d31e110d32e718460ce3008b))
* **cli-vector:** New cli to create and join mbtiles for vector map. BM-1268 ([#3435](https://github.com/linz/basemaps/issues/3435)) ([8cbef0b](https://github.com/linz/basemaps/commit/8cbef0b0a9ef3db804d05b533b6858f55c9064c9))
* **shared:** allow access to s3 nz-coastal public bucket ([#3453](https://github.com/linz/basemaps/issues/3453)) ([ab54746](https://github.com/linz/basemaps/commit/ab5474681084355b0168b85e89e5 …

release: v8.2.0

---

packages/landing/src/config.map.ts
packages/landing/src/debug.map.ts

Debug page is hiding the layers that is not equal to `topographic`, which will hide the layer when `i=topographic-v2`.
Update the check as startWith('topographic') to include all the versions in future.
Broken in production: 
https://basemaps.linz.govt.nz/@-41.8899962,174.0492437,z5?style=topographic-v2&i=topographic-v2&debug=true
Fixed in local test:

fix(landing): Fix debug page automatically hide topographic-v2. BM-1302

---

packages/cli-config/src/cli/action.import.ts

Imagery was mistakenly deleted from basemaps config as it was hidden in a config diff, it is very easy to miss it in the huge lists of words
Add color and symbol differences for new, update and delete

feat(cli-config): be very clear that imagery is about to be removed from the config

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli-config/CHANGELOG.md
packages/cli-config/package.json
packages/cli-vector/CHANGELOG.md
packages/cli-vector/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/landing/CHANGELOG.md
packages/landing/package.json

* **cli-vector:** Fix the stac item format missing datetime in properties. BM-1317 ([#3464](https://github.com/linz/basemaps/issues/3464)) ([6c7719f](https://github.com/linz/basemaps/commit/6c7719f7514160158b6ad14b680fe1bdd10fd1e3))
* **cli-vector:** revert polylabel version to 1.1.0 BM-1309 ([#3467](https://github.com/linz/basemaps/issues/3467)) ([e2039fa](https://github.com/linz/basemaps/commit/e2039fa587467010e399f064f187381eee8a3ac0))
* **cli-config:** Support vector preview links and reports for NZTM. BM-1253 ([#3463](https://github.com/linz/basemaps/issues/3463)) ([5ab6a5b](https://github.com/linz/basemaps/commit/5ab6a5bdd19885f8a461bece0d2736c7ed7269d9))
* **cli-vector:** adjust the layers assigned to each schema layer BM-1299 ([#3462](https://github.com/linz/basemaps/issues/3462)) …

release: v8.4.0

---

packages/cli-vector/src/cli/cli.extract.ts
packages/cli-vector/src/stac.ts

We need to validate the stac files for mbtile cache, so adding collection.json and catalog.json will make the validation recursively for all the stac files.
Create stac files in the following structure.
- `s3://linz-basemaps-staging/mbtiles-cache/3857/catalog.json`
- `s3://linz-basemaps-staging/mbtiles-cache/3857/50348/collection.json`
Validates in argo: https://argo.linzaccess.com/workflows/argo/test-basemaps-vector-etl-shortbread-stac-pqvcp?tab=workflow&nodeId=test-basemaps-vector-etl-shortbread-stac-pqvcp-1403105050&uid=870c6422-5dc6-4333-9e22-2ba266fce6c7

feat(cli-vector): Add stac collection and stac catalog for the extract command. BM-1307

---

package-lock.json
packages/lambda-tiler/src/index.ts
packages/lambda-tiler/src/routes/__tests__/export.test.ts
packages/lambda-tiler/src/routes/export.tileset.ts
packages/shared/package.json
packages/shared/src/file.system.ts
packages/shared/src/index.ts

We have had a number of requests to gain direct access to the current mbtiles files, while sometime in the future they will be part of LINZs Open Data Registry https://github.com/linz/topography a quick option is to presign access to the current mbtiles until they are ready to be made fully public
Adds a  `/v1/export/:tileSet/:tileMatrix.mbtiles` route to export any dataset that has a `.mbtiles` file associated eg `topographic`
Unit tests, will need to run in dev to validate the full redirect logic.

feat(lambda-tiler): add export URL for mbtiles

---

CHANGELOG.md
lerna.json
package-lock.json
packages/_infra/CHANGELOG.md
packages/_infra/package.json
packages/bathymetry/CHANGELOG.md
packages/bathymetry/package.json
packages/cli-config/CHANGELOG.md
packages/cli-config/package.json
packages/cli-raster/CHANGELOG.md
packages/cli-raster/package.json
packages/cli-vector/CHANGELOG.md
packages/cli-vector/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/config-loader/CHANGELOG.md
packages/config-loader/package.json
packages/lambda-analytic-cloudfront/CHANGELOG.md
packages/lambda-analytic-cloudfront/package.json
packages/lambda-analytics/CHANGELOG.md
packages/lambda-analytics/package.json
packages/lambda-tiler/CHANGELOG.md
packages/lambda-tiler/package.json
packages/landing/CHANGELOG.md
packages/landing/package.json
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json

* **cli-vector:** Add stac collection and stac catalog for the extract command. BM-1307 ([#3472](https://github.com/linz/basemaps/issues/3472)) ([b357022](https://github.com/linz/basemaps/commit/b3570226f61ab035b5c6449dd0077cac5a6320db))
* **lambda-tiler:** add export URL for mbtiles ([#3474](https://github.com/linz/basemaps/issues/3474)) ([e15c811](https://github.com/linz/basemaps/commit/e15c8117cf19d6021a0e7a275fccf72a5449c4b2))

release: v8.5.0

---

packages/landing/src/config.map.ts

Two new national DSM hillshade layers have been published in AWS ODR. We want these layers to be published via basemaps for individual use and combined use in our various configs (Aerial, Topographic v2, NZ Topo).
add dsm and dsm igor

feat(landing): add dsm hillshade

---

packages/config-loader/src/json/json.config.ts
packages/config-loader/src/json/parse.tile.set.ts
packages/config/README.md
packages/config/src/config/base.ts
packages/config/src/config/tile.set.ts
packages/config/src/memory/__tests__/memory.config.test.ts
packages/config/src/memory/memory.config.ts

Aerial Imagery PRs with the 'Aerial Imagery Deletes' messages are breaking existing WMTS links, 'urban' or 'rural' has been removed from the layer name as it's taken out of the aerial config, which in turn, changes the URL of the individual layer WMTS
Add an `aliases` property so that tilesets can be linked by different names:
added test

feat: add aliases for tileSets

---

packages/cli-raster/src/cogify/cli/__test__/cli.charts.test.ts
packages/cli-raster/src/cogify/cli/cli.charts.ts

Some of imagery metadata like bbox and gds tagging is not exist from the source imagery in folder `s3://linz-hydrographic-upload/charts/NChart1200/`, however, they are all exists in the `s3://linz-hydrographic-upload/charts/CChart/`.
So we can back off to fetch the meta data from `CCharts`.
New function to prepare and fetch all the matedata for charts imagery.
Processed CK141-7 again, this time applying metadata from the backup imagery to replace the missing georeferencing.

feat(cli-raster): Fetch chart imagery metadata from backup location.BM-1345

---

packages/cli-vector/src/cli/cli.create.ts
packages/cli-vector/src/util.ts

ETL got failed when processing shared layers in different schema with concurrency. The reason is they share a same download file and one of the process might use half downloaded file.
- Add try catch for etl create, to log the error layer id for investigation when failure with async process.
- Add schema path for the layer download files, so that we don't need to share same downloaded file in the tmp folder.
Tested locally with multi concurrency. Same test was failure before the fix.

fix(cli-vector): Fix the tmp path of download layers and add try catch. BM-1352

---

packages/config/src/memory/__tests__/memory.config.test.ts

A unit test was comparing two ULID's time components which could be generated on the same millisecond, which caused the test to fail as it expects the first id to be older than the second.
make the first id much older than the current time.
ran the test 100x to see if it would fail again, was failing approx 1 in 5 before the change.

fix: intermittent unit tests

---

packages/landing/src/components/map.switcher.tsx

Change the behaviour of the quick change button on https://basemaps.linz.govt.nz/  to cycle between the following maps:
1. Aerial
2. Topographic
3. NZ Topo Gridless
4. TopoLite
5. Hillshade Igor DEM
6. Hillshade Igor DSM
visual

feat(landing): quick change cycles through more basemaps BM-1293

---

.github/workflows/containers.yml
.github/workflows/push.yml
.github/workflows/screenshot.yml
.github/workflows/smoke-test.yml
package-lock.json
package.json
packages/_infra/package.json
packages/_infra/src/serve/lambda.tiler.ts
packages/attribution/package.json
packages/bathymetry/package.json
packages/cli-config/package.json
packages/cli-raster/package.json
packages/cli-vector/package.json
packages/cli/package.json
packages/config-loader/package.json
packages/config/package.json
packages/geo/package.json
packages/lambda-analytic-cloudfront/package.json
packages/lambda-analytics/package.json
packages/lambda-tiler/package.json
packages/landing/package.json
packages/linzjs-docker-command/package.json
packages/linzjs-geojson/package.json
packages/linzjs-metrics/package.json
packages/server/Dockerfile
packages/server/package.json
packages/shared/package.json
packages/sprites/package.json
packages/tiler-sharp/package.json
packages/tiler/package.json

the new ZSTD decompression APIs are only added in node24, in preparation for node24 coming to aws lambda upgrade to node24
Swapped to the new node --test globber as the globbing logic has changed and broken the current state
Upgraded lambdas to node 22 (Current latest version, we are waiting for node24 lambda to release)
Upgraded containers to node 24
Upgrade pipelines to node 24
unit tests, local imagery service.

build: node 24

---

package-lock.json
packages/landing/src/components/map.label.tsx
packages/landing/src/config.map.ts

update drop down for gridded and gridless topo
visual

feat(landing): new topo dropdowns BM-1376 

---

packages/landing/src/components/map.label.tsx
packages/landing/src/config.map.ts

This PR assists [this PR].
[this PR]: https://github.com/linz/basemaps-config/pull/1327
---
In a recent [piece of work], we switched our `topo-raster` tileset to serve the 600 DPI `gridded` map sheets. This changed the imagery for our customers who were consuming our original `topo-raster` endpoint. We've decided we want to switch the original endpoint back to serving the `gridless` map sheets.
[piece of work]: https://github.com/linz/basemaps-config/pull/1319

fix(landing): keep gridless default
